import fs from "node:fs";import {spawn,execFileSync} from "node:child_process";import assert from "node:assert/strict";import {chromium} from "@playwright/test";
const out=process.env.RIFT_EVIDENCE_DIR||"../../.evidence/rift-1.4";fs.mkdirSync(out,{recursive:true});const server=spawn(process.execPath,["node_modules/vite/bin/vite.js","--host","127.0.0.1","--port","4173"],{stdio:"inherit"});let browser;
try{for(let i=0;i<60;i++){try{if((await fetch("http://127.0.0.1:4173")).ok)break;}catch{}await new Promise(r=>setTimeout(r,250));}
browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true}),errors=[];page.on("pageerror",e=>errors.push(e.message));await page.goto("http://127.0.0.1:4173");await page.locator("#home").waitFor({state:"visible"});await page.screenshot({path:out+"/home.png",scale:"css"});await page.locator("#start").click();
await page.evaluate(()=>{const g=window.__riftTest.game;g.enemies=[];g.events=[];g.cool.blade=999;g.spawnCd=999;g.nextElite=999;g.player.inv=10;g.time=46;g.level=5;g.weapons={blade:3};for(let i=0;i<7;i++){const e=g.spawn(i%3?"shade":"brute"),a=-1.1+i*.40,r=95+i*8;e.x=g.player.x+Math.cos(a)*r;e.y=g.player.y+Math.sin(a)*r;e.hp=e.maxHp=700;e.speed=0;}g.attack("blade",3);for(let i=0;i<5;i++)g.step(1/60);g.phase="paused";document.querySelector("#banner").style.opacity=0;});await page.waitForTimeout(100);await page.screenshot({path:out+"/anticipation.png",scale:"css"});
await page.evaluate(()=>{const g=window.__riftTest.game;g.phase="playing";for(let i=0;i<4;i++)g.step(1/60);g.phase="paused";});await page.waitForTimeout(100);await page.screenshot({path:out+"/combat.png",scale:"css"});
await page.evaluate(()=>{const g=window.__riftTest.game;g.phase="playing";for(let i=0;i<12;i++)g.step(1/60);g.phase="paused";});await page.waitForTimeout(100);await page.screenshot({path:out+"/recovery.png",scale:"css"});
await page.goto("http://127.0.0.1:4173/?practice=blade");await page.locator("#home").waitFor({state:"visible"});await page.evaluate(()=>{const t=window.__riftTest,a=t.audio,destination=a.context.createMediaStreamDestination();a.output.connect(destination);const stream=document.querySelector("#world").captureStream(30);for(const track of destination.stream.getAudioTracks())stream.addTrack(track);const recorder=new MediaRecorder(stream,{mimeType:"video/webm;codecs=vp8,opus",videoBitsPerSecond:1800000,audioBitsPerSecond:128000}),chunks=[];window.__recording=recorder;window.__recorded=new Promise(resolve=>{recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=async()=>{const bytes=new Uint8Array(await new Blob(chunks,{type:recorder.mimeType}).arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));resolve(btoa(binary));};});recorder.start();});
await page.locator("#start").click();await page.waitForTimeout(15000);await page.evaluate(()=>window.__recording.stop());const encoded=await page.evaluate(()=>window.__recorded),webm="/tmp/rift-sword.webm";fs.writeFileSync(webm,Buffer.from(encoded,"base64"));
execFileSync("ffmpeg",["-hide_banner","-loglevel","error","-y","-i",webm,"-t","15","-vf","scale=390:844","-c:v","libx264","-preset","fast","-crf","24","-pix_fmt","yuv420p","-c:a","aac","-b:a","128k","-movflags","+faststart",out+"/knight-15s.mp4"]);
const video=JSON.parse(execFileSync("ffprobe",["-v","quiet","-show_streams","-show_format","-of","json",out+"/knight-15s.mp4"],{encoding:"utf8"}));assert.ok(video.streams.some(s=>s.codec_type==="audio"));assert.ok(Number(video.format.duration)>14.8);console.log("Recorded actual practice gameplay with Web Audio",video.format.duration,fs.statSync(out+"/knight-15s.mp4").size);
execFileSync("ffmpeg",["-hide_banner","-i",out+"/knight-15s.mp4","-af","volumedetect","-vn","-sn","-dn","-f","null","-"],{stdio:["ignore","ignore","inherit"]});
await page.goto("http://127.0.0.1:4173");await page.locator("#home").waitFor({state:"visible"});await page.setViewportSize({width:360,height:640});await page.waitForTimeout(100);await page.screenshot({path:out+"/small-phone.png",scale:"css"});assert.equal(errors.length,0,errors.join("\n"));const start=await page.locator("#start").boundingBox();assert.ok(start.y+start.height<640);
fs.writeFileSync(out+"/manifest.json",JSON.stringify({version:"1.4.0",engine:"Chromium",nativePhoneTest:false,recordedAudio:true,video:"knight-15s.mp4",screenshots:["home.png","anticipation.png","combat.png","recovery.png","small-phone.png"],combatScene:"Animation stage verification fixture; video uses the public sword-practice mode",errors},null,2));
}finally{await browser?.close();server.kill("SIGTERM");}
