import fs from "node:fs";import {spawn} from "node:child_process";import assert from "node:assert/strict";import sharp from "sharp";import {chromium} from "@playwright/test";
const out=process.env.RIFT_EVIDENCE_DIR||"../../.evidence/rift-1.5";fs.mkdirSync(out,{recursive:true});const server=spawn(process.execPath,["node_modules/vite/bin/vite.js","--host","127.0.0.1","--port","4173"],{stdio:"inherit"});let browser;const screenshots=[];
try{for(let i=0;i<60;i++){try{if((await fetch("http://127.0.0.1:4173")).ok)break;}catch{}await new Promise(r=>setTimeout(r,250));}
browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true}),errors=[];page.on("pageerror",e=>errors.push(e.message));
async function shot(name){await page.waitForTimeout(120);await sharp(await page.screenshot({scale:"css"})).webp({quality:88}).toFile(out+"/"+name+".webp");screenshots.push(name+".webp");}
for(const [hero,key]of [["knight","blade"],["ranger","arrow"],["mage","bolt"]]){
await page.goto("http://127.0.0.1:4173/?practice="+key);await page.locator("#home").waitFor({state:"visible"});assert.equal(await page.evaluate(()=>window.__riftTest.audio.buffers.size),19);await shot(hero+"-home");await page.locator("#start").click();
await page.evaluate(key=>{const g=window.__riftTest.game;g.enemies=[];g.events=[];g.bullets=[];g.bladeSwing=null;g.rangedAttacks={};g.cool[key]=999;g.spawnCd=999;g.nextElite=999;g.time=4;g.weapons={[key]:3};for(let i=0;i<5;i++){const e=g.spawn(i%2?"shade":"brute");Object.assign(e,{x:g.player.x+100+i*10,y:g.player.y-55+i*24,hp:700,maxHp:700,speed:0});}g.events=[];g.attack(key,3);g.phase="paused";document.querySelector("#banner").style.opacity=0;},key);
await page.evaluate(key=>{const g=window.__riftTest.game;g.phase="playing";const steps=key==="blade"?5:key==="arrow"?7:11;for(let i=0;i<steps;i++)g.step(1/60);g.phase="paused";},key);await shot(hero+"-prepare");
await page.evaluate(key=>{const g=window.__riftTest.game;g.phase="playing";for(let i=0;i<10;i++){g.step(1/60);if(key==="blade"?g.bladeSwing?.started:g.rangedAttacks[key]?.released)break;}g.phase="paused";},key);await shot(hero+"-release");
await page.evaluate(key=>{const g=window.__riftTest.game;g.events=[];g.phase="playing";let hit=false;for(let i=0;i<60;i++){g.step(1/60);if(g.events.some(e=>e.type===(key==="blade"?"blade-contact":"projectile-contact"))){hit=true;break;}}g.phase="paused";if(!hit)throw new Error("No contact captured for "+key);},key);await shot(hero+"-contact");
console.log("Captured "+hero+" preparation, release and real projectile/contact response");
}
for(const key of ["arrow","bolt"]){await page.setViewportSize({width:360,height:640});await page.goto("http://127.0.0.1:4173/?practice="+key);await page.locator("#home").waitFor({state:"visible"});const start=await page.locator("#start").boundingBox();assert.ok(start.y+start.height<640);await shot(key+"-small-phone");}
assert.deepEqual(errors,[]);fs.writeFileSync(out+"/manifest.json",JSON.stringify({version:"1.5.0",engine:"Chromium",nativePhoneTest:false,screenshots,scene:"Actual renderer with fixed close target positions to inspect animation timing; normal public practice is tested separately",errors},null,2));console.log("All three heroes captured with no page errors");
}finally{await browser?.close();server.kill("SIGTERM");}
