import {Art} from "./art.js";
import {drawPainted} from "./painted-vfx.js";
import {drawWhirlwind,drawFrostCrown,drawFrostPulse,drawMetalContact,drawForgedBlade,drawFracturedCrystal} from "./hero-vfx.js";
// Painted contact material follows the collision plane; geometry remains a fallback.
const RF_TAU=Math.PI*2,rfCap=v=>Math.max(0,Math.min(1,v)),rfEase=v=>1-(1-rfCap(v))**3;
const rfRand=(i,s=0)=>{const n=Math.sin(i*127.1+s*17.7)*43758.5453;return n-Math.floor(n);};
const rfColors={steel:{dark:"#203344",mid:"#819ba7",edge:"#edf1da",spark:"#e6bb75"},ice:{dark:"#173e59",mid:"#6ab4ca",edge:"#ecfff8",spark:"#aeeaff"},fire:{dark:"#612618",mid:"#ed6c30",edge:"#ffefad",spark:"#ffb853"},stone:{dark:"#302e2b",mid:"#817366",edge:"#c8b58c",spark:"#ebbc69"},toxin:{dark:"#263627",mid:"#7c9f53",edge:"#d6e4a5",spark:"#acd76b"},void:{dark:"#201d45",mid:"#8771c8",edge:"#e7ddff",spark:"#bea0ef"},blood:{dark:"#481f2b",mid:"#9e4956",edge:"#f7b3a4",spark:"#d87572"},storm:{dark:"#1c3556",mid:"#83b5df",edge:"#f4ffff",spark:"#b0dcff"}};
function rfMaterial(key){return ["fireball","meteor","pyre","burn","explosive"].includes(key)?"fire":["bolt","frost","nova","dragon","ultimate-mage"].includes(key)?"ice":["slam","hammer","fissure","judgment"].includes(key)?"stone":["poison","poison-dot","trap","thorns"].includes(key)?"toxin":["beam","gravity","blackflame","spirit"].includes(key)?"void":["lightning","stormbow"].includes(key)?"storm":["rend","bleed"].includes(key)?"blood":"steel";}
function rfPoly(c,points,color){if(!points.length)return;c.fillStyle=color;c.beginPath();c.moveTo(...points[0]);for(let i=1;i<points.length;i++)c.lineTo(...points[i]);c.closePath();c.fill();}
function rfLine(c,points,color,width=1){if(points.length<2)return;c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(...points[0]);for(let i=1;i<points.length;i++)c.lineTo(...points[i]);c.stroke();}
function rfGradient(c,x1,y1,x2,y2,stops){const g=c.createLinearGradient(x1,y1,x2,y2);for(const [at,color]of stops)g.addColorStop(at,color);return g;}
function rfCracks(c,x,y,radius,u,alpha,material="stone",count=7){const p=rfColors[material];c.save();c.translate(x,y);c.globalAlpha*=alpha;for(let i=0;i<count;i++){const a=i*2.399+.2*rfRand(i,x),length=radius*(.5+.45*rfRand(i,y))*rfEase(u),pts=[[Math.cos(a)*9,Math.sin(a)*7]];for(let j=1;j<=5;j++){const q=j/5,bend=(rfRand(i*7+j,y)-.5)*15*q;pts.push([Math.cos(a)*length*q-Math.sin(a)*bend,Math.sin(a)*length*q+Math.cos(a)*bend]);}rfLine(c,pts,p.dark,3.5);rfLine(c,pts,p.mid,1.1);if(i%2===0){const b=pts[3];rfLine(c,[b,[b[0]+Math.cos(a+.6)*length*.16,b[1]+Math.sin(a+.6)*length*.16]],p.mid,.75);}}c.restore();}
function rfFragments(c,x,y,radius,u,material,count=8,angle=null){const p=rfColors[material],fade=(1-u)**1.6;c.save();c.globalAlpha*=fade;for(let i=0;i<count;i++){const a=angle===null?i*2.399:(angle+Math.PI)+(rfRand(i,x)-.5)*2.3,d=(7+u*radius)*(.5+rfRand(i,y)*.5),xx=x+Math.cos(a)*d,yy=y+Math.sin(a)*d-Math.sin(u*Math.PI)*radius*.14,w=(2.2+rfRand(i,x)*3.4)*(1-u*.5);c.save();c.translate(xx,yy);c.rotate(a+u*4);if(material==="steel"||material==="storm"){rfLine(c,[[-w*2,0],[w,0]],i%2?p.spark:p.edge,1.3);}else{rfPoly(c,[[w,0],[0,-w*.65],[-w*.8,-w*.1],[-w*.35,w*.65]],p.mid);rfPoly(c,[[w,0],[0,-w*.65],[-w*.18,0]],p.edge);rfLine(c,[[0,-w*.65],[w,0]],p.edge,.7);}c.restore();}c.restore();}
function rfGround(c,x,y,radius,material,alpha=.55){const p=rfColors[material];c.save();c.translate(x,y);c.globalAlpha*=alpha;const grad=c.createRadialGradient(0,0,radius*.16,0,0,radius);grad.addColorStop(0,p.dark+"88");grad.addColorStop(.5,p.mid+"30");grad.addColorStop(1,p.dark+"00");c.fillStyle=grad;c.beginPath();c.arc(0,0,radius,0,RF_TAU);c.fill();for(let i=0;i<8;i++){const a=i*2.399,d=radius*(.55+rfRand(i,x)*.33),xx=Math.cos(a)*d,yy=Math.sin(a)*d;rfPoly(c,[[xx-9,yy],[xx-2,yy-3],[xx+8,yy-1],[xx+3,yy+3]],p.mid+"24");}c.restore();}
function rfRibbon(c,x,y,radius,angle,u,width,material,echo=false){const p=rfColors[material],front=-1.33+2.64*rfEase(u/.39),tail=Math.max(-1.35,front-(u<.39?.98:2.6)),outer=[],inner=[];c.save();c.translate(x,y);c.rotate(angle);c.globalAlpha*=echo?.43:1;const fade=u<.39?1:rfCap((1-u)/.61)**1.7;c.globalAlpha*=fade;for(let i=0;i<=28;i++){const q=i/28,a=tail+(front-tail)*q,w=width*Math.sin(Math.PI*q)**.62;outer.push([Math.cos(a)*(radius+w*.45),Math.sin(a)*(radius+w*.45)]);inner.push([Math.cos(a)*(radius-w*.55),Math.sin(a)*(radius-w*.55)]);}rfPoly(c,[...outer,...inner.reverse()],rfGradient(c,-radius,-radius,radius,radius,[[0,p.dark+"55"],[.4,p.mid+"a0"],[.7,p.edge],[1,p.mid+"dd"]]));const edge=Array.from({length:22},(_,i)=>{const a=tail+(front-tail)*i/21;return [Math.cos(a)*radius,Math.sin(a)*radius];});rfLine(c,edge,p.edge,1.3);if(!echo)rfLine(c,edge.slice(9),p.edge,2.4);c.restore();}
function rfFlame(c,x,y,width,height,time,seed,alpha=1){if(height<1)return;if(Art.paintedReady()){const sway=Math.sin(time*11+seed)*.11;drawPainted(c,"flame",x+Math.sin(time*9+seed)*width*.10,y-height*.44,width*1.55,height,sway,alpha*.80);return;}const p=rfColors.fire;c.save();c.translate(x,y);c.globalAlpha*=alpha;const bend=Math.sin(time*12+seed*3)*width*.18,h=height,w=width;const grad=rfGradient(c,0,0,0,-h,[[0,p.dark+"bb"],[.28,p.mid+"ee"],[.7,p.spark+"cc"],[1,p.edge+"00"]]);c.fillStyle=grad;c.beginPath();c.moveTo(-w*.54,1);c.bezierCurveTo(-w*.95,-h*.28,-w*.1,-h*.5,-w*.27+bend,-h*.72);c.bezierCurveTo(w*.16+bend,-h*.6,w*.23+bend,-h*.93,bend,-h);c.bezierCurveTo(w*.62,-h*.74,w*.14,-h*.57,w*.53,-h*.29);c.bezierCurveTo(w*.83,-h*.14,w*.4,2,-w*.54,1);c.fill();c.fillStyle=rfGradient(c,0,0,0,-h*.65,[[0,"#fff7c6f0"],[.7,"#ffd675cc"],[1,"#ffd67500"]]);c.beginPath();c.moveTo(-w*.23,0);c.bezierCurveTo(-w*.37,-h*.16,w*.1,-h*.34,bend*.6,-h*.65);c.bezierCurveTo(w*.34,-h*.38,w*.37,-h*.1,w*.23,0);c.closePath();c.fill();c.restore();}
function rfArrow(c,length,material="steel",evolved=false,age=0){const p=rfColors[material],shaft=length*.73;c.save();c.translate(-length*.61,0);const tail=length*(evolved?2.7:1.75);rfPoly(c,[[-tail,0],[-shaft,-2.8],[length*.17,-1],[-shaft,2.8]],rfGradient(c,-tail,0,0,0,[[0,p.mid+"00"],[.7,p.mid+"50"],[1,p.edge+"90"]]));rfLine(c,[[-shaft,0],[length*.36,0]],"#423c30",3);rfLine(c,[[-shaft, -.7],[length*.36,-.7]],"#c8b998",.95);for(const side of [-1,1])rfPoly(c,[[-shaft,0],[-shaft-6,side*5],[-shaft+5,side*4],[-shaft+13,0]],side<0?p.edge:p.mid);rfPoly(c,[[length*.61,0],[length*.2,-5],[length*.28,0],[length*.2,5]],p.mid);rfPoly(c,[[length*.61,0],[length*.2,-5],[length*.28,0]],p.edge);if(evolved){rfLine(c,[[-shaft+7,-3.5],[length*.29,-3.5]],p.spark,.8);rfLine(c,[[-shaft+7,3.5],[length*.29,3.5]],p.mid,.8);}c.restore();}
function rfLightning(c,points,alpha=1,branches=true){c.save();c.globalAlpha*=alpha;rfLine(c,points,"#619be84a",11);rfLine(c,points,"#8ac6f5",3.1);rfLine(c,points,"#f0ffff",1.05);if(branches)for(let i=2;i<points.length-1;i+=3){const q=points[i],side=i%2?1:-1;rfLine(c,[q,[q[0]+13*side,q[1]-13],[q[0]+26*side,q[1]-7]],"#b4ddff80",.9);}c.restore();}
function rfContact(r,f,u,material){const c=r.ctx,p=rfColors[material],fade=(1-u)**2,angle=f.angle||0;if(Art.paintedReady()&&["steel","ice","storm"].includes(material)){const heavy=!!f.strong,size=(heavy?47:material==="ice"?34:28)*(1+u*.35),key=material==="steel"?"steel-impact":"frost-impact";drawPainted(c,key,f.x,f.y,size,size*.83,angle,fade*(heavy?.76:.49));return;}c.save();c.translate(f.x,f.y);c.rotate(angle);c.globalAlpha=fade;if(material==="fire"){rfFlame(c,0,6,24*(1-u*.5),40*(1-u*.4),u*2,f.x);rfFragments(c,0,0,43,u,"fire",r.reduced?3:7,0);}else if(material==="ice"){for(let i=0;i<(r.reduced?3:5);i++){const a=i*2.4;c.save();c.translate(Math.cos(a)*u*25,Math.sin(a)*u*25);c.rotate(a+.3);drawFracturedCrystal(c,8,19*(1-u*.5),.22,i,u,false);c.restore();}}else if(material==="stone"){rfCracks(c,0,5,36,u*2,1-u,"stone",4);rfFragments(c,0,0,40,u,"stone",r.reduced?3:6);}else if(material==="toxin"){for(let i=0;i<(r.reduced?3:6);i++){const a=i*2.399,d=6+u*27;c.fillStyle=i%2?p.mid:p.edge;c.beginPath();c.ellipse(Math.cos(a)*d,Math.sin(a)*d,2.5*(1-u*.6),1.4,a,0,RF_TAU);c.fill();}}else if(material==="void"){for(let i=0;i<3;i++){const q=i*2.399,dist=28*(1-u);rfLine(c,[[Math.cos(q)*dist,Math.sin(q)*dist],[Math.cos(q+.6)*dist*.4,Math.sin(q+.6)*dist*.4],[0,0]],i%2?p.mid:p.edge,1.8);}rfFragments(c,0,0,28,u,"void",r.reduced?3:5);}else{rfLine(c,[[-12-10*u,0],[12+10*u,0]],p.edge,2.2);rfLine(c,[[-6,-11],[8,12]],p.mid,1.1);rfFragments(c,0,0,29,u,material,r.reduced?3:5,0);}c.restore();}
export function drawMaterialEffect(r,f,t,g,a,u){
const c=r.ctx,x=f.follow?g.player.x:f.x,y=f.follow?g.player.y-18:f.y,age=Math.max(0,f.max-f.ttl),radius=f.r||48,detail=!r.reduced&&r.quality>=.8;
if(f.kind==="whirlwind"){drawWhirlwind(r,f,t,g);return true;}
if(f.kind==="frost-crown"){if(f.max>.8)drawFrostCrown(r,f,t,g);else{c.save();c.globalAlpha=(1-u)**1.4;rfCracks(c,x,y,radius,u*2,.6,"ice",detail?8:5);rfFragments(c,x,y,radius*.85,u,"ice",detail?13:6);}if(f.max<=.8)c.restore();return true;}
if(f.kind==="frost-storm"){if(f.ultimate)drawFrostPulse(r,f,t);else{c.save();c.globalAlpha=(1-u)*.35;rfFragments(c,x,y,radius*.76,u,"ice",detail?7:3);c.restore();}return true;}
if(f.kind==="impact"&&["orbit","whirlwind"].includes(f.key)){drawMetalContact(r,f);return true;}
if(["slash","swordslash","blood-cut","rend"].includes(f.kind)){const blood=f.kind==="blood-cut"||f.kind==="rend";c.save();c.globalAlpha=1;rfRibbon(c,x,y,radius*.9,f.angle||0,u,blood?20:f.evolved?23:16,blood?"blood":"steel",f.echo);if(blood){rfRibbon(c,x,y,radius*.72,(f.angle||0)-.10,u,5,"steel",true);if(detail)rfFragments(c,x,y,radius*.83,u,"blood",6,f.angle||0);}c.restore();return true;}
if(f.kind==="arrow-hit"){const material=rfMaterial(f.key);c.save();c.translate(x,y);c.rotate(f.angle||0);c.globalAlpha=(1-u)**2;rfLine(c,[[-13-12*u,0],[3,0]],rfColors[material].edge,1.45);rfFragments(c,0,0,31,u,material,detail?6:3,0);if(material==="toxin"){c.fillStyle="#accf7c";for(let i=0;i<3;i++){c.beginPath();c.ellipse(-u*(9+i*6),Math.sin(i*2.4)*(4+u*14),2,1,0,0,RF_TAU);c.fill();}}c.restore();return true;}
if(["impact","cut-hit","bolt-hit","ice-shatter","burst"].includes(f.kind)){let material=f.key==="ultimate"?(g.hero?.id==="mage"?"ice":g.hero?.id==="ranger"?"storm":"steel"):f.kind==="bolt-hit"||f.kind==="ice-shatter"?"ice":f.kind==="cut-hit"?"steel":rfMaterial(f.key);if(f.kind==="burst"&&!f.key)return true;rfContact(r,{...f,x,y},u,material);return true;}
if(["arrow-release","bolt-release"].includes(f.kind)){const ice=f.kind==="bolt-release";c.save();c.translate(x,y);c.rotate(f.angle||0);c.globalAlpha=(1-u)**2;const p=rfColors[ice?"ice":"steel"];rfLine(c,[[-20-u*20,-3],[14,0]],p.edge,1.1);rfLine(c,[[-16-u*26,4],[8,0]],p.mid,1.6);if(ice)for(const side of [-1,1]){c.save();c.translate(7+u*12,side*(6+u*11));c.rotate(side*.6);drawFracturedCrystal(c,5,15,.1,side,age,false);c.restore();}c.restore();return true;}
if(f.kind==="line"){const dx=f.x2-f.x,dy=f.y2-f.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,points=[];for(let i=0;i<=Math.min(18,Math.max(5,Math.ceil(len/20)));i++){const q=i/Math.min(18,Math.max(5,Math.ceil(len/20))),off=i===0||q===1?0:(rfRand(i,f.x+Math.floor(age*26))*2-1)*13;points.push([f.x+dx*q+nx*off,f.y+dy*q+ny*off]);}rfLightning(c,points,(1-u)**1.25,detail);if(u<.22)rfContact(r,{x:f.x2,y:f.y2,angle:Math.atan2(dy,dx)},u/.22,"storm");return true;}
if((f.kind==="lightning-strike"||f.kind==="lightning")&&Art.paintedReady()){drawPainted(c,"lightning",x,y-99,102,208,0,(1-u)**1.5*.91);if(u<.16)drawPainted(c,"steel-impact",x,y,36,23,0,(1-u/.16)*.42);return true;}
if(f.kind==="lightning-strike"||f.kind==="lightning"){const points=[[x+12,y-235],[x-17,y-166],[x+15,y-125],[x-7,y-61],[x+9,y-28],[x,y]];rfLightning(c,points,(1-u)**1.5,detail);rfCracks(c,x,y,radius,u*3,(1-u)*.5,"storm",5);return true;}
if(["fire-burst","meteor-impact","flame-pillar","fireburst","meteor","flamepillar"].includes(f.kind)){const pillar=["flame-pillar","flamepillar"].includes(f.kind),meteor=["meteor-impact","meteor"].includes(f.kind),fade=(1-u)**1.25,rise=rfEase(u/.16);c.save();c.globalAlpha=fade;rfGround(c,x,y,radius,"fire",.7);rfCracks(c,x,y,radius,u*2,.65,"fire",detail?9:5);const n=detail?(pillar?3:6):3;for(let i=0;i<n;i++){const q=i*2.399,d=radius*Math.sqrt(rfRand(i,x))*(pillar?.43:.78),xx=x+Math.cos(q)*d,yy=y+Math.sin(q)*d,w=(pillar?14:12)+rfRand(i,y)*12,h=(pillar?radius*1.55:radius*.62)*(.55+rfRand(i,x)*.5)*rise*(1-u*.4);c.save();c.translate(xx,yy);c.rotate(pillar?Math.sin(t*9+i)*.09:Math.cos(q)*.58);rfFlame(c,0,0,w,h,t,i,pillar?.74:.63);c.restore();}if(meteor)rfFragments(c,x,y,radius*1.2,u,"stone",detail?13:6);else if(detail)rfFragments(c,x,y,radius,u,"fire",8);c.restore();return true;}
if(f.kind==="quake"){c.save();c.globalAlpha=(1-u)**1.2;rfGround(c,x,y,radius,"stone",.5);rfCracks(c,x,y,radius,u*2.8,1,"stone",detail?10:6);for(let i=0;i<(detail?10:5);i++){const q=i*2.399,d=radius*(.18+rfRand(i,x)*.65),xx=x+Math.cos(q)*d,yy=y+Math.sin(q)*d-Math.sin(u*Math.PI)*16,w=(8+rfRand(i,y)*13)*(1-u*.4);rfPoly(c,[[xx-w,yy],[xx-w*.7,yy-w*.7],[xx+w*.35,yy-w],[xx+w,yy-w*.2],[xx+w*.6,yy+4]],rfGradient(c,xx,yy-w,xx,yy+4,[[0,"#ad987e"],[.45,"#786b5a"],[1,"#393734"]]));rfLine(c,[[xx-w*.7,yy-w*.7],[xx+w*.35,yy-w],[xx+w,yy-w*.2]],"#c9b58f",1);}rfFragments(c,x,y,radius,u,"stone",detail?10:4);c.restore();return true;}
if(f.kind==="trap-burst"){c.save();c.globalAlpha=1-u;rfGround(c,x,y,radius,"toxin",.45);for(let i=0;i<(detail?10:6);i++){const q=i*2.399,spread=radius*(.4+rfRand(i,x)*.4)*rfEase(u/.35),xx=x+Math.cos(q)*spread,yy=y+Math.sin(q)*spread,lift=Math.sin(u*Math.PI)*(24+rfRand(i,y)*25);const pts=[[x+Math.cos(q)*12,y+Math.sin(q)*12],[xx*.45+x*.55,yy*.45+y*.55-lift],[xx,yy-lift*.6]];rfLine(c,pts,"#243927",5);rfLine(c,pts,"#a3b97e",1.4);rfPoly(c,[[xx,yy-lift*.6],[xx-4,yy-lift*.6-15],[xx+3,yy-lift*.6-4]],"#cfdfaa");}c.restore();return true;}
if(f.kind==="arrow-rain"||f.kind==="arrowrain"){c.save();c.globalAlpha=(1-u)**1.8;for(let i=0;i<(detail?10:5);i++){const q=i*2.399,d=radius*Math.sqrt(rfRand(i,x))*.84,xx=x+Math.cos(q)*d,yy=y+Math.sin(q)*d;c.save();c.translate(xx,yy);c.rotate(1.78);c.scale(.72,.72);rfArrow(c,27,"steel",false);c.restore();if(i<4)rfFragments(c,xx,yy,18,u,"steel",2);}c.restore();return true;}
if(["fire-residue","poison-residue","thorn-residue","blood-eruption","frostresidue"].includes(f.kind)){const material=f.kind==="fire-residue"?"fire":f.kind==="blood-eruption"?"blood":f.kind==="frostresidue"?"ice":"toxin";c.save();c.globalAlpha=(1-u)*.37;rfFragments(c,x,y,radius*.6,u,material,detail?5:2);if(material==="blood")rfRibbon(c,x,y,radius*.7,0,u,13,"blood",true);c.restore();return true;}
if(f.kind==="sun-cleave"){const fall=rfCap(age/.3)**2,hit=rfCap((age-.3)/.82);c.save();c.globalAlpha=1;if(age<.46){c.save();c.translate(x,y-250*(1-fall)-142);c.rotate(Math.PI/2);c.globalAlpha=age<.31?1:rfCap((.46-age)/.15);rfPoly(c,[[-112,-8],[-112,8],[144,28],[144,-28]],rfGradient(c,-112,0,144,0,[[0,"#d0a45400"],[.7,"#fff0a345"],[1,"#fff5c470"]]));drawForgedBlade(c,240,age,8,false,detail);c.restore();}if(age>=.3){rfGround(c,x,y,radius,"stone",.65*(1-hit));rfCracks(c,x,y,radius,hit*3,1-hit,"stone",detail?12:7);rfRibbon(c,x,y,radius*.82,f.angle||0,hit,30,"steel");rfRibbon(c,x,y,radius*.64,(f.angle||0)+Math.PI,hit,15,"steel",true);rfFragments(c,x,y,radius,hit,"stone",detail?18:8);}c.restore();return true;}
if(f.kind==="meteor-fan"){const wave=age<.18?-1:Math.min(2,Math.floor((age-.18)/.2)),q=wave<0?age/.18:rfCap((age-(.18+wave*.2))/.2),fade=wave<0?1:1-q;c.save();c.translate(x,y);c.rotate(f.angle||0);c.globalAlpha=age<.78?fade:rfCap((1.2-age)/.42)*.2;const bend=wave<0?rfEase(q):1-q*.55;for(const side of [-1,1]){c.strokeStyle="#bfd3b4";c.lineWidth=2.8;c.beginPath();c.moveTo(-9,0);c.bezierCurveTo(-16,-side*18,13,-side*35,25,-side*48*bend);c.stroke();rfLine(c,[[25,-side*48*bend],[4,0]],"#e8f5d0",.8);}if(wave>=0)for(let i=0;i<7;i++){const angle=(i-3)*.12,len=25+q*69;rfLine(c,[[Math.cos(angle)*18,Math.sin(angle)*18],[Math.cos(angle)*len,Math.sin(angle)*len]],i%2?"#c0dbb580":"#edf4d4b0",1.2);}c.restore();return true;}
return false;
}
export function drawMaterialProjectile(r,b){
if(!["arrow","multishot","piercing","poison","ricochet","hammer","glaive","slam","fireball","bolt","nova","cleave"].includes(b.key))return false;
const c=r.ctx,age=b.age||0,detail=!r.reduced&&r.quality>=.8;let angle=Math.atan2(b.vy,b.vx),material=rfMaterial(b.key);
c.save();c.translate(b.x,b.y-20);if(b.key==="hammer"||b.key==="glaive")angle=age*(b.key==="hammer"?9:13);c.rotate(angle);
if(["arrow","multishot","piercing","poison","ricochet"].includes(b.key)){if(b.ultimate)material="storm";rfArrow(c,b.ultimate?44:b.key==="piercing"?39:30,material,!!b.evolved||b.ultimate,age);if(b.key==="poison"&&detail){for(let i=0;i<3;i++){const xx=-11-age% .1*60-i*13;c.fillStyle="#adc27680";c.beginPath();c.ellipse(xx,Math.sin(age*17+i)*4,2,1.2,0,0,RF_TAU);c.fill();}}}
else if(b.key==="fireball"){const size=b.evolved?28:21;c.save();c.rotate(Math.PI/2);rfFlame(c,0,0,size*1.5,size*3.2,age,7,.8);c.restore();const points=[[size*.63,0],[size*.17,-size*.55],[-size*.48,-size*.47],[-size*.64,size*.07],[-size*.24,size*.55],[size*.48,size*.33]];rfPoly(c,points,rfGradient(c,-size,-size,size,size,[[0,"#7d3921"],[.5,"#e58b36"],[.8,"#fff2ba"],[1,"#ba491f"]]));rfLine(c,[[size*.63,0],[size*.17,-size*.55],[-size*.48,-size*.47]],"#fff0b6",1.6);rfLine(c,[[-size*.45,size*.1],[size*.13,-size*.1],[size*.34,size*.2]],"#ffeeb6",1.2);}
else if(b.key==="bolt"||b.key==="nova"){const length=b.key==="bolt"?(b.evolved?41:31):23,width=b.key==="bolt"?10:7;rfPoly(c,[[-length*2,0],[-8,-width*.65],[length*.2,0],[-8,width*.65]],rfGradient(c,-length*2,0,0,0,[[0,"#6cb4d400"],[.7,"#6cb4d470"],[1,"#dafbe9c0"]]));c.save();c.rotate(Math.PI/2);drawFracturedCrystal(c,width,length,.02,3,age,detail);c.restore();if(b.evolved)for(const side of [-1,1]){c.save();c.translate(-9,side*width*.8);c.rotate(Math.PI/2+side*.2);drawFracturedCrystal(c,width*.42,length*.57,0,side,age,false);c.restore();}}
else if(b.key==="cleave"){rfRibbon(c,-b.r*.8,0,b.r*1.7,0,.28,11,"steel");rfLine(c,[[-b.r*.4,-b.r],[-b.r*.1,0],[-b.r*.4,b.r]],"#c8d7d560",1);}
else if(b.key==="hammer"){const w=b.evolved?29:23;rfLine(c,[[0,-8],[0,37]],"#252d34",8);rfLine(c,[[-1,-7],[-1,34]],"#ae966b",2);for(let i=0;i<4;i++)rfLine(c,[[-4,14+i*4],[4,11+i*4]],"#6a624f",1.8);rfPoly(c,[[-w,-19],[-w+6,-27],[w-5,-27],[w,-17],[w-2,-4],[-w+2,-4]],rfGradient(c,-w,-26,w,-2,[[0,"#adbdba"],[.25,"#536c7b"],[.62,"#243845"],[1,"#bdd0c7"]]));rfPoly(c,[[-w,-19],[-w+6,-27],[w-5,-27],[w,-17],[-w,-17]],"#adbfbc");rfLine(c,[[-w+6,-27],[w-5,-27],[w,-17]],"#edf0d6",1.2);rfPoly(c,[[-7,-19],[0,-24],[8,-19],[0,-10]],"#cbad67");rfLine(c,[[-w+1,-5],[w-2,-5]],"#73909a",1);}
else if(b.key==="glaive"){for(const side of [-1,1]){c.save();c.scale(side,side);c.fillStyle=rfGradient(c,-30,-20,25,10,[[0,"#254557"],[.45,"#9bb6ba"],[.62,"#eff3db"],[1,"#537b8b"]]);c.beginPath();c.moveTo(-32,7);c.bezierCurveTo(-22,-17,2,-27,29,-12);c.bezierCurveTo(6,-15,-3,-2,-5,9);c.closePath();c.fill();c.strokeStyle="#e0f0df";c.lineWidth=1.1;c.beginPath();c.moveTo(-32,7);c.bezierCurveTo(-22,-17,2,-27,29,-12);c.stroke();rfLine(c,[[-20,3],[-1,-13],[17,-14]],"#5f8290",.8);c.restore();}rfPoly(c,[[7,0],[0,-7],[-7,0],[0,7]],"#d5b57a");}
else{rfPoly(c,[[14,0],[4,-8],[-9,-6],[-13,3],[-4,10]],rfGradient(c,-10,-8,9,9,[[0,"#bdaa87"],[.4,"#776b5c"],[1,"#353733"]]));rfLine(c,[[14,0],[4,-8],[-9,-6]],"#d5b989",1);}
c.restore();return true;
}
export function drawMaterialField(r,f,t,layer="all"){
const keys=["whirlwind","meteor","slam","fissure","pyre","lightning","frost","trap","volley","burn","poison","thorns","beam"];
if(!keys.includes(f.key))return false;if(f.key==="whirlwind"||f.done)return true;
const c=r.ctx,detail=!r.reduced&&r.quality>=.8,back=layer!=="front",front=layer!=="back",material=rfMaterial(f.key),age=f.age||0,radius=f.r||55,fade=Math.min(1,f.ttl/.3),delay=Math.max(0,f.delay||0),charge=rfCap(age/Math.max(.001,age+delay));
c.save();c.globalAlpha=fade*(r.focusKey&&r.focusKey!==f.key?.48:1);
if(f.key==="beam"){c.translate(f.x,f.y-20);c.rotate(f.angle);const width=f.r,length=f.length,start=20,pulse=.94+Math.sin(t*27)*.035;if(back){rfLine(c,[[start,10],[length,10]],"#15112b55",width*1.8);}if(front){const grad=rfGradient(c,start,0,length,0,[[0,"#6f599a00"],[.03,"#927bcb80"],[.85,"#b797dcaa"],[1,"#9d81ce30"]]);rfPoly(c,[[start,-3],[length,-width*pulse],[length,width*pulse],[start,3]],grad);rfLine(c,[[start,0],[length,0]],"#aa94d5",width*.40);rfLine(c,[[start,0],[length,0]],"#ebe1ff",1.7);if(detail)for(const side of [-1,1]){const pts=[];for(let i=0;i<=12;i++){const q=i/12;pts.push([start+(length-start)*q,side*(3+q*width*.71)+Math.sin(i*1.4+t*12)*width*.12]);}rfLine(c,pts,"#d2bcf48a",.85);}const endPulse=rfCap(1-(age% .15)/.15);for(let i=0;i<(detail?6:3);i++){const q=i*2.399,d=(5+endPulse*12);rfLine(c,[[length+Math.cos(q)*d*.3,Math.sin(q)*d*.3],[length+Math.cos(q)*d,Math.sin(q)*d]],"#cab5eca0",.9);}}c.restore();return true;}
if(back){if(f.key==="trap")rfGround(c,f.x,f.y,f.trigger||radius,"toxin",.25);else rfGround(c,f.x,f.y,radius,material,delay>0?.2+charge*.23:f.key==="frost"?.4:.3);if(["meteor","slam","fissure","pyre","lightning"].includes(f.key)&&delay>0){rfCracks(c,f.x,f.y,radius,charge,.35+charge*.35,material,detail?7:4);c.save();c.translate(f.x,f.y);c.strokeStyle=rfColors[material].mid;c.lineWidth=1.25;for(let i=0;i<8;i++){const q=i*RF_TAU/8;c.beginPath();c.arc(0,0,radius*.9,q-.065,q+.065);c.stroke();}c.restore();}if(f.key==="frost")rfCracks(c,f.x,f.y,radius,rfCap(age/.6),.48,"ice",detail?8:5);if(["burn","poison","thorns"].includes(f.key))rfCracks(c,f.x,f.y,radius,.7,.3,material,5);}
if(f.key==="meteor"&&delay>0&&front){const height=280*(1-charge*charge);c.save();c.translate(f.x+height*.19,f.y-height-18);c.rotate(-.24);rfFlame(c,0,-5,41,103,t,4,.85);const w=26;rfPoly(c,[[-w,-8],[-w*.75,-26],[8,-31],[w,-9],[w*.7,18],[-8,25]],rfGradient(c,-w,-24,w,19,[[0,"#edac5e"],[.24,"#915a33"],[.68,"#402c28"],[1,"#a45d34"]]));rfLine(c,[[-w,-8],[-w*.75,-26],[8,-31],[w,-9]],"#ffb866",2);rfLine(c,[[0,-25],[-8,-4],[3,7],[1,20]],"#ffce7b",1.5);c.restore();}
if(f.key==="frost"&&delay<=0){const n=detail?9:5;for(let i=0;i<n;i++){const q=i*2.399,d=radius*(.25+rfRand(i,f.x)*.61),xx=f.x+Math.cos(q)*d,yy=f.y+Math.sin(q)*d,isBack=yy<f.y;if(layer==="back"&&!isBack||layer==="front"&&isBack)continue;c.save();c.translate(xx,yy);if(Art.paintedReady()){const h=(28+rfRand(i,f.x)*31)*rfEase((age-.2)/.2);if(h>.1)drawPainted(c,"crystal-cluster",0,-h*.35,h*.58,h,0,.72);}else drawFracturedCrystal(c,8+rfRand(i,f.y)*6,(24+rfRand(i,f.x)*28)*rfEase((age-.2)/.2),(rfRand(i,f.x)-.5)*.55,i,t,detail);c.restore();}}
if(f.key==="trap"&&front){const arm=rfCap(1-Math.max(0,f.arm||0)/.45),w=(f.trigger||46)*.61,h=13;c.save();c.translate(f.x,f.y);c.globalAlpha*=.55+arm*.45;const jawRise=8+arm*9;for(const side of [-1,1]){c.fillStyle=rfGradient(c,0,-jawRise,w,jawRise,[[0,"#d6d8b5"],[.5,"#657769"],[1,"#2c3e36"]]);c.beginPath();c.ellipse(0,side*3,w,h,0,side>0?0:Math.PI,side>0?Math.PI:RF_TAU);c.ellipse(0,side*3,w-4,h-4,0,side>0?Math.PI:RF_TAU,side>0?0:Math.PI,true);c.fill();for(let i=0;i<5;i++){const xx=(i-2)*w*.34;rfPoly(c,[[xx-3,side*10],[xx,side*(10+jawRise)],[xx+4,side*10]],"#c5d1a5");}}rfPoly(c,[[-9,-4],[8,-4],[10,4],[-8,4]],"#697e57");rfLine(c,[[-7,-3],[7,-3]],"#e2e2b7",.8);c.restore();}
if(f.key==="volley"&&front){const n=detail?11:6,fallProgress=delay>0?charge:rfCap(1-(f.tick||0)/.4),spread=radius*.86;for(let i=0;i<n;i++){const q=i*2.399,d=spread*Math.sqrt(rfRand(i,f.x)),xx=f.x+Math.cos(q)*d,yy=f.y+Math.sin(q)*d,flight=delay>0?rfCap((fallProgress-.15-rfRand(i,f.y)*.12)/.73):rfCap((fallProgress-rfRand(i,f.y)*.16)/.84),height=(1-flight)*170;c.save();c.globalAlpha*=delay>0?.45+.55*flight:.65;c.translate(xx+height*.17,yy-height-5);c.rotate(1.74);c.scale(.8,.8);rfArrow(c,30,f.evolved?"storm":"steel",f.evolved);c.restore();}}
if(["burn","poison","thorns"].includes(f.key)&&front){const n=detail?7:4;for(let i=0;i<n;i++){const q=i*2.399,d=radius*(.15+rfRand(i,f.x)*.67),xx=f.x+Math.cos(q)*d,yy=f.y+Math.sin(q)*d;if(f.key==="burn")rfFlame(c,xx,yy,12+rfRand(i,f.y)*12,22+rfRand(i,f.x)*37,t,i,.7);else if(f.key==="poison"){const cycle=(age*.8+rfRand(i,f.x))%1;c.globalAlpha=fade*(1-cycle)*.6;c.fillStyle="#91ae6b";c.beginPath();c.ellipse(xx,yy-cycle*17,2.5+cycle*1.5,2+cycle,0,0,RF_TAU);c.fill();c.globalAlpha=fade;}else{const rise=rfEase(age/.15),h=(16+rfRand(i,f.y)*18)*rise;c.save();c.translate(xx,yy);rfPoly(c,[[-4,0],[-7,-h*.4],[2,-h],[5,-h*.35],[4,3]],rfGradient(c,-5,0,5,-h,[[0,"#2d432e"],[.55,"#8da56c"],[1,"#cdd9a3"]]));rfLine(c,[[2,-h],[-1,-h*.2],[0,1]],"#d5e1aa",.8);c.restore();}}}
c.restore();return true;
}
