import {Art} from "./art.js";
import {drawPainted} from "./painted-vfx.js";
const SignatureVFX=(()=>{
const TAU=Math.PI*2,cap=v=>Math.max(0,Math.min(1,v)),ease=v=>1-(1-cap(v))**3;
const keys=new Set(["thousand","ballista","dragon"]),textures=new Map(),heads=new Map();
const rand=(n,s=0)=>{const v=Math.sin(n*127.1+s*31.7)*43758.5453;return v-Math.floor(v);};
const ready=()=>typeof Art.paintedReady==="function"&&Art.paintedReady();
const focus=(r,key)=>!r.focusKey||r.focusKey===key?1:.55;
const detail=r=>!r.reduced&&(r.quality??1)>=.8;
const chest=p=>({x:p.x,y:p.y-20});
function canvas(w,h){let out;if(typeof OffscreenCanvas==="function")out=new OffscreenCanvas(w,h);else if(typeof document!=="undefined"){out=document.createElement("canvas");out.width=w;out.height=h;}return out||null;}
function frame(key,w=768,h=192){if(textures.has(key))return textures.get(key);const out=canvas(w,h);if(!out)return null;const c=out.getContext("2d");if(!c)return null;drawPainted(c,key,w/2,h/2,w,h);textures.set(key,out);return out;}
function headFrame(blend){const step=Math.round(cap(blend)*12);if(heads.has(step))return heads.get(step);const out=canvas(160,112);if(!out)return null;const c=out.getContext("2d");if(!c)return null;drawPainted(c,"dragon-head-closed",80,56,158,110,0,1-step/12);c.globalCompositeOperation="lighter";drawPainted(c,"dragon-head-open",80,56,158,110,0,step/12);c.globalCompositeOperation="source-over";heads.set(step,out);return out;}
function gradient(c,x0,y0,x1,y1,stops){const g=c.createLinearGradient(x0,y0,x1,y1);for(const [q,color]of stops)g.addColorStop(q,color);return g;}
function curve(c,pts,color,width=1){if(pts.length<2)return;c.strokeStyle=color;c.lineWidth=width;c.lineJoin=c.lineCap="round";c.beginPath();c.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length-1;i++)c.quadraticCurveTo(pts[i].x,pts[i].y,(pts[i].x+pts[i+1].x)/2,(pts[i].y+pts[i+1].y)/2);c.lineTo(pts.at(-1).x,pts.at(-1).y);c.stroke();}
function wisps(c,x,y,r,u,angle,cold=false,count=5,seed=0){c.save();c.globalAlpha*=(1-u)**1.7;c.translate(x,y);c.rotate(angle);for(let i=0;i<count;i++){const v=rand(i,seed),side=i%2?1:-1,d=(10+v*r)*ease(u),yy=side*(3+v*11)*Math.sin(u*Math.PI),xx=d*(.35+v*.65),l=3+v*8;c.strokeStyle=cold?(i%2?"#6e9cae":"#d6e8e7"):(i%2?"#a58c6c":"#e3e1ce");c.lineWidth=i%3===0?1.1:.65;c.beginPath();c.moveTo(xx-l,yy);c.quadraticCurveTo(xx,yy-side*2,xx+l*.55,yy+side*1.5);c.stroke();}c.restore();}
function featherLight(c,x,y,len,angle,u,cold=false,alpha=1){c.save();c.translate(x,y);c.rotate(angle);c.globalAlpha*=alpha*(1-cap(u))**1.4;const reach=len*ease(u/.30),bend=reach*.075,w=Math.sin(Math.PI*cap(u))*4.8+1.4;c.fillStyle=gradient(c,0,-w,reach,w,[[0,cold?"#5b819200":"#80795500"],[.25,cold?"#91bec357":"#c3b88d50"],[.82,"#e8eee1be"],[1,"#f4f3da00"]]);c.beginPath();c.moveTo(0,0);c.bezierCurveTo(reach*.22,-w,reach*.74,bend-w,reach,bend);c.bezierCurveTo(reach*.72,bend+w,reach*.25,w*.45,0,0);c.fill();c.strokeStyle=cold?"#dcefee96":"#f2e7c38c";c.lineWidth=.75;c.beginPath();c.moveTo(reach*.14,-w*.3);c.bezierCurveTo(reach*.40,-w*.8,reach*.76,bend-w*.5,reach*.94,bend-w*.05);c.stroke();c.restore();}
function inLayer(layer,isFront){return layer==="all"||(isFront?layer==="front":layer==="back");}
function player(r,f){return r.currentGame?.player||{x:f.x,y:f.y};}
function farFront(r,p){const h=r.currentGame?.player;return !!h&&p.y>h.y+12&&Math.hypot(p.x-h.x,p.y-h.y)>46;}
function pathMesh(path,f,r){const nodes=[],parts=detail(r)?2:1,width=(f.r||24)*((f.paths?.length||1)>1?.72:.86);for(let i=0;i<path.length-1;i++)for(let j=0;j<parts;j++){const q=j/parts,a=path[i],b=path[i+1];nodes.push({x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q-20,q:(i+q)/(path.length-1)});}const end=path.at(-1);nodes.push({x:end.x,y:end.y-20,q:1});let total=0;for(let i=0;i<nodes.length;i++){const p=nodes[i],a=nodes[Math.max(0,i-1)],b=nodes[Math.min(nodes.length-1,i+1)],d=Math.hypot(b.x-a.x,b.y-a.y)||1;p.angle=Math.atan2(b.y-a.y,b.x-a.x);p.nx=-(b.y-a.y)/d;p.ny=(b.x-a.x)/d;p.w=width*(.12+.78*Math.sin(p.q*Math.PI*.5));if(i)total+=Math.hypot(p.x-nodes[i-1].x,p.y-nodes[i-1].y);p.distance=total;}return{nodes,total:Math.max(total,1),width};}
function dragonBody(c,mesh,f,r,index){const ns=mesh.nodes,texture=frame("dragon-body"),fade=cap((f.age||0)/.25)*cap((f.ttl??1)/.22);c.save();c.globalAlpha*=fade*(index===Math.floor((f.paths?.length||1)/2)?1:.76);
for(let i=1;i<ns.length;i++){const a=ns[i-1],b=ns[i],len=Math.hypot(b.x-a.x,b.y-a.y);if(len<.15||b.q<.055)continue;const angle=Math.atan2(b.y-a.y,b.x-a.x),w=Math.max(a.w,b.w)*1.10;c.save();c.translate((a.x+b.x)/2,(a.y+b.y)/2);c.rotate(angle);c.beginPath();c.moveTo(-len/2-1.1,-a.w*1.10);c.quadraticCurveTo(0,-(a.w+b.w)*.56,len/2+1.1,-b.w*1.10);c.lineTo(len/2+1.1,b.w);c.quadraticCurveTo(0,(a.w+b.w)*.51,-len/2-1.1,a.w);c.closePath();c.clip();if(texture){const sx=a.distance/mesh.total*texture.width,sw=Math.max(1,len/mesh.total*texture.width);c.drawImage(texture,sx,0,Math.min(sw+1,texture.width-sx),texture.height,-len/2-1.1,-w,len+2.2,w*2);}else drawPainted(c,"dragon-body",0,0,len+3,w*2);c.restore();}
const tail=ns[Math.min(ns.length-1,Math.max(1,Math.floor(ns.length*.09)))],start=ns[0],tailLen=Math.max(17,Math.min(42,mesh.total*.17));drawPainted(c,"dragon-tail",start.x+Math.cos(tail.angle)*tailLen*.45,start.y+Math.sin(tail.angle)*tailLen*.45,tailLen,mesh.width*.68,tail.angle+Math.PI,.86);
if(detail(r)){const pts=ns.filter((_,i)=>i%3===0||i===ns.length-1).map(p=>({x:p.x+p.nx*p.w*.44,y:p.y+p.ny*p.w*.44}));curve(c,pts,f.evolved?"#d8ba7978":"#d4e4d24b",f.evolved?1.05:.65);for(let k=4;k<ns.length-3;k+=7){const p=ns[k],bend=Math.sin((f.age||0)*9+k)*2;c.strokeStyle=f.evolved?"#c5af77a0":"#9bc3c48c";c.lineWidth=.65;c.beginPath();c.moveTo(p.x-p.nx*p.w*.6,p.y-p.ny*p.w*.6);c.bezierCurveTo(p.x-p.nx*p.w*1.1+Math.cos(p.angle)*5,p.y-p.ny*p.w*1.1+Math.sin(p.angle)*5,p.x-p.nx*p.w*1.4-Math.cos(p.angle)*7,p.y-p.ny*p.w*1.4-Math.sin(p.angle)*7,p.x-p.nx*p.w*1.2-Math.cos(p.angle)*(16+bend),p.y-p.ny*p.w*1.2-Math.sin(p.angle)*(16+bend));c.stroke();}}
c.restore();}
function dragonHead(c,mesh,f,r,index){const p=mesh.nodes.at(-1),age=f.age||0,fade=cap((age-.06)/.24)*cap((f.ttl??1)/.22),base=mesh.width,headW=Math.min(72,base*2.7),headH=headW*.70,breath=.20+.72*Math.max(0,Math.sin((age-.23)*TAU/.42-index*.55))**1.5,head=headFrame(breath),cx=p.x-Math.cos(p.angle)*headW*.29,cy=p.y-Math.sin(p.angle)*headW*.29;c.save();c.globalAlpha*=fade*(index===Math.floor((f.paths?.length||1)/2)?1:.8);c.translate(cx,cy);c.rotate(p.angle);if(head)c.drawImage(head,-headW/2,-headH/2,headW,headH);else{drawPainted(c,"dragon-head-closed",0,0,headW,headH,0,1-breath);drawPainted(c,"dragon-head-open",0,0,headW,headH,0,breath);}
if(f.evolved){for(const side of [-1,1]){c.strokeStyle=side===1?"#ba985a9e":"#dbca95a6";c.lineWidth=.95;c.beginPath();c.moveTo(-headW*.17,side*headH*.24);c.bezierCurveTo(-headW*.42,side*headH*.54,-headW*.53,side*headH*.18,-headW*.73,side*headH*.38);c.stroke();if(detail(r)){c.beginPath();c.moveTo(-headW*.46,side*headH*.34);c.quadraticCurveTo(-headW*.55,side*headH*.62,-headW*.63,side*headH*.54);c.stroke();}}}
c.restore();}
function sword(c,key,x,y,length,angle,alpha=1,evolved=false){const width=length*(key==="curved-sword"?.38:.45);drawPainted(c,key,x-Math.cos(angle)*length*.48,y-Math.sin(angle)*length*.48,width,length,angle+Math.PI/2,alpha);if(evolved){c.save();c.globalAlpha*=alpha*.45;c.translate(x,y);c.rotate(angle);c.strokeStyle="#e5d19ba0";c.lineWidth=.7;c.beginPath();c.moveTo(-length*.12,-1.2);c.quadraticCurveTo(-length*.5,-2.1,-length*.77,-1.1);c.stroke();c.restore();}}
function thousand(c,r,f,t,layer){const age=f.age||0,A=Math.min(1.22,f.area||1),lv=f.lv||1,p=player(r,f);
if(layer!=="front"&&age<.27){const u=cap(age/.27);c.save();c.globalAlpha*=Math.sin(Math.PI*u)*.55;for(const side of [-1,1]){c.strokeStyle=side>0?"#d8ca9c":"#8c9ba5";c.lineWidth=.75;c.beginPath();c.moveTo(f.x+side*22,f.y-17);c.bezierCurveTo(f.x+side*30,f.y-32,f.x+side*24,f.y-45,f.x+side*11,f.y-54);c.stroke();}c.restore();}
let n=0;for(const mark of f.marks||[]){const i=n++;if(mark.inactive)continue;const until=mark.at-age;if(until>.29||until<-.12)continue;const front=mark.y>p.y+12&&Math.hypot(mark.x-p.x,mark.y-p.y)>46;if(!inLayer(layer,front))continue;const hit=until<=0,fall=cap(1-until/.17)**3,after=cap(-until/.12),rise=hit?0:98*A*(1-fall),side=i%2?1:-1,angle=Math.PI/2+((mark.angle??f.angle??0)-(f.angle||0))*.18,major=lv>=5&&i%4===0,len=(major?67:lv>=3?58:51)*A*(f.evolved?1.07:1),x=mark.x+side*rise*.10,y=mark.y-16-rise,alpha=hit?(1-after)**1.5:ease((.29-until)/.09),key=lv>=3&&i%3===1?"curved-sword":"holy-sword";
if(!hit&&fall>.1&&detail(r))featherLight(c,x,y,len*.88,angle+Math.PI,cap(1-fall)*.45,false,alpha*.45);sword(c,key,x,y,len,angle,alpha,!!f.evolved);
if(hit&&after<.7){c.save();c.globalAlpha*=alpha*.34;drawPainted(c,"steel-impact",mark.x,mark.y-15,34+after*15,22,mark.angle||0,.48);c.restore();}}}
function bowArms(c,W,H,load,recoil,evolved){if(!evolved)return;const span=H*.56,flex=load*.11-recoil*.06;c.save();for(const side of [-1,1]){c.save();c.scale(1,side);c.strokeStyle=gradient(c,-W*.40,0,W*.04,span,[[0,"#493b2b"],[.45,"#b2965e"],[.78,"#65553b"],[1,"#ddc898"]]);c.lineWidth=3.2;c.beginPath();c.moveTo(-W*.24,5);c.bezierCurveTo(-W*.37,span*.37,-W*(.29+flex),span*.78,-W*.14,span);c.stroke();c.strokeStyle="#c7b37c96";c.lineWidth=.65;c.beginPath();c.moveTo(-W*.245,5);c.bezierCurveTo(-W*.38,span*.37,-W*(.29+flex),span*.78,-W*.145,span);c.stroke();c.restore();}c.restore();}
function ballista(c,r,f,t,layer){const age=f.age||0,a=f.angle||0,A=Math.min(1.18,f.area||1),W=86*A,H=48*A,shotAt=f.shotAt??f.lastShotAge??-1,since=shotAt>=0?age-shotAt:10,count=f.count||1,shots=f.shots||0,loaded=shots<count,recoil=since>=0&&since<.12?(1-since/.12)**2:0,load=loaded?(shots?cap((since-.07)/.18):cap(age/.39)):0,assembly=ease(age/.22),last=.45+(count-1)*.28,depart=shots>=count?cap(1-(age-last-.20)/.48):1,bodyX=f.x+Math.cos(a)*(26-W*.5),bodyY=f.y-20+Math.sin(a)*(26-W*.5),alpha=assembly*depart;
if(layer!=="front"){c.save();c.globalAlpha*=alpha;c.translate(bodyX,bodyY);c.rotate(a);c.translate(-recoil*7,0);bowArms(c,W,H,load,recoil,!!f.evolved);drawPainted(c,"ballista-body",0,0,W,H);const span=H*.32,anchor=-W*.19,pull=-W*.36-load*7;c.strokeStyle="#182323bb";c.lineWidth=1.5;c.beginPath();c.moveTo(anchor,-span);c.lineTo(pull+recoil*10,0);c.lineTo(anchor,span);c.stroke();c.strokeStyle="#c6bda58f";c.lineWidth=.55;c.beginPath();c.moveTo(anchor,-span);c.lineTo(pull+recoil*10,0);c.lineTo(anchor,span);c.stroke();
if(loaded&&since>.04){const L=55*A,tip=W*.5-(1-load)*11;drawPainted(c,"siege-arrow",tip-L*.5,0,L,9*A,0,.55+load*.45);}if(detail(r)&&load>.5){c.strokeStyle="#d5c39e70";c.lineWidth=.65;c.beginPath();c.moveTo(-W*.18,-2);c.bezierCurveTo(W*.02,-2.5,W*.13,-1.8,W*.30,-1.2);c.stroke();}c.restore();}
if(layer!=="back"&&since>=0&&since<.14){const u=since/.14;c.save();c.globalAlpha*=alpha*(1-u)**1.4;const x=f.x+Math.cos(a)*26,y=f.y-20+Math.sin(a)*26;featherLight(c,x,y,26,a,u,false,.80);wisps(c,x,y,21,u,a,false,detail(r)?3:2,f.seed||0);c.restore();}}
function drawSignatureField(r,f,t=0,layer="all"){if(!keys.has(f.key)||!ready())return false;const c=r.ctx,age=f.age||0;c.save();c.globalAlpha*=focus(r,f.key)*cap((f.ttl??1)/.20);if(f.key==="thousand")thousand(c,r,f,t,layer);else if(f.key==="ballista")ballista(c,r,f,t,layer);else{const paths=f.paths||[],dissolve=f.canFinish&&age>(f.finalAt??Infinity)?cap((age-f.finalAt)/.23):0;
for(let i=0;i<paths.length;i++){if(paths[i].length<2)continue;const mesh=pathMesh(paths[i],f,r),end=paths[i].at(-1);
if(layer!=="front"){c.save();const shadow=mesh.nodes.map(p=>({x:p.x,y:p.y+19}));c.globalAlpha*=.16*(1-dissolve);curve(c,shadow,"#071925",mesh.width*.65);c.restore();c.save();c.globalAlpha*=1-dissolve;dragonBody(c,mesh,f,r,i);c.restore();}
if(inLayer(layer,farFront(r,end))){c.save();c.globalAlpha*=1-dissolve*.90;dragonHead(c,mesh,f,r,i);c.restore();}
if(dissolve>0&&layer!=="back"){const pts=mesh.nodes;for(let j=3;j<pts.length;j+=detail(r)?7:12){const p=pts[j];wisps(c,p.x,p.y,18,dissolve,p.angle+Math.PI,true,2,j+(f.seed||0));}}}
if(!paths.length&&layer!=="front"&&age<.3)drawPainted(c,"frost-mist",f.x,f.y-24,55,23,f.angle||0,Math.sin(Math.PI*cap(age/.3))*.35);}c.restore();return true;}
function drawSignatureProjectile(r,b){if(b.key!=="ballista"||!ready())return false;const c=r.ctx,a=Math.atan2(b.vy||0,b.vx||0),L=b.final?73:b.evolved?65:59,x=b.x,y=b.y-20;c.save();c.globalAlpha*=focus(r,b.key);c.translate(x,y);c.rotate(a);const age=b.age||0;c.strokeStyle=gradient(c,-L*1.9,0,-5,0,[[0,"#96a89b00"],[.72,"#adb7a95c"],[1,"#ecedc1a0"]]);c.lineWidth=b.final?2:1.1;c.beginPath();c.moveTo(-L*1.9,Math.sin(age*20)*1.6);c.bezierCurveTo(-L*1.3,-2,-L*.65,1,-4,0);c.stroke();drawPainted(c,"siege-arrow",-L*.5,0,L,b.final?13:10);if(b.final){c.strokeStyle="#f3dfaa88";c.lineWidth=.7;for(const side of [-1,1]){c.beginPath();c.moveTo(-L*1.45,side*3);c.bezierCurveTo(-L,side*5,-L*.38,side*2,-L*.13,side*1.8);c.stroke();}}c.restore();return true;}
function drawSignatureEffect(r,f){if(!keys.has(f.key)||!String(f.kind||"").startsWith("campaign-")||!ready())return false;const c=r.ctx,age=Math.max(0,(f.max||.48)-(f.ttl||0)),u=cap(age/(f.max||.48)),x=f.x,y=f.y-20,a=f.angle||0,key=f.key;c.save();c.globalAlpha*=focus(r,key);if(f.kind==="campaign-hit"){c.restore();return true;}
if(f.kind==="campaign-slash"&&key==="thousand"){const xx=f.tx??f.x+Math.cos(a)*55,yy=(f.ty??f.y+Math.sin(a)*55)-20;featherLight(c,xx-Math.cos(a)*18,yy-Math.sin(a)*18,58,a,u,false,.46);if(detail(r)&&u<.7)wisps(c,xx,yy,24,u,a,false,3,f.seed||0);}
else if(f.kind==="campaign-finish"){if(key==="thousand"){const reach=Math.min(f.length||f.r||380,460),wave=cap(age/.24),d=26+ease(wave)*Math.min(reach*.39,170),alpha=cap(age/.035)*(1-u)**1.45;c.save();c.globalAlpha*=alpha;featherLight(c,x+Math.cos(a)*19,y+Math.sin(a)*19,reach*.76,a,Math.min(.94,age/.36),false,1);drawPainted(c,"gold-crescent",x+Math.cos(a)*d,y+Math.sin(a)*d,115+wave*14,61,a+Math.PI/4,.86);if(f.evolved)drawPainted(c,"curved-sword",x+Math.cos(a)*(d-16),y+Math.sin(a)*(d-16),19,67,a+Math.PI/2,.34);c.restore();if(detail(r))wisps(c,x+Math.cos(a)*47,y+Math.sin(a)*47,59,u,a,false,6,f.seed||0);}
else if(key==="ballista"){if(age<.13){const k=age/.13;c.save();c.globalAlpha*=(1-k)**1.5;drawPainted(c,"steel-impact",x,y,27+k*12,20,a,.50);c.restore();}wisps(c,x,y,33,u,a,false,detail(r)?4:2,f.seed||0);}
else{const expand=ease(age/.14),fade=(1-u)**1.3;c.save();c.globalAlpha*=fade;drawPainted(c,"frost-mist",x-Math.cos(a)*14,y-Math.sin(a)*14,80+expand*38,35+expand*12,a,.64);if(age<.18)drawPainted(c,"frost-impact",x,y,43+expand*17,39,a,cap(age/.025)*(1-age/.18)*.65);c.restore();wisps(c,x,y,55,u,a+Math.PI,true,detail(r)?8:4,f.seed||0);}}c.restore();return true;}
return{drawSignatureField,drawSignatureProjectile,drawSignatureEffect};})();
export const drawSignatureField=SignatureVFX.drawSignatureField,drawSignatureProjectile=SignatureVFX.drawSignatureProjectile,drawSignatureEffect=SignatureVFX.drawSignatureEffect;
