import fs from "node:fs";import path from "node:path";import crypto from "node:crypto";import {execFileSync} from "node:child_process";
const dir=".evidence/rift-5.2-source",base="games/rift-survivors/public/audio",plan=JSON.parse(fs.readFileSync(dir+"/sound-map.json","utf8")),catalog=JSON.parse(fs.readFileSync(dir+"/audio-catalog.json","utf8")),reports=[];
const pcm=(file,filters)=>execFileSync("ffmpeg",["-v","error","-i",file,...(filters?["-af",filters]:[]),"-ac","1","-ar","44100","-f","f32le","pipe:1"],{maxBuffer:16*1024*1024});
function stats(buffer){let peak=0,sum=0,onset=-1;const count=buffer.length/4,threshold=10**(-42/20);for(let i=0;i<count;i++){const x=buffer.readFloatLE(i*4);if(!Number.isFinite(x))throw Error("Invalid PCM");peak=Math.max(peak,Math.abs(x));sum+=x*x;if(onset<0&&Math.abs(x)>threshold)onset=i;}return{peak,rms:Math.sqrt(sum/count),onset,seconds:count/44100};}
for(const row of [...plan.aliases,...plan.additions]){const source="/tmp/rift-audio-catalog/"+row.source;if(!fs.existsSync(source))throw Error("Missing source "+row.source);const raw=pcm(source),rawStats=stats(raw);if(rawStats.peak<.001||rawStats.onset<0)throw Error("Silent source "+row.key);
const start=Math.max(0,rawStats.onset/44100-.008),duration=Math.min(row.maxSeconds,(rawStats.seconds-start)/row.pitchRate),filters=["atrim=start="+start,"asetpts=PTS-STARTPTS","asetrate="+Math.round(44100*row.pitchRate),"aresample=44100","atrim=duration="+duration,"highpass=f="+row.highpassHz,"lowpass=f="+row.lowpassHz].join(",");
const filtered=pcm(source,filters),filteredStats=stats(filtered),gain=10**(row.targetPeakDbfs/20)/filteredStats.peak;if(!Number.isFinite(gain)||filteredStats.peak<.001)throw Error("Silent filtered "+row.key);
const fade=Math.min(.05,duration*.25),finish=filters+",volume="+gain+",afade=t=in:st=0:d=0.003,afade=t=out:st="+Math.max(0,duration-fade)+":d="+fade,out=base+"/"+row.key+".mp3";execFileSync("ffmpeg",["-y","-v","error","-i",source,"-af",finish,"-ac","1","-ar","44100","-c:a","libmp3lame","-b:a","128k",out]);const encoded=stats(pcm(out));if(encoded.peak>.99||encoded.rms<.001)throw Error("Clip or silent output "+row.key);reports.push({...row,trimStartSeconds:start,preservedSeconds:duration,sourcePeak:rawStats.peak,gain,encoded});
}
const files=fs.readdirSync(base).filter(n=>n.endsWith(".mp3")).sort().map(name=>{const bytes=fs.readFileSync(base+"/"+name);const probe=JSON.parse(execFileSync("ffprobe",["-v","error","-show_entries","format=duration","-of","json",base+"/"+name],{encoding:"utf8"}));return{name,bytes:bytes.length,sha256:crypto.createHash("sha256").update(bytes).digest("hex"),duration:Number(probe.format.duration)};});if(files.length!==plan.expectedSampleCount)throw Error("Sample count "+files.length);
const manifest=JSON.parse(fs.readFileSync(base+"/manifest.json","utf8"));manifest.version="5.2.0";manifest.files=files;manifest.totalBytes=files.reduce((a,f)=>a+f.bytes,0);manifest.sources=manifest.sources.filter(s=>!["jc-fantasy","creature"].includes(s.name));manifest.sources.push(...catalog.sources.map(s=>({name:s.key==="fantasy"?"jc-fantasy":s.key,author:s.author,license:s.license,page:s.page,archive:s.archive})));manifest.materialMix="Licensed designed fantasy recordings, real thunder, air/rock/ice recordings and CC0 creature vocals. Distinct windup, flight, contact and finish cues; source dynamics preserved with peak gain, gentle filters and short fades. Not all source material is physical Foley.";fs.writeFileSync(base+"/manifest.json",JSON.stringify(manifest,null,2)+"\n");
let credits=fs.readFileSync(base+"/CREDITS.txt","utf8");if(!credits.includes("Rift Keepers 5.2 licensed"))credits+="\nRift Keepers 5.2 licensed weapon and creature material:\nJC Sounds — Fantasy SFX Pack Vol 1 — CC BY 4.0\nhttps://opengameart.org/content/jc-sounds-fantasy-sfx-pack-vol-1\nhttps://creativecommons.org/licenses/by/4.0/\nrubberduck — 80 CC0 creature SFX — CC0 1.0\nhttps://opengameart.org/content/80-cc0-creature-sfx\nhttps://creativecommons.org/publicdomain/zero/1.0/\nModifications: onset trim with 8ms pre-roll, peak gain preserving internal dynamics, pitch for creature cues, gentle high/low-pass EQ, fades, mono 44.1kHz MP3 encoding and runtime layers. Source roles and edits are recorded in .evidence/rift-5.2-source/sound-map.json and sound-report.json.\n";fs.writeFileSync(base+"/CREDITS.txt",credits);
const index=JSON.parse(fs.readFileSync(base+"/source-index.json","utf8"));index.version="5.2.0";index.sources=index.sources.filter(s=>!["jc-fantasy","creature"].includes(s.name));index.sources.push(...catalog.sources.map(s=>({name:s.key==="fantasy"?"jc-fantasy":s.key,url:s.archive,page:s.page,author:s.author,license:s.license,files:catalog.clips.filter(c=>c.path.startsWith(s.key+"/"))})));fs.writeFileSync(base+"/source-index.json",JSON.stringify(index,null,2)+"\n");fs.writeFileSync(dir+"/sound-report.json",JSON.stringify({version:"5.2.0",method:"FFmpeg decoding/encoding, PCM onset/peak/RMS; not timbre or human listening approval",replaced:plan.aliases.length,added:plan.additions.length,files:files.length,reports},null,2)+"\n");console.log({replaced:plan.aliases.length,added:plan.additions.length,samples:files.length,totalBytes:manifest.totalBytes});
