import fs from "node:fs";import path from "node:path";import {execFileSync} from "node:child_process";import crypto from "node:crypto";import {createRequire} from "node:module";const sharp=createRequire(import.meta.url)("/tmp/rift-asset-tools/node_modules/sharp");
const dir=".evidence/rift-5.2-source",parts=fs.readdirSync(dir+"/parts").filter(n=>n.endsWith(".pngpart")).sort();
const png=Buffer.concat(parts.map(n=>fs.readFileSync(dir+"/parts/"+n)));if(png.subarray(0,8).toString("hex")!=="89504e470d0a1a0a")throw Error("Atlas header mismatch");
fs.mkdirSync("games/rift-survivors/public/art",{recursive:true});
await sharp(png).webp({quality:96,alphaQuality:100,effort:6}).toFile("games/rift-survivors/public/art/vfx-painted.webp");
const meta=await sharp(png).metadata();fs.writeFileSync(dir+"/atlas-manifest.json",JSON.stringify({version:"5.2.0",method:"Original imagegen painted component artwork; encoded as WebP for the game",width:meta.width,height:meta.height,pngSha256:crypto.createHash("sha256").update(png).digest("hex"),sourceParts:parts.length},null,2));
const sources=[{key:"fantasy",author:"JC Sounds",license:"CC-BY-4.0",page:"https://opengameart.org/content/jc-sounds-fantasy-sfx-pack-vol-1",archive:"https://opengameart.org/sites/default/files/fantasy_sfx_pack_vol_1.7z"},{key:"creature",author:"rubberduck",license:"CC0-1.0",page:"https://opengameart.org/content/80-cc0-creature-sfx",archive:"https://opengameart.org/sites/default/files/80-CC0-creature-SFX_0.zip"}];
const media=[];function walk(root){for(const item of fs.readdirSync(root,{withFileTypes:true})){const f=path.join(root,item.name);if(item.isDirectory())walk(f);else if(/\.(wav|ogg|mp3|flac)$/i.test(item.name))media.push(f);}}
for(const source of sources){const root="/tmp/rift-audio-catalog/"+source.key;walk(root);const html=fs.readFileSync("/tmp/rift-audio-catalog/"+source.key+"-license.html","utf8");const token=source.key==="fantasy"?"creativecommons.org/licenses/by/4.0":"creativecommons.org/publicdomain/zero";if(!html.includes(token))throw Error("License page did not confirm "+source.license);}
const clips=[];for(const f of media){const info=JSON.parse(execFileSync("ffprobe",["-v","error","-show_entries","format=duration:stream=sample_rate,channels","-of","json",f],{encoding:"utf8"}));clips.push({path:path.relative("/tmp/rift-audio-catalog",f),bytes:fs.statSync(f).size,seconds:Number(info.format.duration),sampleRate:Number(info.streams[0].sample_rate),channels:info.streams[0].channels});}
fs.writeFileSync(dir+"/audio-catalog.json",JSON.stringify({version:"5.2.0",method:"Archive inventory and FFprobe output; no human listening assessment",sources,clips},null,2));
console.log(JSON.stringify({atlas:{width:meta.width,height:meta.height,bytes:fs.statSync("games/rift-survivors/public/art/vfx-painted.webp").size},clips:clips.length}));
