import {STAGE_SKILLS,CAMPAIGN_ENEMIES} from "./campaign.js";
const ccClamp=(n,a,b)=>Math.max(a,Math.min(b,n)),ccD2=(a,b)=>(a.x-b.x)**2+(a.y-b.y)**2;
function ccShot(g,b){if(g.bullets.length>=180)return false;g.bullets.push({r:6,ttl:1.5,pierce:3,hit:[],age:0,...b});return true;}
function ccEnemyShot(g,e,a,speed=190,extra={}){if(g.shots.length<160)g.shots.push({x:e.x,y:e.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:6,ttl:4,damage:8+g.stage*1.8,...extra});}
function ccLineContains(e,f,a,length,width){const dx=e.x-f.x,dy=e.y-f.y,along=dx*Math.cos(a)+dy*Math.sin(a),across=Math.abs(-dx*Math.sin(a)+dy*Math.cos(a));return along>=-e.r&&along<=length+e.r&&across<width+e.r;}
function ccHitLine(g,f,a,length,width,damage,extra={}){let hits=0;g.damageKey=f.damageKey||f.visualKey||f.key;for(const e of g.enemies){if(e.hp<=0||!ccLineContains(e,f,a,length,width))continue;e.stagger=Math.max(e.stagger||0,extra.stagger??.12);if(extra.slow)e.slow=Math.max(e.slow||0,extra.slow);if(g.hit(e,damage,{...f,angle:a,contactPhase:extra.phase||f.contactPhase}))hits++;if(g.phase!=="playing")break;}return hits;}
function ccSegmentD2(e,a,b){const dx=b.x-a.x,dy=b.y-a.y,u=ccClamp(((e.x-a.x)*dx+(e.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return(e.x-a.x-u*dx)**2+(e.y-a.y-u*dy)**2;}
function ccPathContains(e,path,width){for(let n=1;n<path.length;n++)if(ccSegmentD2(e,path[n-1],path[n])<(width+e.r)**2)return true;return false;}
function ccEmitImpact(g,f,hits,extra={}){if(!hits&&!extra.ground)return;g.emit("skill-impact",{key:f.visualKey||f.key,hits,angle:f.angle,strong:f.damage>=65,evolved:!!f.evolved,strength:extra.phase==="finish"?1.35:.65,level:f.lv,id:f.seed, ...extra});}
function ccFinish(g,f,x,y,r,hits,angle=f.angle){g.effect({kind:"campaign-finish",key:f.visualKey||f.key,x,y,r,angle,level:f.lv,evolved:!!f.evolved,seed:f.seed,ttl:.48,max:.48});if(hits)g.emit("skill-finish",{key:f.visualKey||f.key,hits,angle,strong:true,evolved:!!f.evolved,strength:1.35,phase:"finish",id:f.seed});}
export function launchCampaignSkill(g,t){if(!STAGE_SKILLS[t.key])return false;const p=g.player,s=t.stats,target=g.enemies.find(e=>e.id===t.targetId&&e.hp>0)||g.nearest(),angle=target?Math.atan2(target.y-p.y,target.x-p.x):t.angle;
const f={key:t.key,x:p.x,y:p.y,tx:target?.x??t.x,ty:target?.y??t.y,angle,lv:t.lv,evolved:t.evolved,damage:s.damage,r:80*s.area,area:s.area,ttl:2.4,age:0,tick:0,shots:0,keepMultiple:false,seed:++g.counter};
if(t.key==="crosscut")Object.assign(f,{ttl:1.02,length:240*s.area,r:22*s.area,count:t.evolved?5:t.lv>=5?4:t.lv>=3?3:2});
if(t.key==="explosive"){if(ccShot(g,{key:t.key,x:p.x,y:p.y,vx:Math.cos(angle)*560,vy:Math.sin(angle)*560,damage:s.damage,explosion:62*s.area,pierce:0,cluster:t.evolved?6:t.lv>=5?4:t.lv>=3?2:0,lv:t.lv,evolved:t.evolved,seed:f.seed}))g.emit("skill-release",{key:t.key,angle,level:t.lv,evolved:t.evolved,id:f.seed});return true;}
if(t.key==="spirit")Object.assign(f,{ttl:1.7,count:t.evolved?9:t.lv>=5?7:t.lv>=3?5:3});
if(t.key==="phantom")Object.assign(f,{ttl:1.6,count:t.evolved?8:t.lv>=5?6:t.lv>=3?4:2});
if(t.key==="falcon")Object.assign(f,{ttl:t.evolved?2.55:2.25,count:t.evolved?4:t.lv>=5?3:t.lv>=3?2:1,birds:[]});
if(t.key==="blackflame")Object.assign(f,{ttl:t.evolved?3.5:2.7,length:(t.lv>=3?390:300)*s.area,r:24*s.area});
if(t.key==="judgment")Object.assign(f,{ttl:2.05,count:t.evolved?7:t.lv>=5?5:t.lv>=3?3:1,r:72*s.area,marks:[]});
if(t.key==="stormbow"){if(ccShot(g,{key:t.key,x:p.x,y:p.y,vx:Math.cos(angle)*620,vy:Math.sin(angle)*620,damage:s.damage,chain:t.evolved?9:t.lv>=5?7:t.lv>=3?4:2,stormStrike:t.lv>=5,pierce:0,lv:t.lv,evolved:t.evolved,seed:f.seed}))g.emit("skill-release",{key:t.key,angle,level:t.lv,evolved:t.evolved,id:f.seed});return true;}
if(t.key==="gravity")Object.assign(f,{x:f.tx,y:f.ty,ttl:2.8,r:(t.evolved?155:125)*s.area,count:t.evolved?4:t.lv>=5?3:t.lv>=3?2:1});
if(t.key==="thousand"){const count=t.evolved?16:t.lv>=5?12:t.lv>=3?8:5,targets=g.enemies.filter(e=>e.hp>0&&ccD2(e,p)<500**2).sort((a,b)=>ccD2(a,p)-ccD2(b,p));Object.assign(f,{ttl:2.45,count,canFinish:t.lv>=5||t.evolved,finalAt:.40+count*.09+.16,finishAngle:angle,marks:Array.from({length:count},(_,i)=>{const e=targets[i%Math.max(1,targets.length)];return{x:e?.x??f.tx,y:e?.y??f.ty,targetId:e?.id,inactive:!e,at:.40+i*.09,angle:angle+(i%2?-.72:.72),hit:false,contacts:0};})});}
if(t.key==="ballista")Object.assign(f,{ttl:2.05,count:t.evolved?4:t.lv>=5?3:t.lv>=3?2:1,recoil:0,lastShotAge:-1,shotAt:-1});
if(t.key==="dragon"){const duration=t.evolved?2.6:t.lv>=3?2.15:1.7;Object.assign(f,{ttl:duration,duration,finalAt:duration-.24,canFinish:t.lv>=5||t.evolved,length:Math.min((t.lv>=3?390:330)*s.area,Math.max(110,Math.hypot(f.tx-f.x,f.ty-f.y)+20)),r:24*s.area,paths:[]});}
g.addField(f);g.emit("skill-release",{key:t.key,angle,level:t.lv,evolved:t.evolved,id:f.seed});return true;}
export function advanceCampaignField(g,f,dt){if(!STAGE_SKILLS[f.key])return false;const p=g.player,lv=f.lv,A=f.area,burst=(x,y,r,d,extra={})=>{const key=f.visualKey||f.key,hits=g.areaHit({key,x,y,r,angle:f.angle,evolved:f.evolved,lv,seed:f.seed,contactPhase:extra.phase},d,extra);if(hits)g.effect({kind:"campaign-hit",key,x,y,r,angle:f.angle,level:lv,evolved:f.evolved,seed:f.seed,ttl:.32,max:.32});ccEmitImpact(g,f,hits,extra);return hits;};
const release=b=>ccShot(g,{key:f.key,damage:f.damage,evolved:f.evolved,lv,seed:f.seed,...b});
if(f.key==="crosscut"){const due=Math.min(f.count,Math.max(0,Math.floor((f.age-.16)/.16)+1));while(f.shots<due){const i=f.shots++,a=f.angle+(i===0?-.24:i===1?.24:i===2?0:i===3?Math.PI:Math.PI*.5),hits=ccHitLine(g,f,a,f.length,f.r,f.damage*(i>1?.6:1));g.effect({kind:"campaign-slash",key:f.key,x:f.x,y:f.y,angle:a,r:f.length,level:lv,evolved:f.evolved,seed:f.seed,ttl:.32,max:.32});g.emit("skill-pulse",{key:f.key,angle:a,hits:0,id:f.seed});ccEmitImpact(g,f,hits);if(g.phase!=="playing")break;}}
else if(f.key==="spirit"){const due=Math.min(f.count,Math.max(0,Math.floor((f.age-.24)/.14)+1));while(f.shots<due){const i=f.shots++,side=(i-(f.count-1)/2)*17,aim=g.nearest(),a=aim?Math.atan2(aim.y-p.y,aim.x-p.x):f.angle;if(release({x:p.x-Math.sin(a)*side,y:p.y+Math.cos(a)*side,vx:Math.cos(a)*520,vy:Math.sin(a)*520,r:7,pierce:lv>=5?7:3,freeze:lv>=5?.4:0}))g.emit("skill-pulse",{key:f.key,angle:a,id:f.seed,hits:0});}}
else if(f.key==="phantom"){const due=Math.min(f.count,Math.max(0,Math.floor((f.age-.22)/.14)+1));while(f.shots<due){f.shots++;const targets=g.enemies.filter(e=>e.hp>0&&ccD2(e,p)<450**2).sort((a,b)=>ccD2(a,p)-ccD2(b,p)),e=targets[(f.shots-1)%Math.max(1,targets.length)];if(!e)continue;f.tx=e.x;f.ty=e.y;const a=f.shots%2?-.6:.6;g.effect({kind:"ghost",x:e.x-22,y:e.y,face:f.shots%2?1:-1,ttl:.22,max:.22,color:"#ffe4b0"});burst(e.x,e.y,48*A,f.damage,{stagger:.18});g.effect({kind:"campaign-slash",key:f.key,x:e.x-35,y:e.y,angle:a,r:105*A,level:lv,evolved:f.evolved,seed:f.seed,ttl:.28,max:.28});g.emit("skill-pulse",{key:f.key,angle:a,id:f.seed,hits:0});if(g.phase!=="playing")break;}if(lv>=5&&f.shots===f.count&&!f.final){f.final=true;const hits=burst(f.tx,f.ty,110*A,f.damage*.7,{phase:"finish"});ccFinish(g,f,f.tx,f.ty,110*A,hits);}}
else if(f.key==="falcon"){if(!f.birds.length)for(let i=0;i<f.count;i++)f.birds.push({x:f.x,y:f.y,age:-i*.15,hit:[],returning:false});for(const b of f.birds){b.age+=dt;if(b.age<0)continue;const target=b.age>.8?p:g.nearest();if(!target)continue;if(b.age>.8&&!b.returning){b.returning=true;if(lv>=5)b.hit=[];}const dx=target.x-b.x,dy=target.y-b.y,d=Math.hypot(dx,dy)||1,speed=b.returning?490:420,ox=b.x,oy=b.y;b.x+=dx/d*Math.min(d,speed*dt);b.y+=dy/d*Math.min(d,speed*dt);b.angle=Math.atan2(dy,dx);let hits=0;for(const e of g.enemies)if(e.hp>0&&!b.hit.includes(e.id)&&ccSegmentD2(e,{x:ox,y:oy},b)<(e.r+27*A)**2){b.hit.push(e.id);g.damageKey=f.key;if(g.hit(e,f.damage,{x:ox,y:oy,angle:b.angle,lv,evolved:f.evolved,seed:f.seed}))hits++;if(g.phase!=="playing")break;}ccEmitImpact(g,f,hits);if(g.phase!=="playing")break;}}
else if(f.key==="blackflame"){f.tick-=dt;if(f.tick<=0&&f.age>.25){f.tick+=.28;let hits=0;for(const a of lv>=5?[f.angle-.24,f.angle,f.angle+.24]:[f.angle]){hits+=ccHitLine(g,f,a,f.length,f.r,f.damage,{slow:lv>=3?.3:0,stagger:0,phase:"sustain"});if(g.phase!=="playing")break;}g.emit("skill-pulse",{key:f.key,angle:f.angle,hits:0,phase:"sustain",id:f.seed});}}
else if(f.key==="judgment"){if(!f.marks.length)for(let i=0;i<f.count;i++){const e=g.enemies.filter(e=>e.hp>0&&ccD2(e,p)<520**2)[i];f.marks.push({x:e?.x??f.tx+Math.cos(i*2.4)*i*35,y:e?.y??f.ty+Math.sin(i*2.4)*i*35,at:.5+i*.19,hit:false});}for(const m of f.marks)if(!m.hit&&f.age>=m.at){m.hit=true;let hits=burst(m.x,m.y,f.r,f.damage,{stagger:.5,ground:true});if(lv>=5&&g.phase==="playing")hits+=burst(m.x,m.y,f.r*1.45,f.damage*.25,{stagger:.18,ground:true});m.contacts=hits;if(g.phase!=="playing")break;}}
else if(f.key==="gravity"){f.tick-=dt;if(f.age<1.5){for(const e of g.enemies){const d=Math.sqrt(ccD2(e,f));if(!e.boss&&e.hp>0&&d<f.r&&d>45&&ccD2(e,p)>(e.r+p.r+60)**2){e.x+=(f.x-e.x)/d*75*dt;e.y+=(f.y-e.y)/d*75*dt;}}if(f.tick<=0){f.tick+=.35;g.areaHit({...f,contactPhase:"sustain"},f.damage,{slow:.4});g.emit("skill-pulse",{key:f.key,phase:"sustain",hits:0,id:f.seed});}}else{const due=Math.min(f.count,Math.floor((f.age-1.5)/.28)+1);while(f.shots<due){f.shots++;burst(f.x,f.y,f.r,f.damage*2.2,{root:lv>=5?.5:0,phase:f.shots===f.count?"finish":"contact",ground:true});if(g.phase!=="playing")break;}}}
else if(f.key==="thousand"){for(const m of f.marks){if(m.hit)continue;if(f.age<m.at-.1){const e=g.enemies.find(e=>e.id===m.targetId&&e.hp>0);if(e){m.x=e.x;m.y=e.y;}}if(f.age<m.at)continue;m.hit=true;f.shots++;if(m.inactive)continue;m.contacts=burst(m.x,m.y,38*A,f.damage,{stagger:.12});g.effect({kind:"campaign-slash",key:f.key,x:m.x-55*Math.cos(m.angle),y:m.y-55*Math.sin(m.angle),tx:m.x,ty:m.y,angle:m.angle,r:140*A,level:lv,evolved:f.evolved,seed:f.seed,ttl:.24,max:.24});g.emit("skill-pulse",{key:f.key,angle:m.angle,phase:"cut",hits:0,id:f.seed});if(g.phase!=="playing")break;}if(f.canFinish&&f.age>=f.finalAt&&!f.final&&g.phase==="playing"){f.final=true;const e=g.nearest(500*A);f.finishAngle=e?Math.atan2(e.y-p.y,e.x-p.x):f.angle;const hits=ccHitLine(g,{...f,x:p.x,y:p.y},f.finishAngle,480*A,65*A,f.damage*1.2,{stagger:.35,phase:"finish"});ccFinish(g,f,p.x,p.y,480*A,hits,f.finishAngle);g.emit("skill-pulse",{key:f.key,angle:f.finishAngle,phase:"finish",hits:0,id:f.seed});}}
else if(f.key==="ballista"){f.recoil=Math.max(0,(f.recoil||0)-dt);const due=Math.min(f.count,Math.max(0,Math.floor((f.age-.45)/.28)+1));while(f.shots<due){f.shots++;const target=g.nearest(),a=target?Math.atan2(target.y-f.y,target.x-f.x):f.angle;f.angle=a;if(release({x:f.x+Math.cos(a)*26,y:f.y+Math.sin(a)*26,vx:Math.cos(a)*780,vy:Math.sin(a)*780,r:lv>=5?20:14,pierce:f.evolved?20:16,ttl:1.05,shatter:lv>=5?40*A:0,final:f.evolved&&f.shots===f.count})){f.lastShotAge=f.shotAt=f.age;f.recoil=.12;g.emit("skill-pulse",{key:f.key,angle:a,phase:"release",hits:0,id:f.seed,strong:true,evolved:f.evolved});}}}
else if(f.key==="dragon"){f.paths=[];const count=lv>=5?3:1;for(let i=0;i<count;i++){const a=f.angle+(i-(count-1)/2)*.25,path=[];for(let n=0;n<=16;n++){const travel=ccClamp((f.age-.1)/.75,.05,1),d=n*f.length*travel/16,side=Math.sin(n*.275-f.age*5)*22*A*Math.sin(Math.min(1,n/4)*Math.PI/2);path.push({x:f.x+Math.cos(a)*d-Math.sin(a)*side,y:f.y+Math.sin(a)*d+Math.cos(a)*side});}f.paths.push(path);}f.tick-=dt;if(f.age>.28&&f.tick<=0){f.tick+=f.evolved?.16:.2;g.damageKey=f.key;for(const e of g.enemies)if(e.hp>0&&f.paths.some(path=>ccPathContains(e,path,f.r))){e.slow=Math.max(e.slow||0,.3);g.hit(e,f.damage,{...f,contactPhase:"sustain"});if(g.phase!=="playing")break;}g.emit("skill-pulse",{key:f.key,phase:"sustain",hits:0,id:f.seed});}if(f.canFinish&&f.age>=f.finalAt&&!f.final&&g.phase==="playing"){f.final=true;let hits=0;for(const path of f.paths){const q=path.at(-1);hits+=burst(q.x,q.y,80*A,f.damage*2,{root:.45,phase:"finish",ground:true});if(g.phase!=="playing")break;}const q=f.paths[Math.floor(f.paths.length/2)].at(-1);ccFinish(g,f,q.x,q.y,80*A,hits);}}
return true;}
export function campaignProjectileContact(g,b,e){
if(b.cluster){const count=b.cluster;b.cluster=0;for(let i=0;i<count;i++){const a=i*Math.PI*2/count,r=48;g.addField({key:"judgment",x:e.x,y:e.y,tx:e.x+Math.cos(a)*r,ty:e.y+Math.sin(a)*r,lv:1,damage:b.damage*.32,r:40,area:1,age:0,ttl:.95,count:1,marks:[{x:e.x+Math.cos(a)*r,y:e.y+Math.sin(a)*r,at:.28+i*.045,hit:false}],shots:0,angle:a,evolved:b.evolved,seed:b.seed,keepMultiple:true,visualKey:"explosive"});}}
if(b.chain){const used=new Set([e.id]);let old=e,hits=0;for(let i=0;i<b.chain;i++){const n=g.enemies.filter(x=>x.hp>0&&!used.has(x.id)&&ccD2(x,old)<210**2).sort((a,c)=>ccD2(a,old)-ccD2(c,old))[0];if(!n)break;used.add(n.id);g.effect({kind:"campaign-chain",key:b.key,x:old.x,y:old.y-18,x2:n.x,y2:n.y-18,ttl:.3,max:.3,level:b.lv,evolved:b.evolved,seed:b.seed});g.damageKey=b.key;n.stagger=Math.max(n.stagger||0,.17);if(g.hit(n,b.damage*.65,{...old,seed:b.seed}))hits++;if(b.stormStrike&&g.phase==="playing")g.addField({key:"judgment",visualKey:"stormbow",x:n.x,y:n.y,tx:n.x,ty:n.y,damage:b.damage*.38,r:42,area:1,lv:b.lv,evolved:b.evolved,angle:0,count:1,marks:[{x:n.x,y:n.y,at:.32,hit:false}],ttl:.8,age:0,shots:0,seed:b.seed,keepMultiple:true});old=n;if(g.phase!=="playing")break;}ccEmitImpact(g,{...b,angle:Math.atan2(b.vy,b.vx)},hits);if(b.stormStrike&&g.phase==="playing")g.addField({key:"judgment",visualKey:"stormbow",x:e.x,y:e.y,tx:e.x,ty:e.y,damage:b.damage*.38,r:42,area:1,lv:b.lv,evolved:b.evolved,angle:0,count:1,marks:[{x:e.x,y:e.y,at:.32,hit:false}],ttl:.8,age:0,shots:0,seed:b.seed,keepMultiple:true});}
if(b.key==="ballista"&&b.shatter){const a=Math.atan2(b.vy,b.vx),hits=g.areaHit({key:b.key,x:e.x,y:e.y,r:b.shatter,angle:a,lv:b.lv,evolved:b.evolved,seed:b.seed,contactPhase:b.final?"finish":"contact"},b.damage*.12,{stagger:b.final?.3:.12});ccFinish(g,{...b,angle:a},e.x,e.y,b.shatter,hits,a);}
}
export function advanceCampaignEnemy(g,e,dt){if(!CAMPAIGN_ENEMIES[e.kind])return false;const p=g.player,dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy)||1,a=Math.atan2(dy,dx),can=e.stagger<=0&&e.root<=0,speed=e.speed*(e.slow>0?.45:1)*(can?1:0);
const facing=e.faceAngle??a;e.faceAngle=e.kind==="guard"?facing+ccClamp(Math.atan2(Math.sin(a-facing),Math.cos(a-facing)),-1.2*dt,1.2*dt):a;const ranged=["healer","sniper","wisp","frostling"].includes(e.kind),desired=ranged?230:0;if(dist>desired){e.x+=dx/dist*speed*dt;e.y+=dy/dist*speed*dt;}else if(ranged&&dist<150){e.x-=dx/dist*speed*dt;e.y-=dy/dist*speed*dt;}
if(e.kind==="hound"){if(e.charge){e.charge.age+=dt;if(can&&e.charge.age>.65&&e.charge.age<.95){e.x+=Math.cos(e.charge.angle)*340*dt;e.y+=Math.sin(e.charge.angle)*340*dt;}if(e.charge.age>=.95)e.charge=null;}else if(can&&e.shoot<=0&&dist<360){e.shoot=4;e.charge={age:0,angle:a};}}
if(e.kind==="bomber"&&can&&dist<150&&!e.fuse)e.fuse=.9;if(e.fuse){e.fuse-=dt;if(e.fuse<=0){if(g.hazards.length<80)g.hazards.push({x:e.x,y:e.y,r:80,delay:0,life:.12,damage:15+g.stage*2});e.hp=0;g.effect({kind:"campaign-hit",key:"explosive",x:e.x,y:e.y,r:85,ttl:.5,max:.5});g.emit("enemy-burst");return true;}}
if(e.kind==="healer"&&can&&e.shoot<=0){e.shoot=4.5;for(const n of g.enemies)if(n!==e&&!n.boss&&n.hp>0&&ccD2(n,e)<180**2)n.hp=Math.min(n.maxHp,n.hp+n.maxHp*.12);e.healPulse=.45;g.effect({kind:"campaign-heal",key:"healer",x:e.x,y:e.y,r:180,ttl:.45,max:.45});}
if(e.kind==="sniper"&&can){if(e.aim){e.aim.age+=dt;if(e.aim.age>=1){ccEnemyShot(g,e,e.aim.angle,430,{r:4,damage:12+g.stage*2});e.aim=null;}}else if(e.shoot<=0){e.shoot=3.6;e.aim={age:0,angle:a};}}
if(e.kind==="wisp"&&can&&e.shoot<=0){e.shoot=3;ccEnemyShot(g,e,a,130,{homing:1.2});}
if(e.kind==="frostling"&&can&&e.shoot<=0){e.shoot=4.1;if(g.hazards.length<80)g.hazards.push({x:p.x,y:p.y,r:70,delay:1.2,life:.8,damage:11+g.stage*2,ice:true});}
if(can&&dist<e.r+p.r)g.hurt(9+g.stage*2.2);return true;}
export function advanceCampaignBoss(g,e,dt){if(g.stage===1||e.stagger>0)return;const p=g.player,phase2=e.hp<e.maxHp*.5;e.special=(e.special??5)-dt;if(e.special>0)return;e.special=phase2?5:7;const a=Math.atan2(p.y-e.y,p.x-e.x),hazard=(x,y,r,delay=1.1)=>{if(g.hazards.length<80)g.hazards.push({x:ccClamp(x,30,1770),y:ccClamp(y,30,1770),r,delay,life:.35,damage:14+g.stage*3,ice:g.stage===4});};
if(g.stage===2){for(let i=0;i<4;i++)hazard(e.x+Math.cos(a)*(70+i*80),e.y+Math.sin(a)*(70+i*80),42,1+i*.12);}
if(g.stage===3){const count=phase2?10:7;for(let i=0;i<count;i++)ccEnemyShot(g,e,a+i*Math.PI*2/count,115,{homing:.6});hazard(p.x,p.y,75,1.35);}
if(g.stage===4){for(let i=0;i<5;i++){const q=i*Math.PI*2/5;hazard(p.x+Math.cos(q)*115,p.y+Math.sin(q)*115,49,1.2+i*.09);}}
if(g.stage===5){for(let i=0;i<3;i++)hazard(p.x+(i-1)*95,p.y+(i-1)*55,52,1.2+i*.18);for(let i=0;i<5;i++)ccEnemyShot(g,e,a+(i-2)*.23,185);if(phase2&&g.enemies.length<170)for(const kind of ["healer","hound"])g.spawn(kind);}
g.emit("boss-special",{stage:g.stage});}
