import {STAGES,STAGE_SKILLS,CAMPAIGN_ENEMIES} from "./campaign.js";
import {Art,drawSprite,drawMaterial} from "./art.js";
const cvTAU=Math.PI*2;
function cvPoly(c,points,fill,stroke){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=1.2;c.stroke();}}
function cvSword(c,x,y,size,angle=0,alpha=1){c.save();c.translate(x,y);c.rotate(angle);c.globalAlpha*=alpha;const z=size/100;c.scale(z,z);cvPoly(c,[[0,-94],[-9,-58],[-7,0],[0,8],[7,0],[9,-58]],"#eaf6ff","#162b40");cvPoly(c,[[0,-94],[-9,-58],[-7,0],[0,8]],"#789bb5");cvPoly(c,[[0,-94],[3,-50],[3,1],[0,8]],"#fff8d8");cvPoly(c,[[-22,0],[-18,-8],[-5,-4],[5,-4],[18,-8],[22,0],[5,5],[-5,5]],"#cfab69","#46372d");c.fillStyle="#364c64";c.fillRect(-4,6,8,24);c.fillStyle="#ffe7a4";c.fillRect(-6,30,12,5);c.restore();}
function cvArrow(c,x,y,a,size=1,color="#d3ffe4"){c.save();c.translate(x,y);c.rotate(a);c.scale(size,size);c.strokeStyle="#071923";c.lineWidth=7;c.beginPath();c.moveTo(-25,0);c.lineTo(19,0);c.stroke();c.strokeStyle="#edddad";c.lineWidth=3;c.stroke();cvPoly(c,[[28,0],[12,-8],[16,0],[12,8]],color,"#143b3d");cvPoly(c,[[-26,0],[-35,-7],[-18,-6],[-13,0],[-18,6],[-35,7]],"#79be9d");c.restore();}
function cvStreak(c,points,color,width){c.lineJoin="round";c.lineCap="round";for(const [w,a]of [[width+9,.12],[width+3,.5],[width,1]]){c.globalAlpha*=a;c.strokeStyle=color;c.lineWidth=w;c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();c.globalAlpha/=a;}}
function cvConstruct(c,name,x,y,width,angle=0,alpha=1){const img=Art.images.get(name);if(!img)return false;const height=width*img.naturalHeight/img.naturalWidth;c.save();c.translate(x,y);c.rotate(angle);c.globalAlpha*=alpha;c.drawImage(img,-width/2,-height/2,width,height);c.restore();return true;}
export function drawCampaignProjectile(r,b){if(!STAGE_SKILLS[b.key])return false;const c=r.ctx,a=Math.atan2(b.vy,b.vx);c.save();c.translate(b.x,b.y-18);c.rotate(a);const color=STAGE_SKILLS[b.key].color;c.strokeStyle=color+"55";c.lineWidth=b.key==="ballista"?12:3;c.beginPath();c.moveTo(-90,0);c.lineTo(-12,0);c.stroke();if(b.key==="spirit"){cvSword(c,0,0,52,a-a+Math.PI/2);c.strokeStyle="#caf3ff";c.lineWidth=1;c.beginPath();c.moveTo(-65,-8);c.lineTo(8,-8);c.stroke();}else{cvArrow(c,0,0,0,b.key==="ballista"?1.8:1,color);if(b.key==="explosive"){c.fillStyle="#ffd289";c.beginPath();c.arc(-6,0,5,0,cvTAU);c.fill();}if(b.key==="stormbow"){cvStreak(c,[{x:-45,y:-4},{x:-25,y:8},{x:-8,y:-5},{x:13,y:2}],"#b8f0ff",2);}}c.restore();return true;}
export function drawCampaignField(r,f,t){if(!STAGE_SKILLS[f.key])return false;const c=r.ctx,key=f.visualKey||f.key,u=STAGE_SKILLS[key],color=u?.color||"#ffe0a0",fade=Math.min(1,f.ttl/.22),A=f.area;c.save();c.globalAlpha=fade;
if(f.key==="spirit"){const count=f.count-f.shots;for(let i=0;i<count;i++){const side=(i-(count-1)/2)*17;cvSword(c,r.currentGame?.player.x+side||f.x+side,(r.currentGame?.player.y||f.y)-38-12*Math.cos(i*.7+t),43,Math.PI/2+f.angle,.65);}}
if(f.key==="crosscut"&&f.age<.16){c.translate(f.x,f.y-18);c.rotate(f.angle);cvSword(c,10,0,70,1.1,.8);cvSword(c,10,0,70,2.05,.8);}
if(f.key==="falcon")for(const b of f.birds){if(b.age<0)continue;const a=Math.atan2((r.currentGame?.player.y||f.y)-b.y,(r.currentGame?.player.x||f.x)-b.x)+(b.returning?0:Math.PI);c.save();c.translate(b.x,b.y-22);c.rotate(a);c.scale(1,1+Math.sin(b.age*20)*.07);cvConstruct(c,"spell-falcon",0,0,78*A,0,.92);c.restore();}
if(f.key==="blackflame"){c.save();c.translate(f.x,f.y);c.rotate(f.angle);for(const side of f.lv>=5?[-.24,0,.24]:[0]){c.save();c.rotate(side);c.strokeStyle="#0c081fcc";c.lineWidth=f.r*2;c.beginPath();c.moveTo(30,0);c.lineTo(f.length,0);c.stroke();for(let i=0;i<Math.floor(f.length/28);i++){const x=30+i*28,h=25+Math.sin(t*16+i*1.7)*14;c.fillStyle=i%2?"#6b2480b0":"#a250bccc";c.beginPath();c.moveTo(x-16,12);c.quadraticCurveTo(x-18,-h*.5,x+Math.sin(i+t)*12,-h);c.quadraticCurveTo(x+14,-h*.3,x+13,12);c.fill();c.fillStyle="#e8c9ffb0";c.beginPath();c.moveTo(x-6,6);c.lineTo(x+3,-h*.6);c.lineTo(x+7,6);c.fill();}c.restore();}c.restore();}
if(f.key==="judgment")for(const m of f.marks){const until=m.at-f.age;if(until>0){c.strokeStyle=color+"b0";c.lineWidth=2;c.beginPath();c.ellipse(m.x,m.y,f.r*.65,f.r*.4,0,0,cvTAU);c.stroke();if(key==="explosive"){r.glow(m.x,m.y,55,"red",.6);continue;}const height=90+until*120;cvSword(c,m.x,m.y-height,115*A,Math.PI,Math.min(1,1-until+.35));c.strokeStyle="#ffd99477";c.beginPath();c.moveTo(m.x,m.y-18);c.lineTo(m.x,m.y-height+40);c.stroke();}else if(until>-.32){if(key!=="explosive")cvSword(c,m.x,m.y-52,120*A,Math.PI,1+until/0.32);}}
if(f.key==="gravity"){c.save();c.translate(f.x,f.y);const q=f.age<1.5?f.age/1.5:Math.max(.1,1-(f.age-1.5)/.9),rad=f.r*q;c.strokeStyle="#a668cbbc";c.lineWidth=1.6;for(let k=0;k<3;k++){c.beginPath();c.ellipse(0,0,rad,rad*.55,t*1.4+k,0,cvTAU);c.stroke();}for(let i=0;i<10;i++){const a=i*.628-t*2.3,d=rad*(.5+.35*Math.sin(i*3));cvPoly(c,[[Math.cos(a)*d,Math.sin(a)*d*.65],[Math.cos(a)*d+8,Math.sin(a)*d*.65-6],[Math.cos(a)*d+14,Math.sin(a)*d*.65+5]],"#766b97","#d1a5ec");}r.glow(0,0,75,"violet",.85);c.fillStyle="#10091f";c.beginPath();c.ellipse(0,0,17+q*8,14+q*5,0,0,cvTAU);c.fill();c.restore();}
if(f.key==="thousand"&&f.age<.24){for(let i=0;i<5;i++){const a=i*cvTAU/5+t*.4;cvSword(c,f.x+Math.cos(a)*58,f.y+Math.sin(a)*34-22,50,a+Math.PI/2,.8);}}
if(f.key==="ballista"){c.save();c.translate(f.x,f.y-18);c.rotate(f.angle);c.globalAlpha*=Math.min(1,f.age/.2);c.strokeStyle="#f0dfb8";c.lineWidth=5;c.beginPath();c.moveTo(-20,-58);c.quadraticCurveTo(32,-38,13,0);c.quadraticCurveTo(32,38,-20,58);c.stroke();c.strokeStyle="#91dcb6";c.lineWidth=2;c.stroke();c.strokeStyle="#defff088";c.lineWidth=1;c.beginPath();c.moveTo(-20,-58);c.lineTo(-35,0);c.lineTo(-20,58);c.stroke();cvArrow(c,5,0,0,1.7);for(const side of [-1,1])cvPoly(c,[[-20,side*45],[-38,side*54],[-29,side*28],[-3,side*35]],"#386d63","#efdaa0");c.restore();}
if(f.key==="dragon")for(const path of f.paths){if(!path.length)continue;c.save();c.globalAlpha*=Math.min(1,f.age/.3);const pts=path.map(q=>({x:q.x,y:q.y-18}));cvStreak(c,pts,"#557eaca0",f.r*.70);cvStreak(c,pts,"#bce9fc",2);for(let i=1;i<path.length-1;i++){const q=path[i],old=path[i-1],a=Math.atan2(q.y-old.y,q.x-old.x);c.save();c.translate(q.x,q.y-18);c.rotate(a);c.strokeStyle="#d6f3ff8a";c.lineWidth=1.2;c.beginPath();c.ellipse(0,0,13,7,.5,Math.PI,Math.PI*2);c.stroke();c.restore();}const head=path.at(-1),old=path.at(-2),a=Math.atan2(head.y-old.y,head.x-old.x);cvConstruct(c,"spell-dragon",head.x,head.y-24,112*A,a,.94);c.restore();}
c.restore();return true;}
export function drawCampaignEffect(r,f){if(!f.kind.startsWith("campaign-"))return false;const c=r.ctx,u=1-f.ttl/f.max,key=f.key,color=STAGE_SKILLS[key]?.color||"#a9efd0";c.save();c.globalAlpha=Math.max(0,1-u);
if(f.kind==="campaign-slash"){c.translate(f.x,f.y-18);c.rotate(f.angle);const length=f.r;cvPoly(c,[[0,8],[length*.4,-length*.14],[length,0],[length*.4,length*.11],[0,-4]],color+"8f");c.strokeStyle="#fff7e2";c.lineWidth=2.1;c.beginPath();c.moveTo(0,0);c.quadraticCurveTo(length*.65,-length*.13,length,0);c.stroke();cvSword(c,length*.42,0,Math.min(95,length*.4),Math.PI/2,.62);}
else if(f.kind==="campaign-chain"){const points=[];for(let i=0;i<=8;i++){const q=i/8;points.push({x:f.x+(f.x2-f.x)*q+(i===0||i===8?0:Math.sin(i*4.7)*9),y:f.y+(f.y2-f.y)*q});}cvStreak(c,points,"#b9efff",2);}
else if(f.kind==="campaign-heal"){c.strokeStyle="#a7efcb";c.lineWidth=2;c.beginPath();c.ellipse(f.x,f.y,f.r*u,f.r*u*.5,0,0,cvTAU);c.stroke();for(let i=0;i<6;i++){const a=i*cvTAU/6,x=f.x+Math.cos(a)*f.r*.5,y=f.y+Math.sin(a)*f.r*.25-u*25;c.fillStyle="#bcffda";c.fillRect(x-2,y-7,4,14);c.fillRect(x-7,y-2,14,4);}}
else{const row=key==="explosive"?1:["spirit","dragon"].includes(key)?3:["gravity","blackflame"].includes(key)?5:key==="stormbow"?2:0;drawMaterial(c,row,Math.min(5,Math.floor(u*6)),f.x,f.y-12,f.r*1.7,f.r*1.4,0,.75);for(let i=0;i<7;i++){const a=i*2.4,d=f.r*u*(.35+(i%3)*.12);c.save();c.translate(f.x+Math.cos(a)*d,f.y+Math.sin(a)*d*.65-12);c.rotate(a);cvPoly(c,[[0,0],[4,-3],[16+u*9,0],[4,3]],color);c.restore();}}
c.restore();return true;}
export function drawCampaignEnemyMarks(r,e,t){const c=r.ctx;c.save();
if(e.kind==="bomber"&&e.fuse){c.strokeStyle="#ffb484";c.lineWidth=2;c.setLineDash([5,3]);c.beginPath();c.ellipse(e.x,e.y,80,60,0,0,cvTAU);c.stroke();c.setLineDash([]);r.glow(e.x,e.y-25,65,"red",1-e.fuse/.9);}
if(e.aim){c.strokeStyle=e.aim.age>.7?"#ffd3ba":"#ddaaaa80";c.lineWidth=e.aim.age>.7?2:1;c.beginPath();c.moveTo(e.x,e.y-15);c.lineTo(e.x+Math.cos(e.aim.angle)*600,e.y+Math.sin(e.aim.angle)*600-15);c.stroke();}
if(e.kind==="guard"){const a=e.faceAngle||0;c.strokeStyle="#edc68b88";c.lineWidth=3;c.beginPath();c.arc(e.x,e.y,e.r+6,a-.9,a+.9);c.stroke();}
c.restore();}
export function makeCampaignGround(r,stage){if(!r.stagePatterns)r.stagePatterns=new Map();if(r.stagePatterns.has(stage))return r.stagePatterns.get(stage);const canvas=document.createElement("canvas");canvas.width=canvas.height=768;const c=canvas.getContext("2d");c.drawImage(r.tile,0,0);c.fillStyle=STAGES[stage-1].tint;c.fillRect(0,0,768,768);
for(let i=0;i<32;i++){const x=(i*173)%768,y=(i*269)%768;c.save();c.translate(x,y);c.rotate(i*2.4);if(stage===2){c.strokeStyle="#180c10bc";c.lineWidth=7;c.beginPath();c.moveTo(-25,-20);c.lineTo(0,4);c.lineTo(36,-8);c.stroke();c.strokeStyle="#e1976c66";c.lineWidth=1;c.stroke();}if(stage===3){cvPoly(c,[[0,-10],[5,0],[0,10],[-5,0]],i%2?"#84679855":"#aac98a44");}if(stage===4){c.strokeStyle="#bde2ec88";c.lineWidth=1.2;c.beginPath();c.moveTo(-45,0);c.lineTo(-7,-5);c.lineTo(10,12);c.lineTo(38,0);c.moveTo(-7,-5);c.lineTo(0,-24);c.stroke();}if(stage===5){c.strokeStyle="#cf76846b";c.lineWidth=1;c.strokeRect(-14,-14,28,28);c.rotate(.7);c.strokeRect(-10,-10,20,20);c.fillStyle="#280d2966";c.fillRect(-8,-8,16,16);}c.restore();}
const pattern=r.ctx.createPattern(canvas,"repeat");r.stagePatterns.set(stage,pattern);return pattern;}
