import {drawWhirlwind,drawFrostCrown,drawFrostPulse,drawMetalContact} from "./hero-vfx.js";
import {Art,drawMaterial} from "./art.js";
const VFX_TAU=Math.PI*2,cap=v=>Math.max(0,Math.min(1,v)),noise=(i,s)=>{const n=Math.sin(i*127.1+s*17.7)*43758.5453;return n-Math.floor(n);};
function materialRow(key){return ["fireball","meteor","pyre","burn"].includes(key)?1:key==="lightning"?2:["bolt","nova","frost","ultimate-mage"].includes(key)?3:["slam","fissure"].includes(key)?4:key==="beam"?5:0;}
function shards(c,x,y,r,progress,color,count,stone=false){c.save();c.translate(x,y);c.fillStyle=color;for(let i=0;i<count;i++){const q=i*2.399+noise(i,x)*.4,dist=(.15+progress*.85)*r*(.4+noise(i,y)*.6),size=(stone?7:4)*(1-progress)+1,xx=Math.cos(q)*dist,yy=Math.sin(q)*dist*.72-progress*(1-progress)*r*.4;c.save();c.translate(xx,yy);c.rotate(q+progress*4);c.beginPath();c.moveTo(size,0);c.lineTo(-size*.3,-size*.65);c.lineTo(-size,-size*.2);c.lineTo(-size*.5,size*.5);c.closePath();c.fill();c.restore();}c.restore();}
function cracks(c,x,y,r,u,alpha,color){c.save();c.translate(x,y);c.strokeStyle=color;c.lineWidth=2.1*alpha;for(let i=0;i<7;i++){const a=i*VFX_TAU/7,n=r*(.22+cap(u*2)*.78);c.beginPath();c.moveTo(Math.cos(a)*15,Math.sin(a)*9);c.lineTo(Math.cos(a+.16)*n*.5,Math.sin(a+.16)*n*.32);c.lineTo(Math.cos(a-.08)*n*.77,Math.sin(a-.08)*n*.53);c.lineTo(Math.cos(a+.06)*n,Math.sin(a+.06)*n*.7);c.stroke();}c.restore();}
export function drawMaterialEffect(r,f,t,g,a,u){
if(f.kind==="whirlwind"){drawWhirlwind(r,f,t,g);return true;}
if(f.kind==="frost-crown"){drawFrostCrown(r,f,t,g);return true;}
if(f.kind==="frost-storm"&&f.ultimate){drawFrostPulse(r,f,t);return true;}
if(f.kind==="impact"&&["orbit","whirlwind"].includes(f.key)){drawMetalContact(r,f);return true;}
if(!Art.materialFrames.size)return false;const c=r.ctx,x=f.follow?g.player.x:f.x,y=f.follow?g.player.y-18:f.y,col=Math.min(5,Math.floor(u*6)),row=materialRow(f.key==="ultimate"&&g.hero.id==="mage"?"ultimate-mage":f.key),count=r.reduced?3:r.quality<.8?6:11;
if(["slash","blood-cut","whirlwind","cut-hit","fire-burst","meteor-impact","quake","bolt-hit","impact","burst","frost-storm","lightning-strike","flame-pillar","ice-shatter","blood-eruption","fire-residue","poison-residue","thorn-residue"].includes(f.kind)){
 c.globalAlpha=1;
 if(f.kind==="slash"||f.kind==="blood-cut"){const radius=f.r||100;c.save();c.translate(x,y);c.rotate((f.angle||0)-.48);drawMaterial(c,0,col,0,0,radius*2.22,radius*1.76,0,f.echo?.5:.96);c.globalCompositeOperation="lighter";c.strokeStyle=f.kind==="blood-cut"?"#db7468":"#fff3bc";c.lineWidth=(f.echo?1:2.8)*a;c.beginPath();c.arc(0,0,radius*.91,-1.15+cap(u*3)*.4,1.03);c.stroke();c.restore();if(!r.reduced)shards(c,x,y,radius*.95,u,f.kind==="blood-cut"?"#b74949":"#d5ad62",count);return true;}
 if(f.kind==="fire-burst"||f.kind==="meteor-impact"||f.kind==="flame-pillar"){const radius=f.r||90,pillar=f.kind==="flame-pillar";drawMaterial(c,1,col,x,y-(pillar?radius*.55:15),radius*(pillar?1.6:2.25),radius*(pillar?3.0:1.9),0,.98);if(u<.17)r.glow(x,y,Math.min(170,radius*1.8),"red",(1-u/.17)*.85);cracks(c,x,y,radius,u,a*.6,"#bc6a35");if(!r.reduced)shards(c,x,y,radius*1.25,u,"#e49347",count,true);return true;}
 if(f.kind==="quake"){drawMaterial(c,4,col,x,y-10,f.r*2.1,f.r*1.6,0,.94);cracks(c,x,y,f.r,u,a,"#d8a66d");if(!r.reduced)shards(c,x,y,f.r*1.1,u,"#8f775e",count,true);return true;}
 if(f.kind==="frost-storm"){const phase=Math.floor((t*6)%4)+1;drawMaterial(c,3,phase,x,y-13,f.r*2.05,f.r*1.4,0,f.ultimate?.50:.37);if(!r.reduced)shards(c,x,y,f.r,(t*.36)%1,"#a9d2d9",count);return true;}
 if(f.kind==="fire-residue"){drawMaterial(c,1,4,x,y-10,f.r*2,f.r*1.5,t*.08,.28*a);cracks(c,x,y,f.r,.8,a*.35,"#b56b36");return true;}
 if(f.kind==="poison-residue"||f.kind==="thorn-residue"||f.kind==="blood-eruption"){c.save();c.translate(x,y);const dark=f.kind==="blood-eruption";c.fillStyle=dark?"#611e2877":"#39432270";c.beginPath();for(let i=0;i<14;i++){const q=i*VFX_TAU/14,rad=f.r*(.75+noise(i,x)*.22);const xx=Math.cos(q)*rad,yy=Math.sin(q)*rad*.67;if(!i)c.moveTo(xx,yy);else c.lineTo(xx,yy);}c.closePath();c.fill();if(f.kind==="thorn-residue")for(let i=0;i<count;i++){const q=i*2.4,dist=f.r*Math.sqrt(noise(i,y)),xx=Math.cos(q)*dist,yy=Math.sin(q)*dist*.7;c.fillStyle="#b5bc86";c.beginPath();c.moveTo(xx,yy-22*a);c.lineTo(xx+5,yy);c.lineTo(xx-4,yy+3);c.closePath();c.fill();}else{c.strokeStyle=dark?"#b96364":"#a9bd53";c.lineWidth=1.3;for(let i=0;i<count;i++){const q=i*2.4,dist=f.r*Math.sqrt(noise(i,y));c.beginPath();c.arc(Math.cos(q)*dist,Math.sin(q)*dist*.65,2+noise(i,x)*4,0,VFX_TAU);c.stroke();}}c.restore();return true;}
 if(f.kind==="lightning-strike"){const strike=cap(u*5);c.save();c.globalCompositeOperation="lighter";c.beginPath();c.moveTo(x+10,y-190*(1-strike*.2));c.lineTo(x-14,y-110);c.lineTo(x+13,y-60);c.lineTo(x,y);c.strokeStyle="#84b8ec77";c.lineWidth=10*a;c.stroke();c.strokeStyle="#eef6ff";c.lineWidth=2*a;c.stroke();c.restore();drawMaterial(c,2,col,x,y-12,(f.r||40)*2.6,(f.r||40)*2.1,0,.9);return true;}
 const chosen=f.kind==="bolt-hit"||f.kind==="ice-shatter"?3:f.kind==="cut-hit"?0:row,size=f.kind==="burst"?58:f.kind==="ice-shatter"?(f.r||45)*2:chosen===4?100:chosen===1?96:chosen===5?95:chosen===2?90:75;
 drawMaterial(c,chosen,col,x,y,size,size*.88,f.kind==="cut-hit"?(f.angle||0)-.5:0,f.kind==="burst"?.58:.9);
 if(u<.14)r.glow(x,y,size*.55,chosen===1?"red":chosen>=2&&chosen!==4?"blue":"gold",(1-u/.14)*.65);
 return true;
}
if(f.kind==="line"){c.globalAlpha=1;c.save();const dx=f.x2-f.x,dy=f.y2-f.y,length=Math.hypot(dx,dy)||1,nx=-dy/length,ny=dx/length,segments=Math.min(18,Math.max(5,Math.ceil(length/18))),points=[[f.x,f.y]];for(let i=1;i<segments;i++){const q=i/segments,off=(noise(i,Math.floor(t*24)+f.x)*2-1)*16;points.push([f.x+dx*q+nx*off,f.y+dy*q+ny*off]);}points.push([f.x2,f.y2]);c.beginPath();c.moveTo(...points[0]);for(const p of points.slice(1))c.lineTo(...p);c.strokeStyle="#628cc14d";c.lineWidth=13*a;c.stroke();c.strokeStyle="#9acff5";c.lineWidth=3.7*a;c.stroke();c.strokeStyle="#f1faff";c.lineWidth=1.2;c.stroke();if(!r.reduced){c.strokeStyle="#9fc2e8aa";c.lineWidth=1;for(let i=2;i<points.length-1;i+=4){const p=points[i],side=i%2?1:-1;c.beginPath();c.moveTo(...p);c.lineTo(p[0]+nx*20*side+dx*.06,p[1]+ny*20*side+dy*.06);c.lineTo(p[0]+nx*38*side+dx*.12,p[1]+ny*38*side+dy*.12);c.stroke();}}c.restore();drawMaterial(c,2,col,f.x2,f.y2,92,96,0,a*.84);return true;}
if(f.kind==="sun-cleave"){const age=f.max-f.ttl,fall=cap(age/.3),impact=cap((age-.28)/.92);c.globalAlpha=1;if(age<.43){c.save();c.translate(x,y-310*(1-fall));c.globalAlpha=age<.32?1:cap((.43-age)/.11);r.glow(0,-90,160,"gold",.8);const grad=c.createLinearGradient(-15,0,15,0);grad.addColorStop(0,"#9b7035");grad.addColorStop(.45,"#fff6c5");grad.addColorStop(.55,"#fff");grad.addColorStop(1,"#c6a15a");c.fillStyle=grad;c.beginPath();c.moveTo(0,12);c.lineTo(-13,-34);c.lineTo(-10,-190);c.lineTo(10,-190);c.lineTo(13,-34);c.closePath();c.fill();c.fillStyle="#d0a257";c.fillRect(-44,-196,88,10);c.fillRect(-5,-228,10,33);c.restore();}if(age>.28){drawMaterial(c,0,Math.min(5,Math.floor(impact*6)),x,y-12,f.r*2.2,f.r*1.7,-.28,.94);drawMaterial(c,4,Math.min(5,Math.floor(impact*6)),x,y-10,f.r*1.65,f.r*1.15,0,.72);cracks(c,x,y,f.r,impact,1-impact,"#e6c687");if(!r.reduced)shards(c,x,y,f.r,impact,"#c3aa75",count+4,true);}return true;}

return false;}
export function drawMaterialProjectile(r,b){if(!["hammer","glaive","slam","fireball","bolt","nova","cleave"].includes(b.key))return false;const c=r.ctx;c.save();c.translate(b.x,b.y-20);const angle=["slam","fireball","bolt","nova","cleave"].includes(b.key)?Math.atan2(b.vy,b.vx):(b.age||0)*(b.key==="hammer"?10:16);c.rotate(angle);r.glow(0,0,b.key==="hammer"?48:42,b.key==="glaive"?"mint":"gold",.22);if(b.key==="fireball"){const grad=c.createLinearGradient(-68,0,10,0);grad.addColorStop(0,"#8d3b1b00");grad.addColorStop(.65,"#d6682977");grad.addColorStop(1,"#ffe5a6");c.fillStyle=grad;c.beginPath();c.moveTo(-70,0);c.quadraticCurveTo(-18,-13,14,-5);c.quadraticCurveTo(23,0,14,5);c.quadraticCurveTo(-18,13,-70,0);c.fill();drawMaterial(c,1,1+Math.floor((b.age||0)*14)%3,-5,0,b.evolved?74:59,42,-Math.PI/2,.82);}
else if(b.key==="bolt"||b.key==="nova"){const length=b.key==="bolt"?(b.evolved?33:25):18,width=b.key==="bolt"?7:5;c.fillStyle="#78a8b45c";c.beginPath();c.moveTo(-length*2.2,0);c.lineTo(-9,-width);c.lineTo(length,0);c.lineTo(-9,width);c.closePath();c.fill();const grad=c.createLinearGradient(-10,-width,12,width);grad.addColorStop(0,"#528b9e");grad.addColorStop(.5,"#dcf1ec");grad.addColorStop(1,"#7baebf");c.fillStyle=grad;c.beginPath();c.moveTo(length,0);c.lineTo(-6,-width);c.lineTo(-15,0);c.lineTo(-6,width);c.closePath();c.fill();c.strokeStyle="#e7f5ed";c.lineWidth=1;c.beginPath();c.moveTo(-14,0);c.lineTo(length,0);c.stroke();}
else if(b.key==="cleave"){drawMaterial(c,0,2,0,0,b.r*2.4,b.r*3.1,-.5,.86);c.strokeStyle="#f8e6bc";c.lineWidth=1.3;c.beginPath();c.arc(-12,0,b.r*1.35,-1.08,1.08);c.stroke();}
else if(b.key==="hammer"){c.fillStyle="#9f7645";c.fillRect(-3,-7,6,29);const grad=c.createLinearGradient(-15,-20,15,0);grad.addColorStop(0,"#dec48e");grad.addColorStop(.55,"#82613f");grad.addColorStop(1,"#f6e5ac");c.fillStyle=grad;c.beginPath();c.moveTo(-18,-17);c.lineTo(-12,-25);c.lineTo(13,-23);c.lineTo(20,-14);c.lineTo(13,-5);c.lineTo(-14,-7);c.closePath();c.fill();c.strokeStyle="#e0c998";c.lineWidth=1;c.stroke();}else if(b.key==="glaive"){for(const side of [-1,1]){c.save();c.scale(side,side);const grad=c.createLinearGradient(-20,0,20,-13);grad.addColorStop(0,"#365e64");grad.addColorStop(.5,"#c9dcd6");grad.addColorStop(1,"#6c9894");c.fillStyle=grad;c.beginPath();c.moveTo(-26,5);c.quadraticCurveTo(-8,-27,27,-11);c.quadraticCurveTo(7,-10,-5,8);c.closePath();c.fill();c.strokeStyle="#dfece2";c.lineWidth=.9;c.stroke();c.restore();}}else{c.fillStyle="#8d7154";c.beginPath();c.moveTo(12,0);c.lineTo(2,-6);c.lineTo(-8,-3);c.lineTo(-5,7);c.closePath();c.fill();}c.restore();return true;}
export function drawMaterialField(r,f,t){const c=r.ctx;if(["fissure","pyre"].includes(f.key)&&f.delay>0){c.save();c.translate(f.x,f.y);const u=cap(1-f.delay/.65);c.fillStyle=f.key==="pyre"?"#9b462921":"#c69a4421";c.beginPath();c.ellipse(0,0,f.r*.82,f.r*.52,0,0,VFX_TAU);c.fill();cracks(c,0,0,f.r*.8,u,.28+u*.32,f.key==="pyre"?"#cf7f4c":"#a38b63");if(f.key==="pyre")drawMaterial(c,1,0,0,-16-u*20,f.r*.8,f.r*1.4,0,u*.46);c.restore();return true;}if(f.key!=="beam")return false;c.save();c.translate(f.x,f.y-20);c.rotate(f.angle);const alpha=Math.min(1,f.ttl*4),width=f.r,pulse=.88+Math.sin(t*31)*.08;c.globalAlpha=alpha;const gradient=c.createLinearGradient(0,0,f.length,0);gradient.addColorStop(0,"#3a255800");gradient.addColorStop(.06,"#815ed989");gradient.addColorStop(.65,"#8e6be6bb");gradient.addColorStop(1,"#5c3a9900");c.fillStyle=gradient;c.beginPath();c.moveTo(8,-4);c.lineTo(f.length,-width*pulse);c.lineTo(f.length,width*pulse);c.lineTo(8,4);c.closePath();c.fill();c.globalCompositeOperation="lighter";c.strokeStyle="#b4a2e7";c.lineWidth=width*.34;c.beginPath();c.moveTo(8,0);c.lineTo(f.length,0);c.stroke();c.strokeStyle="#eef3ed";c.lineWidth=2.4;c.stroke();c.globalCompositeOperation="source-over";drawMaterial(c,5,2,14,0,78,70,t*.9,.66);drawMaterial(c,5,Math.floor(t*9)%4+1,f.length,0,width*3.6,width*3.3,-f.angle,.78);if(!r.reduced){c.strokeStyle="#b199d877";c.lineWidth=1;for(const side of [-1,1]){c.beginPath();c.moveTo(14,side*7);for(let i=1;i<9;i++)c.lineTo(i*f.length/9,side*(width*.65+Math.sin(i*1.6+t*14)*5));c.stroke();}}c.restore();return true;}
