import "./style.css";
import {Game,HEROES,UPGRADES,EVOLUTIONS,cleanSave,purchase,reward,metaCost} from "./core.js";
import {Platform} from "./platform.js";
import {Renderer,drawHero} from "./render.js";
import {Audio} from "./audio.js";
import {FixedClock,RenderBudget,joystick} from "./runtime.js";
const $=id=>document.getElementById(id),platform=new Platform(),audio=new Audio(),renderer=new Renderer($("world"));
let save=cleanSave(),hero=HEROES[0],game=null,ready=false,settled=false,dialogKind=null,returnFocus=null,last=0,clock=0,bannerUntil=0,skillSignature="",exiting=false;
const simulation=new FixedClock(),budget=new RenderBudget(),metrics={frames:0,steps:0,frameMs:0,updateMs:0,renderMs:0};let lastDraw=0,lastHud=0;
const joy={active:false,id:null,x:0,y:0,ox:0,oy:0,keyboard:false},keys=new Set();
const format=n=>Math.floor(n).toLocaleString("ko-KR"),timeText=n=>String(Math.floor(n/60)).padStart(2,"0")+":"+String(Math.floor(n%60)).padStart(2,"0");
function toast(text){$("toast").textContent=text;$("toast").classList.add("visible");clearTimeout(toast.timer);toast.timer=setTimeout(()=>$("toast").classList.remove("visible"),4000);}
platform.onSaveError=()=>toast("기록을 저장하지 못했어요. 앱을 닫기 전에 설정에서 다시 저장해 주세요.");
const persist=()=>platform.save(save);
function resetInput(){joy.active=false;joy.id=null;joy.x=joy.y=0;joy.keyboard=false;keys.clear();}
function modal(html,kind){resetInput();if(!dialogKind)returnFocus=document.activeElement;dialogKind=kind;$("dialog").innerHTML=html;$("overlay").classList.remove("hidden");$("dialog").focus();}
function hideModal(){dialogKind=null;$("overlay").classList.add("hidden");$("dialog").innerHTML="";if(returnFocus?.isConnected)returnFocus.focus();returnFocus=null;}
const heading=(eyebrow,title,desc)=>'<div class="eyebrow">'+eyebrow+'</div><h2 id="dialog-title">'+title+'</h2>'+(desc?'<p>'+desc+'</p>':"");
function updateHome(){$("coins").textContent=format(save.coins);$("best").textContent=format(save.best);$("wins").textContent=format(save.wins);$("hero-description").textContent=hero.tag;for(const card of document.querySelectorAll(".hero")){const on=card.dataset.hero===hero.id;card.classList.toggle("selected",on);card.setAttribute("aria-pressed",String(on));card.querySelector(".check").textContent=on?"✓":"";}}
function showHome(){resetInput();game=null;exiting=false;settled=false;hideModal();$("home").classList.remove("hidden");$("hud").classList.add("hidden");platform.awake(false);updateHome();}
function renderHeroes(){$("heroes").innerHTML=HEROES.map(h=>'<button class="hero" data-hero="'+h.id+'" aria-pressed="false"><span class="check"></span><canvas width="96" height="100" aria-hidden="true"></canvas><strong>'+h.name+'</strong></button>').join("");for(const card of document.querySelectorAll(".hero")){const h=HEROES.find(x=>x.id===card.dataset.hero),c=card.querySelector("canvas").getContext("2d");c.imageSmoothingEnabled=false;drawHero(c,h,48,58,3,1,0);card.onclick=()=>{hero=h;updateHome();audio.unlock();audio.tone(440,.08,.02);};}}
function startGame(){if(!ready)return;simulation.reset();last=0;lastHud=0;budget.set(save.settings.performance);renderer.setQuality(budget.scale);audio.enabled=save.settings.sound;audio.unlock();hideModal();resetInput();settled=false;exiting=false;skillSignature="";game=new Game(hero.id,save.meta);game.spawnDistance=Math.max(470,Math.min(650,renderer.h*.6));$("home").classList.add("hidden");$("hud").classList.remove("hidden");$("bossbar").classList.add("hidden");platform.awake(true);banner("숲의 균열 · 5분 생존",2.7);$("move-hint").textContent="화면을 드래그해 이동";updateHud();}
function banner(text,seconds=2){$("banner").textContent=text;$("banner").style.opacity="1";bannerUntil=clock+seconds;}
function showUpgrade(){const choices=game.choices;modal(heading("LEVEL "+game.level,"새로운 힘을 선택하세요","공격은 잠시 멈춰요. 이번 도전에 사용할 스킬을 골라 주세요.")+'<div class="upgrade-list">'+choices.map((key,i)=>{const original=UPGRADES[key],ev=EVOLUTIONS[key],u=(game.evolved[key]?{...original,name:ev.name,desc:ev.desc}:original)||{name:"회복의 빛",icon:"♥",color:"#ffb5bc",desc:"체력을 35 회복해요"},lv=game.weapons[key]||game.passives[key]||0;return '<button class="upgrade '+(lv===4?"evolved":"")+'" data-choice="'+i+'"><span class="glyph" style="color:'+u.color+'">'+u.icon+'</span><span><strong>'+u.name+'</strong><small>'+u.desc+(ev&&!game.evolved[key]?'<em>진화: 무기 Lv.5 + '+UPGRADES[ev.passive].name+' Lv.2</em>':'')+'</small></span><span class="lv">'+(lv===4?"Lv. 5":lv?"Lv. "+(lv+1):"신규")+'</span></button>';}).join("")+'</div><button id="reroll" class="secondary" '+(game.rerolls<=0?'disabled':'')+'>다시 뽑기 · '+game.rerolls+'회 남음</button><p class="tip">무기는 최대 4개 · 각 스킬은 최대 5레벨까지 성장해요.</p>',"upgrade");$("reroll").onclick=()=>{if(game.reroll())showUpgrade();};for(const b of document.querySelectorAll("[data-choice]"))b.onclick=()=>{if(game.choose(choices[Number(b.dataset.choice)])){audio.unlock();hideModal();if(game.phase==="upgrade")showUpgrade();}};}
function settleRun(){if(!game?.result||settled)return;settled=true;save=reward(save,game.result);persist().catch(()=>{});}
function showResult(){settleRun();platform.awake(false);const r=game.result;modal('<div class="result-symbol">'+(r.win?"✦":"◈")+'</div>'+heading(r.win?"RIFT CLOSED":"A NEW BEGINNING",r.win?"균열을 닫았어요!":"다음 도전은 더 강하게",r.win?"별빛이 숲으로 돌아왔어요. 수호자의 다음 모험을 준비해 보세요.":"모은 보석으로 영구 강화하면 다음 도전이 더 수월해져요.")+'<div class="stats"><div class="stat"><small>점수</small><b>'+format(r.score)+'</b></div><div class="stat"><small>처치한 적</small><b>'+format(r.kills)+'</b></div><div class="stat"><small>생존 시간</small><b>'+timeText(r.time)+'</b></div><div class="stat"><small>도달 레벨</small><b>'+r.level+'</b></div></div><div class="reward">획득한 보석　◈ +'+r.coins+'</div><button id="again" class="primary">같은 영웅으로 다시 도전</button><button id="result-home" class="secondary">영웅 선택으로 돌아가기</button>',"result");$("again").onclick=startGame;$("result-home").onclick=showHome;}
function showPause(){if(!game)return;if(game.phase==="playing")game.pause();audio.stop();platform.awake(false);modal(heading("TAKE A BREATH","잠시 쉬어 가세요","도전은 멈춰 있어요. 준비되면 계속할 수 있어요.")+'<button id="resume" class="primary">도전 계속하기</button><button id="pause-settings" class="secondary">사운드 · 화면 설정</button><button id="retire" class="secondary">이번 도전 마치고 보상 받기</button><button id="pause-exit" class="text-button">미니앱 종료</button>',"pause");$("resume").onclick=()=>{hideModal();game.resume();audio.unlock();platform.awake(true);};$("pause-settings").onclick=()=>showSettings(true);$("retire").onclick=()=>{game.finish(false);showResult();};$("pause-exit").onclick=requestExit;}
function showSettings(fromGame=false){modal(heading("SETTINGS","내게 맞게 플레이","설정과 기록은 이 기기에 저장돼요.")+'<div class="setting-row"><span>배경음 · 효과음</span><button id="sound" class="toggle '+(save.settings.sound?"on":"")+'" aria-pressed="'+save.settings.sound+'">'+(save.settings.sound?"켜짐":"꺼짐")+'</button></div><div class="setting-row"><span>움직이는 효과 줄이기</span><button id="motion" class="toggle '+(save.settings.reduced?"on":"")+'" aria-pressed="'+save.settings.reduced+'">'+(save.settings.reduced?"켜짐":"꺼짐")+'</button></div><div class="setting-row"><span>화면 성능</span><button id="performance" class="toggle">'+({auto:"자동",smooth:"부드럽게",battery:"배터리 절약"}[save.settings.performance])+'</button></div><button id="save-retry" class="secondary">기록 저장 다시 시도</button><button id="settings-close" class="primary">'+(fromGame?"일시정지 화면으로":"영웅 선택으로")+'</button><button id="settings-exit" class="text-button">미니앱 종료</button>',"settings");
$("sound").onclick=()=>{save.settings.sound=!save.settings.sound;audio.set(save.settings.sound);if(fromGame)audio.stop();persist().catch(()=>{});showSettings(fromGame);};$("motion").onclick=()=>{save.settings.reduced=!save.settings.reduced;renderer.reduced=save.settings.reduced;persist().catch(()=>{});showSettings(fromGame);};$("performance").onclick=()=>{const modes=["auto","smooth","battery"];save.settings.performance=modes[(modes.indexOf(save.settings.performance)+1)%3];budget.set(save.settings.performance);renderer.setQuality(budget.scale);persist().catch(()=>{});showSettings(fromGame);};$("save-retry").onclick=async()=>{try{await persist();toast("기록을 저장했어요.");}catch{toast("저장이 완료되지 않았어요. 연결을 확인하고 다시 시도해 주세요.");}};$("settings-close").onclick=()=>{hideModal();if(fromGame)showPause();};$("settings-exit").onclick=requestExit;}
function showForge(){const defs={power:["공격의 룬","공격력 +6%"],heart:["생명의 룬","시작 체력 +10"],fortune:["인력의 룬","경험치 수집 범위 +8"]};modal(heading("THE RUNE FORGE","다음 모험을 위한 힘","도전 중 모은 보석으로 강화해요. 구매한 강화는 모든 영웅에게 계속 적용돼요.")+'<div class="reward">보유 보석　◈ '+format(save.coins)+'</div>'+Object.entries(defs).map(([key,[name,desc]])=>{const lv=save.meta[key],cost=metaCost(lv);return '<div class="forge-row"><span><strong>'+name+' · '+lv+'/5</strong><small>'+desc+' / 단계</small></span><button data-forge="'+key+'" '+(lv>=5||save.coins<cost?"disabled":"")+'>'+(lv>=5?"최대 강화":"◈ "+cost)+'</button></div>';}).join("")+'<p class="tip">보석은 플레이로만 얻어요. 실제 돈으로 결제하는 기능은 없어요.</p><button id="forge-close" class="primary">영웅 선택으로</button>',"forge");for(const b of document.querySelectorAll("[data-forge]"))b.onclick=()=>{const r=purchase(save,b.dataset.forge);if(r.ok){save=r.save;persist().catch(()=>{});audio.unlock();audio.event("choose");updateHome();showForge();}};$("forge-close").onclick=hideModal;}
function showHelp(){modal(heading("HOW TO PLAY","5분 뒤, 균열의 군주를 만나세요","복잡한 조작 없이 이동과 선택에 집중하세요.")+'<div class="help-step"><b>1</b><p>전장 아무 곳이나 드래그해 이동해요. 공격은 자동으로 나가요.</p></div><div class="help-step"><b>2</b><p>초록 경험치를 모아요. 레벨이 오르면 스킬 하나를 선택해요. 무기 Lv.5와 연결된 룬 Lv.2를 모으면 진화해요.</p></div><div class="help-step"><b>3</b><p>회피로 위험에서 벗어나고, 별빛 폭풍으로 주변 적을 한 번에 공격해요.</p></div><div class="help-step"><b>4</b><p>빨간 마법진과 보라색 탄환을 피하세요. 5분 뒤 보스를 물리치면 승리해요.</p></div><p class="tip">PC: WASD/방향키 이동 · Space 회피 · E 궁극기 · Esc 일시정지</p><button id="help-close" class="primary">알겠어요</button>',"help");$("help-close").onclick=hideModal;}
function showPrivacy(){modal(heading("GAME INFORMATION","게임과 데이터 안내","균열의 수호자 · 버전 1.1.0")+'<div class="privacy"><h3>어떤 게임인가요?</h3><p>세 영웅의 스킬을 조합해 숲을 지키는 2D 생존 액션이에요. 그래픽과 음향은 게임 안에서 생성해요.</p><h3>어떤 정보를 저장하나요?</h3><p>토스 익명 식별키를 이용해 이 기기에 점수, 보석, 강화와 설정을 저장해요. 이름, 연락처, 위치는 요청하지 않으며 별도 서버로 전송하지 않아요.</p><h3>기록은 어디에 남나요?</h3><p>기기 안의 토스 저장소에 남아요. 기기를 바꾸거나 미니앱 데이터를 삭제하면 기록이 이어지지 않을 수 있어요.</p><h3>문의하기</h3><p>토스 우측 상단 더보기의 문의하기를 이용해 주세요.</p></div><button id="privacy-close" class="primary">닫기</button>',"privacy");$("privacy-close").onclick=hideModal;}
function requestExit(){if(!ready)return;const active=game&&!game.result,before=game?.phase;if(game?.phase==="playing")game.pause();resetInput();audio.stop();platform.awake(false);modal(heading("LEAVE THE RIFT","미니앱을 종료할까요?",active?"이번 도전은 종료돼요. 지금까지 획득한 보상을 저장한 뒤 나가요.":"점수, 보석과 강화는 이 기기에 저장돼요.")+'<button id="exit-cancel" class="primary">계속 머무르기</button><button id="exit-confirm" class="secondary">저장하고 종료</button>',"exit");$("exit-cancel").onclick=()=>{hideModal();if(game){if(before==="upgrade")showUpgrade();else if(game.result)showResult();else showPause();}else audio.unlock();};
$("exit-confirm").onclick=async()=>{const b=$("exit-confirm");b.disabled=true;b.textContent="기록을 저장하고 있어요";exiting=true;try{if(game&&!game.result)game.finish(false);settleRun();await persist();await platform.close();if(import.meta.env.DEV)showHome();}catch{exiting=false;b.disabled=false;b.textContent="저장하고 종료";toast("저장을 완료하지 못했어요. 다시 시도해 주세요.");}};}
function updateHud(){if(!game)return;const p=game.player;$("hptext").textContent=Math.ceil(p.hp)+" / "+p.maxHp;$("hpbar").style.width=(p.hp/p.maxHp*100)+"%";$("level").textContent="Lv. "+game.level;$("xpbar").style.width=(game.xp/game.need*100)+"%";$("time").textContent=timeText(game.time);$("kills").textContent=format(game.kills);$("objective").textContent=game.bossSpawned?"균열의 군주를 처치하세요":"05:00까지 생존";const boss=game.enemies.find(e=>e.boss);$("bossbar").classList.toggle("hidden",!boss);if(boss)$("bossfill").style.width=Math.max(0,boss.hp/boss.maxHp*100)+"%";
for(const [id,cd]of [["dash",p.dashCd],["ultimate",p.ultCd]]){const b=$(id);b.querySelector("b").textContent=cd>0?String(Math.ceil(cd)):"";b.disabled=cd>0||game.phase!=="playing";}const sig=JSON.stringify([game.weapons,game.evolved]);if(sig!==skillSignature){skillSignature=sig;$("skills").innerHTML=Object.entries(game.weapons).map(([k,lv])=>'<span class="skill" style="color:'+UPGRADES[k].color+'" aria-label="'+(game.evolved[k]?EVOLUTIONS[k].name:UPGRADES[k].name)+' '+lv+'레벨">'+UPGRADES[k].icon+'<small>'+(game.evolved[k]?'✦':lv)+'</small></span>').join("");}}
function frame(ts){
const elapsed=last?Math.max(0,(ts-last)/1000):0;last=ts;clock=ts/1000;metrics.frameMs=elapsed*1000;
if(document.hidden){simulation.reset();requestAnimationFrame(frame);return;}
if(game?.phase==="playing"&&budget.observe(elapsed*1000))renderer.setQuality(budget.scale);
const begun=performance.now();
if(game){let x=joy.x,y=joy.y;const kx=(keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0),ky=(keys.has("s")||keys.has("arrowdown")?1:0)-(keys.has("w")||keys.has("arrowup")?1:0);joy.keyboard=!!(kx||ky);if(joy.keyboard){x=kx;y=ky;}
metrics.steps+=simulation.advance(elapsed,dt=>game.step(dt,{x,y}),()=>game?.phase==="playing");
for(const e of game.events.splice(0)){audio.event(e.type,e.key);if(e.type==="boss")banner("균열의 군주가 깨어났어요",3);if(e.type==="elite")banner("강력한 적이 나타났어요",2);if(e.type==="evolve")banner(e.name+" · 진화!",2.5);if(e.type==="chest")banner("정예 보상 · 경험치와 회복",1.8);if(e.type==="magnet")banner("모든 경험치를 끌어당겨요",1.8);if(e.type==="supply")banner("푸른 인력 상자가 나타났어요",1.8);}
if(!exiting){if(game.phase==="upgrade"&&dialogKind!=="upgrade"&&dialogKind!=="exit")showUpgrade();if(game.phase==="result"&&dialogKind!=="result"&&dialogKind!=="exit")showResult();}
if(ts-lastHud>=100){updateHud();lastHud=ts;}
}else simulation.reset();
metrics.updateMs=performance.now()-begun;
if(bannerUntil&&clock>bannerUntil){$("banner").style.opacity="0";bannerUntil=0;}
const fps=game?.phase==="playing"?budget.targetFPS:30;
if(ts-lastDraw>=1000/fps-1){const drawStart=performance.now();renderer.draw(clock,game,hero,joy);metrics.renderMs=performance.now()-drawStart;metrics.frames++;lastDraw=ts;}
requestAnimationFrame(frame);
}
$("world").addEventListener("pointerdown",e=>{if(!game||game.phase!=="playing"||joy.active)return;const b=$("world").getBoundingClientRect();joy.active=true;joy.id=e.pointerId;joy.ox=e.clientX-b.left;joy.oy=e.clientY-b.top;joy.x=joy.y=0;$("world").setPointerCapture(e.pointerId);$("move-hint").textContent="";audio.unlock();});
$("world").addEventListener("pointermove",e=>{if(!joy.active||e.pointerId!==joy.id)return;const b=$("world").getBoundingClientRect(),input=joystick(e.clientX-b.left,e.clientY-b.top,joy.ox,joy.oy);joy.ox=input.originX;joy.oy=input.originY;joy.x=input.x;joy.y=input.y;});
for(const event of ["pointerup","pointercancel","lostpointercapture"])$("world").addEventListener(event,e=>{if(e.pointerId===joy.id)resetInput();});
$("world").addEventListener("contextmenu",e=>e.preventDefault());$("dash").onclick=()=>game?.dash(joy.x,joy.y);$("ultimate").onclick=()=>game?.ultimate();$("pause").onclick=showPause;$("start").onclick=startGame;$("settings").onclick=()=>{audio.unlock();showSettings(false);};$("forge").onclick=showForge;$("help").onclick=showHelp;$("privacy").onclick=showPrivacy;
document.addEventListener("keydown",e=>{if(dialogKind){if(e.key==="Tab"){const buttons=[...$("dialog").querySelectorAll("button:not(:disabled)")];if(!buttons.length){e.preventDefault();return;}const first=buttons[0],end=buttons.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$("dialog"))){end.focus();e.preventDefault();}else if(!e.shiftKey&&(document.activeElement===end||document.activeElement===$("dialog"))){first.focus();e.preventDefault();}}if(e.key==="Escape"&&["help","forge","privacy","settings"].includes(dialogKind)){e.preventDefault();if(game)showPause();else hideModal();}return;}
if(game?.phase!=="playing")return;const k=e.key.toLowerCase();if(["w","a","s","d","arrowup","arrowdown","arrowleft","arrowright"," ","e","escape"].includes(k))e.preventDefault();keys.add(k);if(!e.repeat){if(k===" ")game.dash((keys.has("d")?1:0)-(keys.has("a")?1:0),(keys.has("s")?1:0)-(keys.has("w")?1:0));if(k==="e")game.ultimate();if(k==="escape")showPause();}});
document.addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
function background(){simulation.reset();last=0;resetInput();audio.stop();platform.awake(false);if(game?.phase==="playing")showPause();}
document.addEventListener("visibilitychange",()=>{if(document.hidden)background();});window.addEventListener("pagehide",()=>{background();});window.addEventListener("pageshow",()=>{last=0;simulation.reset();renderer.resize();});window.addEventListener("blur",()=>{if(game?.phase==="playing")background();});window.addEventListener("resize",()=>{renderer.resize();if(game){game.spawnDistance=Math.max(470,Math.min(650,renderer.h*.6));resetInput();}});
async function boot(){$("retry").hidden=true;$("boot-message").textContent="모험을 준비하고 있어요";try{save=await platform.init(requestExit);renderer.reduced=save.settings.reduced||window.matchMedia("(prefers-reduced-motion: reduce)").matches;audio.enabled=save.settings.sound;budget.set(save.settings.performance);renderer.setQuality(budget.scale);ready=true;renderHeroes();$("boot").classList.add("hidden");showHome();}catch{ready=false;$("boot-message").textContent="토스 연결을 확인해 주세요. 최신 토스 앱에서 다시 시도할 수 있어요.";$("retry").hidden=false;}}
$("retry").onclick=boot;
if(import.meta.env.DEV)window.__riftTest={get game(){return game;},metrics,budget,renderer,audio,simulation,get save(){return save;},giveXP:n=>game?.addXP(n),spawnBoss:()=>game?.spawnBoss(),finish:win=>game?.finish(win),requestExit,showSettings,showForge,async flush(){await platform.queue;}};
requestAnimationFrame(frame);boot();
