import "./style.css";
import {Game,HEROES,UPGRADES,EVOLUTIONS,cleanSave,purchase,reward,metaCost,upgradeDetail,CLASS_SKILLS} from "./core.js";
import {Platform} from "./platform.js";
import {Renderer,drawHero} from "./render.js";
import {Art} from "./art.js";
import {iconMarkup} from "./icons.js";
import {Audio} from "./audio.js";
import {FixedClock,RenderBudget,MovementStick} from "./runtime.js";
const $=id=>document.getElementById(id),platform=new Platform(),audio=new Audio(),renderer=new Renderer($("world"));
let save=cleanSave(),hero=HEROES[0],game=null,ready=false,settled=false,dialogKind=null,returnFocus=null,last=0,clock=0,bannerUntil=0,skillSignature="",exiting=false;
const simulation=new FixedClock(),budget=new RenderBudget(),metrics={frames:0,steps:0,frameMs:0,updateMs:0,renderMs:0};let lastDraw=0,lastHud=0;
const practiceParam=new URLSearchParams(location.search).get("practice"),practiceKey=UPGRADES[practiceParam]?.kind==="weapon"?practiceParam:null,practiceHero=Object.keys(CLASS_SKILLS).find(id=>CLASS_SKILLS[id].includes(practiceKey))||null,practiceTitle={blade:"검술 연습",arrow:"궁술 연습",bolt:"마법 연습"}[practiceKey]||(practiceKey?UPGRADES[practiceKey].name+" 연습":"전투 연습");if(practiceHero)hero=HEROES.find(h=>h.id===practiceHero);
const joy=new MovementStick(),keys=new Set();
const format=n=>Math.floor(n).toLocaleString("ko-KR"),timeText=n=>String(Math.floor(n/60)).padStart(2,"0")+":"+String(Math.floor(n%60)).padStart(2,"0");
function toast(text){$("toast").textContent=text;$("toast").classList.add("visible");clearTimeout(toast.timer);toast.timer=setTimeout(()=>$("toast").classList.remove("visible"),4000);}
platform.onSaveError=()=>toast("기록을 저장하지 못했어요. 앱을 닫기 전에 설정에서 다시 저장해 주세요.");
const persist=()=>platform.save(save);
function resetInput(){joy.reset();keys.clear();}
function modal(html,kind){resetInput();if(!dialogKind)returnFocus=document.activeElement;dialogKind=kind;$("dialog").innerHTML=html;$("overlay").classList.remove("hidden");$("dialog").focus();}
function hideModal(){dialogKind=null;$("overlay").classList.add("hidden");$("dialog").innerHTML="";if(returnFocus?.isConnected)returnFocus.focus();returnFocus=null;}
const heading=(eyebrow,title,desc)=>'<div class="eyebrow">'+eyebrow+'</div><h2 id="dialog-title">'+title+'</h2>'+(desc?'<p>'+desc+'</p>':"");
function updateHome(){$("coins").textContent=format(save.coins);$("best").textContent=format(save.best);$("wins").textContent=format(save.wins);$("hero-description").innerHTML='<strong>'+hero.role+'</strong><span>'+hero.tag+'</span>';for(const card of document.querySelectorAll(".hero")){const on=card.dataset.hero===hero.id;card.classList.toggle("selected",on);card.setAttribute("aria-pressed",String(on));card.querySelector(".check").textContent=on?"✓":"";}}
function showHome(){resetInput();game=null;exiting=false;settled=false;hideModal();$("home").classList.remove("hidden");$("hud").classList.add("hidden");platform.awake(false);updateHome();}
function renderHeroes(){$("heroes").innerHTML=HEROES.map(h=>'<button class="hero" data-hero="'+h.id+'" aria-pressed="false"><span class="check"></span><canvas width="128" height="132" aria-hidden="true"></canvas><strong>'+h.name+'</strong></button>').join("");for(const card of document.querySelectorAll(".hero")){if(practiceHero&&card.dataset.hero!==practiceHero)card.disabled=true;const h=HEROES.find(x=>x.id===card.dataset.hero),c=card.querySelector("canvas").getContext("2d");c.imageSmoothingEnabled=true;drawHero(c,h,64,86,2.8,1,0);card.onclick=()=>{hero=h;updateHome();audio.unlock();audio.event("select");};}}
function startGame(){if(!ready)return;simulation.reset();last=0;lastHud=0;budget.set(save.settings.performance);renderer.setQuality(budget.scale);audio.enabled=save.settings.sound;audio.unlock();hideModal();resetInput();settled=false;exiting=false;skillSignature="";game=new Game(practiceHero||hero.id,save.meta);if(practiceHero)game.enablePractice(practiceKey);game.hitStopEnabled=!renderer.reduced;renderer.feedback={shake:0,until:0,flash:0,swingUntil:0,swingAngle:0};if(!game.practice)game.spawnDistance=Math.max(330,Math.min(430,renderer.h*.46));$("home").classList.add("hidden");$("hud").classList.remove("hidden");$("bossbar").classList.add("hidden");platform.awake(true);banner(game.practice?practiceTitle+" · 15초":"별빛 유적 · 수호 시작",2.7);$("ultimate").querySelector("small").textContent=hero.ultimateName;$("ultimate").querySelector("span").innerHTML=iconMarkup(hero.weapon);$("ultimate").setAttribute("aria-label",hero.ultimateName+" · "+hero.ultimateDesc);$("move-hint").textContent="화면을 드래그해 이동";updateHud();}
function banner(text,seconds=2){$("banner").textContent=text;$("banner").style.opacity="1";bannerUntil=clock+seconds;}
function showUpgrade(){const choices=game.choices;modal(heading("LEVEL "+game.level,"어떤 힘을 키울까요?","직업 전용 기술과 성장 룬 중 하나를 선택하세요.")+'<div class="build-summary">무기 '+Object.keys(game.weapons).length+'/4 <span>진화 '+Object.keys(game.evolved).length+' · 균열 봉인 '+game.seals+'</span></div><div class="upgrade-list">'+choices.map((key,i)=>{
const original=UPGRADES[key],ev=EVOLUTIONS[key],u=(game.evolved[key]?{...original,name:ev.name,desc:ev.desc}:original)||{name:"회복의 빛",color:"#ffb5bc",desc:"체력을 회복해요"},d=upgradeDetail(game,key);
return '<button class="upgrade '+(d.evolves?'evolved':'')+'" data-choice="'+i+'"><span class="glyph" style="color:'+u.color+'">'+iconMarkup(key)+'</span><span class="upgrade-copy"><span class="choice-tag">'+(d.evolves?'진화 완성':d.recommended?'진화 연결':d.lv?'강화':'새로운 스킬')+'</span><strong>'+u.name+'</strong><small>'+d.stat+'</small><span class="skill-behavior">'+u.desc+'</span>'+(d.progress?'<em>'+d.progress+'</em>':'')+'<span class="level-dots" aria-hidden="true">'+Array.from({length:5},(_,j)=>'<i class="'+(j<d.lv?'filled':j===d.lv?'next':'')+'"></i>').join('')+'</span></span><span class="lv">'+(d.lv?'Lv.'+d.lv+' → '+d.next:'신규')+'</span></button>';
}).join("")+'</div><button id="reroll" class="secondary" '+(game.rerolls<=0?'disabled':'')+'>다시 뽑기 · '+game.rerolls+'회 남음</button><p class="tip">무기 Lv.5 + 연결 룬 Lv.2 → 진화<br>공격과 전투 시간은 선택하는 동안 멈춰요.</p>',"upgrade");
$("reroll").onclick=()=>{if(game.reroll())showUpgrade();};for(const b of document.querySelectorAll("[data-choice]"))b.onclick=()=>{if(game.choose(choices[Number(b.dataset.choice)])){audio.unlock();hideModal();if(game.phase==="upgrade")showUpgrade();}};}
function settleRun(){if(!game?.result||settled)return;settled=true;if(game.practice)return;save=reward(save,game.result);persist().catch(()=>{});}
function showResult(){settleRun();platform.awake(false);const r=game.result;if(game.practice){modal(heading("COMBAT PRACTICE",practiceTitle+" 완료","연습 보상과 점수는 저장되지 않아요.")+'<button id="again" class="primary">다시 연습하기</button><button id="practice-home" class="secondary">영웅 선택으로</button><a class="text-button practice-link" href="?v=2.0.0">생존 도전으로 이동</a>',"result");$("again").onclick=startGame;$("practice-home").onclick=showHome;return;}modal('<div class="result-symbol">'+(r.win?"✦":"◈")+'</div>'+heading(r.win?"RIFT CLOSED":"A NEW BEGINNING",r.win?"균열을 닫았어요!":"다음 도전은 더 강하게",r.win?"별빛이 숲으로 돌아왔어요. 수호자의 다음 모험을 준비해 보세요.":"모은 보석으로 영구 강화하면 다음 도전이 더 수월해져요.")+'<div class="stats"><div class="stat"><small>점수</small><b>'+format(r.score)+'</b></div><div class="stat"><small>처치한 적</small><b>'+format(r.kills)+'</b></div><div class="stat"><small>생존 시간</small><b>'+timeText(r.time)+'</b></div><div class="stat"><small>도달 레벨</small><b>'+r.level+'</b></div></div><div class="reward">균열 봉인 '+(r.seals||0)+'회 · 보석　◈ +'+r.coins+'</div><button id="again" class="primary">같은 영웅으로 다시 도전</button><button id="result-home" class="secondary">영웅 선택으로 돌아가기</button>',"result");$("again").onclick=startGame;$("result-home").onclick=showHome;}
function showPause(){if(!game)return;if(game.phase==="playing")game.pause();audio.stop();platform.awake(false);modal(heading("TAKE A BREATH","잠시 쉬어 가세요","도전은 멈춰 있어요. 준비되면 계속할 수 있어요.")+'<button id="resume" class="primary">도전 계속하기</button><button id="pause-settings" class="secondary">사운드 · 화면 설정</button><button id="retire" class="secondary">이번 도전 마치고 보상 받기</button><button id="pause-exit" class="text-button">미니앱 종료</button>',"pause");$("resume").onclick=()=>{hideModal();game.resume();audio.unlock();platform.awake(true);};$("pause-settings").onclick=()=>showSettings(true);$("retire").onclick=()=>{game.finish(false);showResult();};$("pause-exit").onclick=requestExit;}
function showSettings(fromGame=false){modal(heading("SETTINGS","내게 맞게 플레이","설정과 기록은 이 기기에 저장돼요.")+'<div class="setting-row"><span>배경음 · 효과음</span><button id="sound" class="toggle '+(save.settings.sound?"on":"")+'" aria-pressed="'+save.settings.sound+'">'+(save.settings.sound?"켜짐":"꺼짐")+'</button></div><div class="setting-row"><span>움직이는 효과 줄이기</span><button id="motion" class="toggle '+(save.settings.reduced?"on":"")+'" aria-pressed="'+save.settings.reduced+'">'+(save.settings.reduced?"켜짐":"꺼짐")+'</button></div><div class="setting-row"><span>화면 성능</span><button id="performance" class="toggle">'+({auto:"자동",smooth:"부드럽게",battery:"배터리 절약"}[save.settings.performance])+'</button></div><button id="save-retry" class="secondary">기록 저장 다시 시도</button><button id="settings-close" class="primary">'+(fromGame?"일시정지 화면으로":"영웅 선택으로")+'</button><button id="settings-exit" class="text-button">미니앱 종료</button>',"settings");
$("sound").onclick=()=>{save.settings.sound=!save.settings.sound;audio.set(save.settings.sound);if(fromGame)audio.stop();persist().catch(()=>{});showSettings(fromGame);};$("motion").onclick=()=>{save.settings.reduced=!save.settings.reduced;renderer.reduced=save.settings.reduced;if(game)game.hitStopEnabled=!renderer.reduced;persist().catch(()=>{});showSettings(fromGame);};$("performance").onclick=()=>{const modes=["auto","smooth","battery"];save.settings.performance=modes[(modes.indexOf(save.settings.performance)+1)%3];budget.set(save.settings.performance);renderer.setQuality(budget.scale);persist().catch(()=>{});showSettings(fromGame);};$("save-retry").onclick=async()=>{try{await persist();toast("기록을 저장했어요.");}catch{toast("저장이 완료되지 않았어요. 연결을 확인하고 다시 시도해 주세요.");}};$("settings-close").onclick=()=>{hideModal();if(fromGame)showPause();};$("settings-exit").onclick=requestExit;}
function showForge(){const defs={power:["공격의 룬","공격력 +6%"],heart:["생명의 룬","시작 체력 +10"],fortune:["인력의 룬","경험치 수집 범위 +8"]};modal(heading("THE RUNE FORGE","다음 모험을 위한 힘","도전 중 모은 보석으로 강화해요. 구매한 강화는 모든 영웅에게 계속 적용돼요.")+'<div class="reward">보유 보석　◈ '+format(save.coins)+'</div>'+Object.entries(defs).map(([key,[name,desc]])=>{const lv=save.meta[key],cost=metaCost(lv);return '<div class="forge-row"><span><strong>'+name+' · '+lv+'/5</strong><small>'+desc+' / 단계</small></span><button data-forge="'+key+'" '+(lv>=5||save.coins<cost?"disabled":"")+'>'+(lv>=5?"최대 강화":"◈ "+cost)+'</button></div>';}).join("")+'<p class="tip">보석은 플레이로만 얻어요. 실제 돈으로 결제하는 기능은 없어요.</p><button id="forge-close" class="primary">영웅 선택으로</button>',"forge");for(const b of document.querySelectorAll("[data-forge]"))b.onclick=()=>{const r=purchase(save,b.dataset.forge);if(r.ok){save=r.save;persist().catch(()=>{});audio.unlock();audio.event("choose");updateHome();showForge();}};$("forge-close").onclick=hideModal;}
function showSkillBook(){modal(heading("CLASS SKILLS",hero.name+"의 전투 기술","전용 공격 6종 · 전투 중 최대 4종 장착")+'<div class="skill-codex">'+CLASS_SKILLS[hero.id].map(key=>{const u=UPGRADES[key],ev=EVOLUTIONS[key];return '<article><span class="glyph" style="color:'+u.color+'">'+iconMarkup(key)+'</span><div><strong>'+u.name+'</strong><p>'+u.desc+'</p><small>Lv.5 + '+UPGRADES[ev.passive].name+' Lv.2 → '+ev.name+'</small></div></article>';}).join("")+'</div><p class="tip">성장 룬 8종: 피해 · 공격 속도 · 이동 · 체력 · 수집 · 치명타 · 흡혈 · 영역 확장<br>레벨업할 때 네 가지 선택이 나오고, 새 기술을 배울 자리가 있으면 전용 기술이 하나 이상 등장해요.</p><button id="skill-book-close" class="primary">확인</button>',"skill-book");$("skill-book-close").onclick=hideModal;}

function showHelp(){modal(heading("HOW TO PLAY","5분 뒤, 균열의 군주를 만나세요","복잡한 조작 없이 이동과 선택에 집중하세요.")+'<div class="help-step"><b>1</b><p>전장 아무 곳이나 드래그해 이동해요. 공격은 자동으로 나가요.</p></div><div class="help-step"><b>2</b><p>초록 경험치를 모아요. 레벨이 오르면 스킬 하나를 선택해요. 무기 Lv.5와 연결된 룬 Lv.2를 모으면 진화해요.</p></div><div class="help-step"><b>3</b><p>회피로 위험에서 벗어나세요. 기사·궁수·마법사는 서로 다른 필살기를 사용해요.</p></div><div class="help-step"><b>4</b><p>보라색 균열 안에 3초 머물러 봉인하면 경험치·회복·필살기 재충전을 얻어요. 주황색 돌진 예고와 적 탄환을 피하고 5분 뒤 보스를 물리치세요.</p></div><p class="tip">PC: WASD/방향키 이동 · Space 회피 · E 궁극기 · Esc 일시정지</p><button id="help-close" class="primary">알겠어요</button>',"help");$("help-close").onclick=hideModal;}
function showPrivacy(){modal(heading("GAME INFORMATION","게임과 데이터 안내","균열의 수호자 · 버전 2.0.0")+'<div class="privacy"><h3>어떤 게임인가요?</h3><p>세 영웅의 스킬을 조합해 별빛 유적을 지키는 2D 생존 액션이에요. 손그림풍 캐릭터와 유적 배경, 금빛 룬 참격과 녹음 효과음으로 전투를 표현해요.</p><h3>어떤 정보를 저장하나요?</h3><p>토스 익명 식별키를 이용해 이 기기에 점수, 보석, 강화와 설정을 저장해요. 이름, 연락처, 위치는 요청하지 않으며 별도 서버로 전송하지 않아요.</p><h3>기록은 어디에 남나요?</h3><p>기기 안의 토스 저장소에 남아요. 기기를 바꾸거나 미니앱 데이터를 삭제하면 기록이 이어지지 않을 수 있어요.</p><h3>제작 크레딧</h3><p>휘두름: artisticdude · RPG Audio: Kenney (CC0). 판타지 효과음: <a href="https://littlerobotsoundfactory.com" target="_blank" rel="noopener">Little Robot Sound Factory</a> · <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noopener">CC BY 3.0</a>. 게임에 맞게 편집·혼합했어요. 제목 글꼴: Noto Serif KR (SIL OFL).</p><h3>문의하기</h3><p>토스 우측 상단 더보기의 문의하기를 이용해 주세요.</p></div><button id="privacy-close" class="primary">닫기</button>',"privacy");$("privacy-close").onclick=hideModal;}
function requestExit(){if(!ready)return;const active=game&&!game.result,before=game?.phase;if(game?.phase==="playing")game.pause();resetInput();audio.stop();platform.awake(false);modal(heading("LEAVE THE RIFT","미니앱을 종료할까요?",active?"이번 도전은 종료돼요. 지금까지 획득한 보상을 저장한 뒤 나가요.":"점수, 보석과 강화는 이 기기에 저장돼요.")+'<button id="exit-cancel" class="primary">계속 머무르기</button><button id="exit-confirm" class="secondary">저장하고 종료</button>',"exit");$("exit-cancel").onclick=()=>{hideModal();if(game){if(before==="upgrade")showUpgrade();else if(game.result)showResult();else showPause();}else audio.unlock();};
$("exit-confirm").onclick=async()=>{const b=$("exit-confirm");b.disabled=true;b.textContent="기록을 저장하고 있어요";exiting=true;try{if(game&&!game.result)game.finish(false);settleRun();await persist();await platform.close();if(import.meta.env.DEV)showHome();}catch{exiting=false;b.disabled=false;b.textContent="저장하고 종료";toast("저장을 완료하지 못했어요. 다시 시도해 주세요.");}};}
function updateHud(){if(!game)return;const p=game.player;$("hptext").textContent=Math.ceil(p.hp)+" / "+p.maxHp;$("hpbar").style.width=(p.hp/p.maxHp*100)+"%";$("level").textContent="Lv. "+game.level;$("xpbar").style.width=(game.xp/game.need*100)+"%";$("time").textContent=timeText(game.time);$("kills").textContent=format(game.kills);$("objective").textContent=game.practice?"15초 "+practiceTitle:game.bossSpawned?"군주를 처치하세요":timeText(Math.max(0,300-game.time))+" 후 군주 출현";
$("chapter").textContent=game.practice?"TRAINING":["01 · 별빛 유적","02 · 날개 군단","03 · 뒤틀린 수호자","04 · 저주받은 숲","05 · 마지막 저항"][game.chapter];
$("run-progress").style.width=Math.min(100,game.time/300*100)+"%";const r=game.rift;$("encounter").classList.toggle("hidden",!r);if(r){$("rift-progress").style.width=r.progress/3*100+"%";$("rift-status").textContent=r.progress>0?"봉인 "+Math.floor(r.progress/3*100)+"%":"균열 안에 3초 머물기";$("rift-time").textContent=Math.ceil(r.life)+"초";}const boss=game.enemies.find(e=>e.boss);$("bossbar").classList.toggle("hidden",!boss);if(boss)$("bossfill").style.width=Math.max(0,boss.hp/boss.maxHp*100)+"%";
for(const [id,cd]of [["dash",p.dashCd],["ultimate",p.ultCd]]){const b=$(id);b.querySelector("b").textContent=cd>0?String(Math.ceil(cd)):"";b.style.setProperty("--cool",String(cd/(id==="dash"?5:32)));b.classList.toggle("ready",cd<=0);b.disabled=cd>0||game.phase!=="playing";}const sig=JSON.stringify([game.weapons,game.evolved]);if(sig!==skillSignature){skillSignature=sig;$("skills").innerHTML=Object.entries(game.weapons).map(([k,lv])=>'<span class="skill" style="color:'+UPGRADES[k].color+'" aria-label="'+(game.evolved[k]?EVOLUTIONS[k].name:UPGRADES[k].name)+' '+lv+'레벨">'+iconMarkup(k)+'<small>'+(game.evolved[k]?'✦':lv)+'</small></span>').join("");}}
function frame(ts){
const elapsed=last?Math.max(0,(ts-last)/1000):0;last=ts;clock=ts/1000;metrics.frameMs=elapsed*1000;
if(document.hidden){simulation.reset();requestAnimationFrame(frame);return;}
if(game?.phase==="playing"&&budget.observe(elapsed*1000))renderer.setQuality(budget.scale);
const begun=performance.now();
if(game){let x=joy.x,y=joy.y;const kx=(keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0),ky=(keys.has("s")||keys.has("arrowdown")?1:0)-(keys.has("w")||keys.has("arrowup")?1:0);joy.keyboard=!!(kx||ky)&&!joy.active;if(joy.keyboard){x=kx;y=ky;}
metrics.steps+=simulation.advance(elapsed,dt=>game.step(dt,{x,y}),()=>game?.phase==="playing");
for(const e of game.events.splice(0)){audio.event(e.type,e.key,e);renderer.react(e,game);if(e.type==="rift-open")banner("균열 개방 · 원 안에 3초 머물기",2);if(e.type==="rift-sealed")banner("봉인 완료 · 회복 + 필살기 재충전",2.3);if(e.type==="chapter")banner(["","날개 군단이 몰려옵니다","뒤틀린 수호자의 습격","저주의 기운이 짙어집니다","마지막 저항 · 군주를 준비하세요"][e.chapter],2.2);if(e.type==="boss")banner("균열의 군주가 깨어났어요",3);if(e.type==="elite")banner("강력한 적이 나타났어요",2);if(e.type==="evolve")banner(e.name+" · 진화!",2.5);if(e.type==="chest")banner("정예 보상 · 경험치와 회복",1.8);if(e.type==="magnet")banner("모든 경험치를 끌어당겨요",1.8);if(e.type==="supply")banner("푸른 인력 상자가 나타났어요",1.8);}
if(!exiting){if(game.phase==="upgrade"&&dialogKind!=="upgrade"&&dialogKind!=="exit")showUpgrade();if(game.phase==="result"&&dialogKind!=="result"&&dialogKind!=="exit")showResult();}
if(ts-lastHud>=100){updateHud();lastHud=ts;}
}else simulation.reset();
metrics.updateMs=performance.now()-begun;
if(bannerUntil&&clock>bannerUntil){$("banner").style.opacity="0";bannerUntil=0;}
const fps=game?.phase==="playing"?budget.targetFPS:30;
if(ts-lastDraw>=1000/fps-1){const drawStart=performance.now();renderer.draw(clock,game,hero,joy);metrics.renderMs=performance.now()-drawStart;metrics.frames++;lastDraw=ts;}
requestAnimationFrame(frame);
}

const world=$("world"),touchInput="TouchEvent" in window;
function beginMovement(source,id,x,y){if(game?.phase!=="playing"||!joy.begin(source,id,x,y,world.getBoundingClientRect()))return false;keys.clear();joy.keyboard=false;$("move-hint").textContent="";audio.unlock();return true;}
function moveMovement(source,id,x,y){return joy.move(source,id,x,y,world.getBoundingClientRect());}
function endMovement(source,id){if(joy.end(source,id))keys.clear();}
world.addEventListener("pointerdown",e=>{if(e.pointerType==="touch"&&touchInput)return;if(beginMovement("pointer",e.pointerId,e.clientX,e.clientY)){if(e.cancelable)e.preventDefault();try{world.setPointerCapture(e.pointerId);}catch{}}});
window.addEventListener("pointermove",e=>moveMovement("pointer",e.pointerId,e.clientX,e.clientY));
for(const type of ["pointerup","pointercancel"])window.addEventListener(type,e=>endMovement("pointer",e.pointerId));
world.addEventListener("lostpointercapture",e=>endMovement("pointer",e.pointerId));
// Phones use the owning touch identifier; other fingers and compatibility pointer events cannot steal movement.
world.addEventListener("touchstart",e=>{const t=e.changedTouches[0];if(t&&beginMovement("touch",t.identifier,t.clientX,t.clientY)&&e.cancelable)e.preventDefault();},{passive:false});
window.addEventListener("touchmove",e=>{for(const t of e.changedTouches)if(moveMovement("touch",t.identifier,t.clientX,t.clientY)){if(e.cancelable)e.preventDefault();break;}},{passive:false});
for(const type of ["touchend","touchcancel"])window.addEventListener(type,e=>{for(const t of e.changedTouches)endMovement("touch",t.identifier);});
$("world").addEventListener("contextmenu",e=>e.preventDefault());const actions={dash:()=>game?.dash(joy.x,joy.y),ultimate:()=>game?.ultimate()};for(const [id,action]of Object.entries(actions)){$(id).onclick=action;$(id).addEventListener("pointerdown",e=>{if(e.pointerType==="touch"){e.preventDefault();audio.unlock();action();}});}$("pause").onclick=showPause;$("start").onclick=startGame;$("settings").onclick=()=>{audio.unlock();showSettings(false);};$("forge").onclick=showForge;$("help").onclick=showHelp;$("skill-book").onclick=showSkillBook;$("privacy").onclick=showPrivacy;
document.addEventListener("keydown",e=>{if(dialogKind){if(e.key==="Tab"){const buttons=[...$("dialog").querySelectorAll("button:not(:disabled)")];if(!buttons.length){e.preventDefault();return;}const first=buttons[0],end=buttons.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===$("dialog"))){end.focus();e.preventDefault();}else if(!e.shiftKey&&(document.activeElement===end||document.activeElement===$("dialog"))){first.focus();e.preventDefault();}}if(e.key==="Escape"&&["help","forge","privacy","settings","skill-book"].includes(dialogKind)){e.preventDefault();if(game)showPause();else hideModal();}return;}
if(game?.phase!=="playing")return;const k=e.key.toLowerCase();if(["w","a","s","d","arrowup","arrowdown","arrowleft","arrowright"," ","e","escape"].includes(k))e.preventDefault();keys.add(k);if(!e.repeat){if(k===" ")game.dash((keys.has("d")?1:0)-(keys.has("a")?1:0),(keys.has("s")?1:0)-(keys.has("w")?1:0));if(k==="e")game.ultimate();if(k==="escape")showPause();}});
document.addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));
function background(){simulation.reset();last=0;resetInput();audio.stop();platform.awake(false);if(game?.phase==="playing")showPause();}
document.addEventListener("visibilitychange",()=>{if(document.hidden)background();});window.addEventListener("pagehide",()=>{background();});window.addEventListener("pageshow",()=>{last=0;simulation.reset();renderer.resize();});window.addEventListener("blur",()=>{keys.clear();joy.keyboard=false;if(document.hidden&&game?.phase==="playing")background();});window.addEventListener("resize",()=>{renderer.resize();if(game){if(!game.practice)game.spawnDistance=Math.max(330,Math.min(430,renderer.h*.46));if(joy.active)joy.rebase(world.getBoundingClientRect());}});
async function boot(){$("retry").hidden=true;$("boot-message").textContent="모험을 준비하고 있어요";try{const loaded=await Promise.all([platform.init(requestExit),Art.load(),audio.prepare()]);save=loaded[0];renderer.makeGround();renderer.resize();renderer.reduced=save.settings.reduced||window.matchMedia("(prefers-reduced-motion: reduce)").matches;audio.enabled=save.settings.sound;budget.set(save.settings.performance);renderer.setQuality(budget.scale);ready=true;renderHeroes();$("boot").classList.add("hidden");showHome();if(practiceHero){$("start").firstChild.textContent=practiceTitle+" 시작 ";$("hero-description").textContent=hero.name+"의 움직임과 타격을 15초 동안 연습해요";}}catch{ready=false;$("boot-message").textContent="게임을 불러오지 못했어요. 연결을 확인하고 다시 시도해 주세요.";$("retry").hidden=false;}}
$("retry").onclick=boot;
if(import.meta.env.DEV)window.__riftTest={get game(){return game;},input:joy,metrics,budget,renderer,audio,simulation,get save(){return save;},giveXP:n=>game?.addXP(n),spawnBoss:()=>game?.spawnBoss(),finish:win=>game?.finish(win),requestExit,showSettings,showForge,async flush(){await platform.queue;}};
for(const [id,key]of [["dash","dash"],["ultimate","ultimate"]])$(id).querySelector("span").innerHTML=iconMarkup(key);$("settings").innerHTML=iconMarkup("settings");$("pause").innerHTML=iconMarkup("pause");
requestAnimationFrame(frame);boot();
