import {UPGRADES,BLADE_TIMING,RANGED_TIMING} from "./core.js";
import {Art,drawSprite} from "./art.js";
const clampRender=n=>Math.max(0,Math.min(1,n));
const TAU=Math.PI*2,hash=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n);};
function ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,TAU);c.fill();}
function star(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.moveTo(x,y-r);c.lineTo(x+r*.27,y-r*.27);c.lineTo(x+r,y);c.lineTo(x+r*.27,y+r*.27);c.lineTo(x,y+r);c.lineTo(x-r*.27,y+r*.27);c.lineTo(x-r,y);c.lineTo(x-r*.27,y-r*.27);c.closePath();c.fill();}
export function drawHero(c,h,x,y,scale=2,face=1,t=0,moving=false,attack=false,flash=0,swing=null,motion=true,gaitPhase=null){
const phase=gaitPhase??t*2;
if(moving&&swing){
 const left=x-scale*14,hip=y-scale*6,width=scale*28,legs=scale*25;
 c.save();c.beginPath();c.rect(x-scale*100,y-scale*100,scale*200,scale*200);c.rect(left,hip,width,legs);c.clip("evenodd");
 drawHeroPose(c,h,x,y,scale,face,t,moving,attack,flash,swing,motion,phase);c.restore();
 c.save();c.beginPath();c.rect(left,hip,width,legs);c.clip();
 drawHeroPose(c,h,x,y,scale,face,t,moving,false,flash,null,motion,phase);c.restore();return;
}
drawHeroPose(c,h,x,y,scale,face,t,moving,attack,flash,swing,motion,phase);
}
function drawHeroPose(c,h,x,y,scale,face,t,moving,attack,flash,swing,motion,phase){
const height=scale*34,bob=moving?-Math.abs(Math.sin(phase*TAU*2))*scale*.6:Math.sin(t*2)*.65;
if(h.id==="knight"&&moving&&!swing&&scale<4){drawSprite(c,Math.floor(phase*2)%2?"knight-walk-b":"knight-walk-a",x,y+bob,scale*46,face,flash,Math.sin(phase*TAU)*.016);return;}
ellipse(c,x,y+height*.18,height*.24,height*.09,"#010e0baa");
if(h.id==="knight"&&scale<4&&Art.images.has("knight-strike-0")){let index=0,lean=0,lunge=0;if(swing){const age=swing.elapsed;index=age<.025?0:age<.06?1:age<.09?2:age<.14?3:age<.19?4:age<.255?5:age<.31?6:7;lean=age<.09?-.035:age<.20?.04:0;lunge=age<.09?-2:age<.20?4:1;}const sprite=Art.sprite("knight-strike-"+index),poseHeight=scale*58,poseWidth=poseHeight*sprite.width/sprite.height;
c.save();c.translate(x+lunge*face,y+bob);c.scale(face,1);c.rotate(lean);const top=poseHeight*(.18-256/296);if(swing&&motion&&swing.elapsed>=.10&&swing.elapsed<.18){c.save();c.globalAlpha*=.11;const trail=Art.sprite("knight-strike-3");c.drawImage(trail.image,-poseWidth/2-5,top,poseWidth,poseHeight);c.restore();}c.drawImage(sprite.image,-poseWidth/2,top,poseWidth,poseHeight);if(flash>0){c.globalAlpha*=Math.min(.3,flash);c.drawImage(sprite.flash,-poseWidth/2,top,poseWidth,poseHeight);}c.restore();return;}
if(["ranger","mage"].includes(h.id)&&scale<2.7&&Art.images.has(h.id+"-attack-0")){const key=h.weapon,age=swing?swing.elapsed/swing.tempo:0,stages=key==="arrow"?[.025,.060,.10,.13,.19,.27,.35]:[.040,.090,.15,.20,.29,.39,.48];let index=0;if(swing){index=stages.findIndex(n=>age<n);if(index<0)index=7;}const name=swing?h.id+"-attack-"+index:moving?h.id+"-walk-"+(Math.floor(phase*4)%4):h.id+"-attack-0",sprite=Art.sprite(name),poseHeight=scale*52,poseWidth=poseHeight*sprite.width/sprite.height,release=RANGED_TIMING[key].release,follow=swing&&age>=release?Math.max(0,1-(age-release)/.12):0;
c.save();c.translate(x-follow*2.5*face,y+bob);c.scale(face,1);c.rotate(swing?(age<release?-.018:.022*follow):moving?Math.sin(phase*TAU)*.012:0);const top=poseHeight*(.18-256/296);c.drawImage(sprite.image,-poseWidth/2,top,poseWidth,poseHeight);if(flash>0){c.globalAlpha*=Math.min(.3,flash);c.drawImage(sprite.flash,-poseWidth/2,top,poseWidth,poseHeight);}c.restore();return;}
const frame=h.id==="knight"?(attack?"knight-attack":moving?(Math.floor(t*10)%2?"knight-walk-a":"knight-walk-b"):"knight-idle"):h.id;
drawSprite(c,frame,x,y+bob,height,face,flash,moving?Math.sin(t*10)*.025:0);
}
export class Renderer{
constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext("2d",{alpha:false});this.reduced=false;this.quality=1;this.visible=[];this.artReady=false;this.zoom=1.12;this.groves=[[80,120,240,1],[1690,120,240,-1],[80,1680,250,1],[1690,1680,250,-1],[60,850,230,1],[1740,900,230,-1]];this.feedback={shake:0,until:0,flash:0,swingUntil:0,swingAngle:0};this.makeGround();this.makeEffects();this.resize();}
setQuality(scale){if(Math.abs(this.quality-scale)<.01)return;this.quality=scale;this.resize();}
makeGround(){const tile=document.createElement("canvas");tile.width=tile.height=768;const c=tile.getContext("2d"),image=Art.images.get("courtyard");if(image){c.drawImage(image,0,0,768,768);c.fillStyle="#0a192c28";c.fillRect(0,0,768,768);this.artReady=true;}else{c.fillStyle="#16382e";c.fillRect(0,0,768,768);}this.tile=tile;this.pattern=this.ctx.createPattern(tile,"repeat");}
makeEffects(){
this.glows={};for(const [key,color]of Object.entries({gold:"#ffe7a0",mint:"#95f8c5",blue:"#b5eaff",violet:"#d89bff",red:"#ffaca0"})){const tile=document.createElement("canvas");tile.width=tile.height=96;const c=tile.getContext("2d"),g=c.createRadialGradient(48,48,0,48,48,48);g.addColorStop(0,color+"b0");g.addColorStop(.22,color+"65");g.addColorStop(.6,color+"22");g.addColorStop(1,color+"00");c.fillStyle=g;c.fillRect(0,0,96,96);this.glows[key]=tile;}
const tile=document.createElement("canvas");tile.width=tile.height=384;const c=tile.getContext("2d");c.translate(192,192);const g=c.createLinearGradient(10,-140,155,125);g.addColorStop(0,"#f6b54700");g.addColorStop(.24,"#e4a84490");g.addColorStop(.7,"#ffe59fff");g.addColorStop(1,"#fffbeeff");c.fillStyle=g;c.beginPath();c.arc(0,0,158,-1.6,1.1);c.arc(0,0,130,1.1,-1.6,true);c.closePath();c.shadowColor="#ffc66d";c.shadowBlur=18;c.fill();c.shadowBlur=0;c.strokeStyle="#fff6d4";c.lineWidth=4;c.beginPath();c.arc(0,0,158,-.85,1.08);c.stroke();c.strokeStyle="#ffcb6c88";c.lineWidth=2;c.beginPath();c.arc(0,0,118,-1.2,1);c.stroke();for(let i=0;i<6;i++){const a=-1.05+i*.36;star(c,Math.cos(a)*125,Math.sin(a)*125,4,"#fff0bfbb");}this.slashTile=tile;
}
resize(){const b=this.canvas.getBoundingClientRect();this.w=Math.max(1,b.width);this.h=Math.max(1,b.height);const d=Math.min(window.devicePixelRatio||1,2)*this.quality;this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.ctx.setTransform(d,0,0,d,0,0);this.ctx.imageSmoothingEnabled=true;this.pattern=this.ctx.createPattern(this.tile,"repeat");this.vignette=this.ctx.createRadialGradient(this.w/2,this.h*.48,Math.min(this.w,this.h)*.16,this.w/2,this.h*.48,Math.max(this.w,this.h)*.65);this.vignette.addColorStop(0,"#04191000");this.vignette.addColorStop(.65,"#09162014");this.vignette.addColorStop(1,"#06101c99");}
circle(x,y,r,color,stroke){const c=this.ctx;c.beginPath();c.arc(x,y,r,0,TAU);if(color){c.fillStyle=color;c.fill();}if(stroke){c.strokeStyle=stroke;c.stroke();}}
glow(x,y,size,key="gold",alpha=1){const c=this.ctx;c.save();c.globalAlpha*=alpha;c.drawImage(this.glows[key],x-size/2,y-size/2,size,size);c.restore();}
react(e,g){if(!g)return;const f=this.feedback,t=g.time;if(e.type==="blade-windup"){f.swingUntil=t+BLADE_TIMING.duration;f.swingAngle=e.angle;}if(e.type==="skill-impact"){f.shake=Math.max(f.shake,e.key==="meteor"?3.5:e.key==="slam"?2.6:1.4);f.until=t+.13;}if(e.type==="skill-release"&&e.key==="lightning"){f.shake=Math.max(f.shake,1.6);f.until=t+.1;f.flash=t+.06;}if(e.type==="blade-contact"){f.shake=Math.max(f.shake,e.strong?2.6:1.5);f.until=t+.075;f.contact=t;f.combo=e.id;}
if(e.type==="projectile-contact"){f.shake=Math.max(f.shake,e.key==="arrow"?.7:e.evolved?1.8:1.15);f.until=t+.06;f.projectileContact=t;f.projectileKey=e.key;}
if(e.type==="impact"&&e.strong){f.shake=Math.max(f.shake,2.5);f.until=t+.085;}if(e.type==="hurt"){f.shake=4;f.until=t+.13;f.flash=t+.1;}if(e.type==="ultimate"){f.shake=e.key==="blade"?5:3;f.until=t+.18;f.flash=t+.055;}if(e.type==="rift-sealed"){f.shake=2;f.until=t+.12;}}
ground(cx,cy,t,zoom=1){const c=this.ctx,w=this.w,h=this.h;c.fillStyle="#16382e";c.fillRect(0,0,w,h);c.save();c.translate(w/2,h/2);c.scale(zoom,zoom);c.translate(-cx,-cy);c.fillStyle=this.pattern;c.fillRect(cx-w/(2*zoom),cy-h/(2*zoom),w/zoom,h/zoom);c.strokeStyle="#b7cbd528";c.lineWidth=2;for(const r of [115,135]){c.beginPath();c.arc(900,900,r,0,TAU);c.stroke();}for(let i=0;i<8;i++){const a=i*TAU/8;star(c,900+Math.cos(a)*125,900+Math.sin(a)*125,5,"#c3d1df44");}
for(const [x,y]of [[350,350],[1450,350],[350,1450],[1450,1450],[900,1700],[120,900],[1680,900]]){if(Math.abs(x-cx)>w/2+60||Math.abs(y-cy)>h/2+100)continue;ellipse(c,x,y+20,25,10,"#01171088");drawSprite(c,"ruin",x,y,90);this.glow(x,y-30,48,"mint",.25);}
c.fillStyle="#031713";c.fillRect(-300,-300,2400,300);c.fillRect(-300,1800,2400,300);c.fillRect(-300,0,300,1800);c.fillRect(1800,0,300,1800);c.strokeStyle="#83925d55";c.lineWidth=6;c.strokeRect(10,10,1780,1780);c.restore();
if(!this.reduced&&this.quality>.7)for(let i=0;i<9;i++){const x=(hash(i,9)*w+t*(i%3+1)*2)%(w+20)-10,y=(hash(i,4)*h-t*1.4)%(h+20);this.circle(x,y,1.2,"#ddeea8"+(i%2?"45":"88"));}}
enemy(e,t,p){const c=this.ctx,flash=Math.max(0,e.flash/.12),away=Math.atan2(e.y-p.y,e.x-p.x),recoil=flash*5,x=e.x+Math.cos(away)*recoil,y=e.y+Math.sin(away)*recoil;
const height=e.boss?170:e.kind==="brute"?(e.elite?100:80):e.kind==="bat"?48:e.kind==="seer"?70:58;
ellipse(c,x,y+height*.18,height*.26,height*.10,e.boss?"#0a080eb0":"#020b0b88");
if(e.boss){this.glow(x,y-20,120,"violet",.32);c.lineWidth=1;this.circle(x,y,55,null,"#d099df55");}
const bob=e.kind==="bat"?Math.sin(t*12+e.id)*3:Math.sin(t*7+e.id)*.6;
drawSprite(c,e.boss?"boss":e.kind,x,y+bob,height,p.x>=e.x?1:-1,flash*(["blade","arrow","bolt"].includes(e.hitKind)?.20:.32),Math.sin(t*7+e.id)*.015+flash*.07);
if(e.slow>0){c.strokeStyle="#c5f3ff99";c.lineWidth=1;c.beginPath();c.arc(x,y,Math.max(15,e.r+3),0,TAU);c.stroke();}
if((e.elite||e.flash>0||e.hp<e.maxHp)&&!e.boss){c.lineWidth=2;if(e.elite)this.circle(x,y,e.r+5,null,"#e8c37d88");c.fillStyle="#0a0f14cc";c.fillRect(x-20,y-height*.65,40,3);c.fillStyle=e.elite?"#f8cc79":"#c38fce";c.fillRect(x-20,y-height*.65,40*Math.max(0,e.hp/e.maxHp),3);}}
projectile(b,enemy=false){const c=this.ctx,angle=Math.atan2(b.vy,b.vx);c.save();c.translate(b.x,b.y-(enemy?0:24));c.rotate(angle);
if(enemy){this.glow(0,0,25,"violet",.9);ellipse(c,0,0,b.r+1,b.r+1,"#ca72ee");ellipse(c,1,-1,2.4,2.4,"#fff0ff");}
else if(b.key==="fireball"){this.glow(-5,0,75,"red",.85);c.fillStyle="#f5773745";c.beginPath();c.moveTo(-65,0);c.quadraticCurveTo(-20,-20,14,-8);c.quadraticCurveTo(25,0,14,8);c.quadraticCurveTo(-20,20,-65,0);c.fill();for(let i=0;i<4;i++){ellipse(c,-i*11,Math.sin(b.ttl*18+i)*4,12-i*2.2,9-i*1.6,i?"#ff9438aa":"#ffe7ad");}ellipse(c,4,-2,6,5,"#fff3d4");}
else if(b.key==="cleave"){this.glow(0,0,80,"gold",.55);c.strokeStyle="#a86e3955";c.lineWidth=18;c.beginPath();c.arc(-20,0,b.r*1.7,-1.1,1.1);c.stroke();c.strokeStyle="#f4c77e";c.lineWidth=9;c.stroke();c.strokeStyle="#fff5d4";c.lineWidth=2;c.beginPath();c.arc(-20,0,b.r*1.7+4,-1,1);c.stroke();}
else if(b.key==="nova"){this.glow(-5,0,35,"blue",.6);c.fillStyle="#72bceba0";c.beginPath();c.moveTo(18,0);c.lineTo(-9,-6);c.lineTo(-5,0);c.lineTo(-9,6);c.closePath();c.fill();c.strokeStyle="#e5faff";c.lineWidth=1;c.beginPath();c.moveTo(-5,0);c.lineTo(18,0);c.stroke();}
else if(["arrow","multishot","piercing","poison"].includes(b.key)){this.glow(2,0,b.key==="piercing"?50:b.evolved?42:29,"mint",b.key==="poison"?.62:b.evolved?.58:.30);if(b.key==="piercing"){c.strokeStyle="#e9ffc799";c.lineWidth=3;c.beginPath();c.moveTo(-66,0);c.lineTo(-6,0);c.stroke();}if(b.key==="poison"){c.fillStyle="#9edd5460";ellipse(c,-7,0,17,7,"#9edd5460");if(!this.reduced)for(let i=0;i<3;i++)ellipse(c,-22-i*10,Math.sin(b.ttl*15+i)*5,2,2,"#d4f992");}c.fillStyle=b.evolved?"#9ff8cd70":"#7be2ac50";c.beginPath();c.moveTo(-45,0);c.lineTo(-8,-3);c.lineTo(7,0);c.lineTo(-8,3);c.closePath();c.fill();c.strokeStyle="#c49c64";c.lineWidth=2;c.beginPath();c.moveTo(-21,0);c.lineTo(7,0);c.stroke();c.strokeStyle="#fff6d4";c.lineWidth=1;c.beginPath();c.moveTo(-19,-1);c.lineTo(6,-1);c.stroke();c.strokeStyle="#bdecc1";c.lineWidth=1.2;for(const side of [-1,1]){c.beginPath();c.moveTo(-19,0);c.lineTo(-24,side*4);c.lineTo(-16,side*2);c.stroke();}c.fillStyle="#f1ffe0";c.beginPath();c.moveTo(12,0);c.lineTo(3,-4);c.lineTo(5,0);c.lineTo(3,4);c.closePath();c.fill();if(!this.reduced&&this.quality>.7){star(c,-29,-2,1.5,"#c9ffe3");if(b.evolved){c.strokeStyle="#bdffe9aa";c.lineWidth=1;c.beginPath();c.moveTo(-44,-5);c.lineTo(-8,-2);c.moveTo(-44,5);c.lineTo(-8,2);c.stroke();star(c,8,0,5,"#f2ffe7");}}}
else{const evo=b.evolved,tail=evo?62:44;this.glow(0,0,evo?74:52,"blue",.62);c.fillStyle="#73c9f05c";c.beginPath();c.moveTo(-tail,0);c.lineTo(-13,-7);c.lineTo(18,0);c.lineTo(-13,7);c.closePath();c.fill();c.fillStyle="#5197d7";c.beginPath();c.moveTo(-18,0);c.lineTo(-3,-(evo?8:5));c.lineTo(evo?25:18,0);c.lineTo(-3,evo?8:5);c.closePath();c.fill();c.fillStyle="#e0faff";c.beginPath();c.moveTo(-13,0);c.lineTo(0,-2.7);c.lineTo(evo?25:18,0);c.lineTo(0,2.7);c.closePath();c.fill();if(!this.reduced&&this.quality>.7){const age=1.8-b.ttl;for(let i=0;i<3;i++){const x=-17-i*12,y=Math.sin(age*16+i*2)*5;star(c,x,y,2.0-i*.35,"#bdefffbb");}if(evo){c.strokeStyle="#b4e4ffbb";c.lineWidth=1;c.beginPath();c.moveTo(-44,-8);c.lineTo(-2,-4);c.lineTo(20,0);c.moveTo(-44,8);c.lineTo(-2,4);c.lineTo(20,0);c.stroke();}}}c.restore();}

effect(f,t,g){const c=this.ctx,a=Math.max(0,f.ttl/f.max),progress=1-a;c.save();c.globalAlpha=a;c.strokeStyle=f.color;c.fillStyle=f.color;c.lineWidth=2;
if(f.kind==="text"){if(!this.reduced){c.font=(f.critical?"800 19px":f.n>=45?"800 16px":"700 12px")+" -apple-system, sans-serif";c.textAlign="center";c.lineWidth=3;c.strokeStyle="#071313";c.strokeText(f.n,f.x,f.y-progress*23);c.fillStyle=f.critical?"#ffb16e":f.n>=45?"#ffdf82":"#fff5d9";c.fillText(f.n,f.x,f.y-progress*23);}}
else if(f.kind==="slash"){const age=f.max-f.ttl,u=Math.min(1,age/.105),front=-1.35+2.65*(1-(1-u)**3),tail=Math.max(-1.38,front-(u<1?1.15:2.65)),fade=age<.105?1:Math.max(0,1-(age-.105)/.165)**2;c.translate(f.x,f.y);c.rotate(f.angle);const radius=f.r*.90,texture=Art.images.get("gold-slash")||this.slashTile;c.globalAlpha=fade;c.save();c.beginPath();const outer=[],inner=[];for(let i=0;i<=24;i++){const q=i/24,angle=tail+(front-tail)*q,thickness=(f.evolved?24:17)*Math.sin(Math.PI*q)**.65;outer.push([Math.cos(angle)*(radius+thickness),Math.sin(angle)*(radius+thickness)]);inner.push([Math.cos(angle)*(radius-thickness*.65),Math.sin(angle)*(radius-thickness*.65)]);}c.moveTo(...outer[0]);for(const point of outer)c.lineTo(...point);for(const point of inner.reverse())c.lineTo(...point);c.closePath();c.clip();c.globalAlpha*=.88;c.drawImage(texture,-radius*1.13,-radius*1.13,radius*2.26,radius*2.26);c.restore();
c.lineCap="round";c.strokeStyle="#fff8d8";c.lineWidth=2.5;c.beginPath();c.arc(0,0,radius*.96,Math.max(tail,front-.42),front);c.stroke();
if(!this.reduced){for(let i=0;i<8;i++){const angle=tail+(front-tail)*i/8,dist=radius*(.82+hash(i,f.id)*.24)+age*20;star(c,Math.cos(angle)*dist,Math.sin(angle)*dist,(1.6+hash(i,7)*2.2)*fade,"#ffe5a0");}const x=Math.cos(front)*radius,y=Math.sin(front)*radius;this.glow(x,y,42,"gold",fade*.55);}
}
else if(f.kind==="arrow-release"||f.kind==="bolt-release"){const frost=f.kind==="bolt-release";c.translate(f.x,f.y);c.rotate(f.angle);const u=1-a;c.globalAlpha=a*a;this.glow(0,0,frost?54:34,frost?"blue":"mint",.65);c.strokeStyle=frost?"#a9eaffcc":"#a6e8babb";c.lineWidth=1.3;c.beginPath();c.arc(0,0,6+u*(frost?25:15),-.8,.8);c.stroke();if(!this.reduced)for(let i=0;i<(frost?6:3);i++){const angle=frost?i*TAU/6:(i-1)*.33,dist=6+u*(frost?31:24);if(frost){c.save();c.translate(Math.cos(angle)*dist,Math.sin(angle)*dist);c.rotate(angle);c.fillStyle="#c7f4ff";c.beginPath();c.moveTo(6*a,0);c.lineTo(-3*a,-2*a);c.lineTo(-1,0);c.lineTo(-3*a,2*a);c.closePath();c.fill();c.restore();}else star(c,Math.cos(angle)*dist,Math.sin(angle)*dist,2.2*a,"#d4ffe2");}}
else if(f.kind==="arrow-hit"||f.kind==="bolt-hit"){const frost=f.kind==="bolt-hit",u=1-a;c.translate(f.x,f.y);c.rotate(f.angle);c.globalAlpha=a*a;this.glow(0,0,(frost?50:32)+u*14,frost?"blue":"mint",.65);star(c,0,0,(frost?11:6)*a,frost?"#eefcff":"#f1ffd7");if(frost){c.strokeStyle="#ace9ff";c.lineWidth=1.3;c.beginPath();for(let i=0;i<6;i++){const angle=i*TAU/6,dist=5+u*19,x=Math.cos(angle)*dist,y=Math.sin(angle)*dist;if(!i)c.moveTo(x,y);else c.lineTo(x,y);}c.closePath();c.stroke();}else{c.strokeStyle="#e6ffd5";c.lineWidth=1.4;c.beginPath();c.moveTo(-14*a,0);c.lineTo(4*a,0);c.stroke();}if(!this.reduced)for(let i=0;i<(frost?7:4);i++){const angle=frost?i*TAU/7:(i-1.5)*.65+Math.PI,dist=5+u*(frost?38:26);c.save();c.translate(Math.cos(angle)*dist,Math.sin(angle)*dist+u*u*8);c.rotate(angle);c.fillStyle=i%2?"#83c8e8":"#e0faff";if(frost){c.beginPath();c.moveTo(6*a,0);c.lineTo(-2*a,-2*a);c.lineTo(0,0);c.lineTo(-2*a,2*a);c.closePath();c.fill();}else{c.strokeStyle=i%2?"#abd4a5":"#e3ffcf";c.lineWidth=1.1;c.beginPath();c.moveTo(0,0);c.lineTo(5*a,0);c.stroke();}c.restore();}}
else if(f.kind==="cut-hit"){const age=f.max-f.ttl,k=Math.max(0,1-age/.32),impact=Math.max(0,1-age/.09);c.translate(f.x,f.y);c.rotate(f.angle-.7);c.globalCompositeOperation="lighter";c.globalAlpha=impact;this.glow(0,0,45+age*100,"gold",.85);c.fillStyle="#fff3c7";c.beginPath();c.moveTo(-27*impact,0);c.lineTo(0,-3.5);c.lineTo(27*impact,0);c.lineTo(0,3.5);c.closePath();c.fill();
c.globalAlpha=k*k;if(!this.reduced)for(let i=0;i<9;i++){const angle=(i-4)*.26,travel=(20+hash(i,f.x)*55)*age*5,side=i%2?1:-1,x=Math.cos(angle)*travel*side,y=Math.sin(angle)*travel+age*age*100;c.strokeStyle=i%3?"#e2af64":"#fff6cc";c.lineWidth=i%3?1.2:2;c.beginPath();c.moveTo(x,y);c.lineTo(x-Math.cos(angle)*side*(3+k*6),y-Math.sin(angle)*(3+k*6));c.stroke();}}
else if(f.kind==="impact"){this.glow(f.x,f.y,45*a+12,"gold",.85);star(c,f.x,f.y,(7+progress*14)*a,"#fff6d3");if(!this.reduced)for(let i=0;i<5;i++){const angle=f.angle+i*TAU/5,dist=6+progress*29;c.strokeStyle=i%2?"#fff4cf":"#ffc46f";c.lineWidth=1.5;c.beginPath();c.moveTo(f.x+Math.cos(angle)*dist,f.y+Math.sin(angle)*dist);c.lineTo(f.x+Math.cos(angle)*(dist+5*a),f.y+Math.sin(angle)*(dist+5*a));c.stroke();}}
else if(f.kind==="burst"){this.glow(f.x,f.y,45+progress*28,"violet",.42);if(!this.reduced)for(let i=0;i<7;i++){const ang=i*TAU/7+f.x*.1,dist=progress*32;star(c,f.x+Math.cos(ang)*dist,f.y+Math.sin(ang)*dist,3*a,f.color);}}
else if(f.kind==="ring"){const radius=f.r*(1-a*.83);c.lineWidth=f.r>400?5:3;this.circle(f.x,f.y,radius,null,f.color);c.globalAlpha=a*.5;c.lineWidth=1;this.circle(f.x,f.y,radius-8,null,"#effbff");if(!this.reduced){for(let i=0;i<(f.r>400?16:8);i++){const ang=i*TAU/(f.r>400?16:8)+t*.3;star(c,f.x+Math.cos(ang)*radius,f.y+Math.sin(ang)*radius,5*a,"#f0fbff");}this.glow(f.x,f.y,Math.min(300,radius*2),"blue",a*.15);}}
else if(f.kind==="line"){const length=Math.hypot(f.x2-f.x,f.y2-f.y),segments=Math.min(12,Math.max(3,Math.floor(length/26)));c.beginPath();c.moveTo(f.x,f.y);for(let i=1;i<segments;i++){const u=i/segments,offset=Math.sin(i*7+f.x)*10;c.lineTo(f.x+(f.x2-f.x)*u+offset,f.y+(f.y2-f.y)*u-offset);}c.lineTo(f.x2,f.y2);c.strokeStyle="#89bfff55";c.lineWidth=13;c.stroke();c.strokeStyle="#b2d6ff";c.lineWidth=4;c.stroke();c.strokeStyle="#fff9ef";c.lineWidth=1.5;c.stroke();this.glow(f.x2,f.y2,65,"blue",.85);if(!this.reduced){c.beginPath();c.moveTo(f.x2,f.y2);c.lineTo(f.x2-15,f.y2+9);c.lineTo(f.x2-6,f.y2+25);c.lineWidth=1.4;c.strokeStyle="#cce5ff";c.stroke();}}

else if(f.kind==="sun-cleave"){const u=1-a;c.translate(f.x,f.y);c.rotate(f.angle);c.globalAlpha=a*a;this.glow(0,0,180,"gold",.5);for(let i=0;i<3;i++){c.save();c.rotate(i*TAU/3);c.strokeStyle=i?"#e6ad5590":"#fff3c2";c.lineWidth=(i?5:10)*a;c.beginPath();c.arc(0,0,f.r*(.18+u*.8)-i*12,-1.9,.5);c.stroke();c.lineWidth=1.5;c.strokeStyle="#fff9dd";c.beginPath();c.arc(0,0,f.r*(.18+u*.8)-i*12,-1.2,.5);c.stroke();c.restore();}if(!this.reduced)for(let i=0;i<12;i++){const q=i*TAU/12,dist=f.r*(.2+u*.85);star(c,Math.cos(q)*dist,Math.sin(q)*dist,5*a,"#ffe6a4");}}
else if(f.kind==="meteor-fan"){c.translate(f.x,f.y);c.rotate(f.angle);this.glow(15,0,100,"mint",a*.7);c.strokeStyle="#dafde5";c.lineWidth=1.8;c.beginPath();c.arc(0,0,25+progress*42,-.8,.8);c.stroke();if(!this.reduced)for(let i=0;i<9;i++){const q=(i-4)*.11,dist=30+progress*180;star(c,Math.cos(q)*dist,Math.sin(q)*dist,4*a,"#d9ffe7");}}
else if(f.kind==="frost-crown"||f.kind==="rift-seal"){const ice=f.kind==="frost-crown",radius=f.r*(.25+progress*.85);c.translate(f.x,f.y);this.glow(0,0,130,ice?"blue":"gold",.3);c.lineWidth=2.5;c.strokeStyle=ice?"#d9f6ff":"#ffe8ab";this.circle(0,0,radius,null,c.strokeStyle);if(!this.reduced)for(let i=0;i<12;i++){const q=i*TAU/12;c.save();c.rotate(q);c.translate(radius,0);c.fillStyle=ice?"#a9dfff":"#ffe5a1";c.beginPath();c.moveTo(15*a,0);c.lineTo(-8*a,-4*a);c.lineTo(-2*a,0);c.lineTo(-8*a,4*a);c.closePath();c.fill();c.restore();}}

else if(f.kind==="whirlwind"||f.kind==="blood-cut"){c.translate(f.x,f.y);c.rotate(f.angle||0);const blood=f.kind==="blood-cut",radius=f.r*(.75+progress*.25),count=blood?1:3;
for(let i=0;i<count;i++){c.save();c.rotate(i*TAU/count+(blood?-.4:progress*1.5));c.strokeStyle=blood?"#cf56594d":"#f4bc6350";c.lineWidth=17*a;c.beginPath();c.arc(0,0,radius,-1.5,.65);c.stroke();c.lineWidth=6*a;c.strokeStyle=blood?"#f8aa9b":"#f8dca6";c.stroke();c.lineWidth=1.5;c.strokeStyle="#fff4db";c.beginPath();c.arc(0,0,radius+3,-.9,.65);c.stroke();c.restore();}
if(!this.reduced)for(let i=0;i<8;i++){const q=i*TAU/8+progress*2;star(c,Math.cos(q)*radius,Math.sin(q)*radius,3*a,blood?"#f6b4a2":"#ffe4ac");}}
else if(["fire-burst","meteor-impact","quake","trap-burst"].includes(f.kind)){const fire=f.kind==="fire-burst"||f.kind==="meteor-impact",trap=f.kind==="trap-burst",radius=f.r*(.2+Math.min(1,progress*2.6)*.8);
c.translate(f.x,f.y);this.glow(0,-8,Math.min(280,radius*2.5),fire?"red":"gold",a*.72);
ellipse(c,0,4,radius*.9,radius*.58,fire?"#e6743026":trap?"#9eaf6a20":"#a47a4122");
c.strokeStyle=fire?"#ffac64":"#d3c290";c.lineWidth=6*a;c.beginPath();c.ellipse(0,0,radius,radius*.7,0,0,TAU);c.stroke();c.lineWidth=1.6;c.strokeStyle="#ffe8bb";c.beginPath();c.ellipse(0,0,radius+5,radius*.7+4,0,0,TAU);c.stroke();
if(fire){const core=1-Math.min(1,progress*3);ellipse(c,0,-10,(40+f.r*.3)*core,(26+f.r*.22)*core,"#fff1c9");}
if(!this.reduced)for(let i=0;i<14;i++){const q=i*TAU/14,dist=radius*(.6+hash(i,f.x)*.4),x=Math.cos(q)*dist,y=Math.sin(q)*dist*.7-progress*(fire?42:18);c.save();c.translate(x,y);c.rotate(q);c.fillStyle=fire?i%2?"#ff9d51":"#ffe0a2":trap?"#c6d497":"#bca786";c.beginPath();c.moveTo(8*a,0);c.lineTo(-4*a,-3*a);c.lineTo(-2*a,0);c.lineTo(-4*a,3*a);c.closePath();c.fill();c.restore();}}
else if(f.kind==="arrow-rain"){c.translate(f.x,f.y);const count=this.reduced?5:this.quality<.8?8:13;for(let i=0;i<count;i++){const q=hash(i,f.x)*TAU,dist=Math.sqrt(hash(i,f.y))*f.r*.9,x=Math.cos(q)*dist,y=Math.sin(q)*dist,fall=Math.min(1,progress*1.5+hash(i,2)*.3),height=(1-fall)*125;c.strokeStyle="#b3f1c5";c.lineWidth=1.7;c.beginPath();c.moveTo(x+height*.25,y-height-22);c.lineTo(x,y-height);c.stroke();c.fillStyle="#edffd9";c.beginPath();c.moveTo(x,y-height+5);c.lineTo(x-3,y-height-3);c.lineTo(x+3,y-height-3);c.closePath();c.fill();if(fall>.92)star(c,x,y,4*a,"#d5f7bd");}}
else if(f.kind==="frost-storm"){c.translate(f.x,f.y);this.glow(0,0,f.r*1.8,"blue",a*.17);c.strokeStyle="#b3e9ff55";c.lineWidth=1.5;for(let i=0;i<3;i++){c.beginPath();c.ellipse(0,0,f.r*(.5+i*.2),f.r*(.23+i*.1),f.angle*.08+i,-.9,1.3);c.stroke();}if(!this.reduced)for(let i=0;i<(this.quality<.8?9:18);i++){const q=i*2.4+f.angle*.07,dist=f.r*Math.sqrt(hash(i,f.x)),x=Math.cos(q)*dist,y=Math.sin(q)*dist*.65-12-progress*20;c.save();c.translate(x,y);c.rotate(q);c.fillStyle=i%2?"#cceeff":"#8dcbe5";c.beginPath();c.moveTo(7*a,0);c.lineTo(-3*a,-2*a);c.lineTo(-2*a,0);c.lineTo(-3*a,2*a);c.closePath();c.fill();c.restore();}}

else if(f.kind==="ghost"&&!this.reduced){c.globalAlpha=a*.28;drawHero(c,g.hero,f.x,f.y,2.6,f.face,t,true);}
c.restore();}
skillField(f,t){const c=this.ctx,ice=f.key==="frost",fire=f.key==="meteor",trap=f.key==="trap",volley=f.key==="volley";if(f.key==="whirlwind"||f.done)return;
c.save();c.translate(f.x,f.y);const color=ice?"#a9dfff":fire?"#ffac71":trap?"#b9c991":volley?"#b3edc4":"#e2b386";
if(trap){const radius=f.trigger;c.globalAlpha=f.arm>0?.5:1;this.circle(0,0,radius,"#0c182940",color+"88");for(let i=0;i<12;i++){const q=i*TAU/12;c.save();c.rotate(q);c.fillStyle="#adc38b";c.beginPath();c.moveTo(radius-8,0);c.lineTo(radius+1,-4);c.lineTo(radius+1,4);c.closePath();c.fill();c.restore();}c.strokeStyle="#dfd6ae";c.lineWidth=1.5;c.beginPath();c.moveTo(-13,-10);c.lineTo(13,10);c.moveTo(13,-10);c.lineTo(-13,10);c.stroke();}
else{c.globalAlpha=f.delay>0?.5:.65;this.circle(0,0,f.r,ice?"#7cbfe315":fire?"#c676301a":"#95be9310",color+"66");c.setLineDash(f.delay>0?[7,7]:[]);c.lineWidth=1.2;this.circle(0,0,f.r*.92,null,color+"88");c.setLineDash([]);
if(f.delay>0){const total=fire?.7:volley?.45:f.key==="slam"?.22:.25,u=clampRender(1-f.delay/total);c.strokeStyle=color;c.lineWidth=2;c.beginPath();c.arc(0,0,f.r,-Math.PI/2,-Math.PI/2+u*TAU);c.stroke();
if(fire){const height=(1-u)*170;c.globalAlpha=1;this.glow(height*.3,-height-18,65,"red",.85);c.strokeStyle="#ffb97570";c.lineWidth=12;c.beginPath();c.moveTo(height*.3+28,-height-70);c.lineTo(height*.3,-height-18);c.stroke();ellipse(c,height*.3,-height-18,15,19,"#ffc97c");ellipse(c,height*.3-3,-height-22,7,10,"#ffefd2");}}
else if(ice&&!this.reduced){c.strokeStyle="#98d7ed50";for(let i=0;i<4;i++){const a=t*.6+i*TAU/4;c.beginPath();c.ellipse(0,0,f.r*.8,f.r*.38,a,-.8,.8);c.stroke();}}}
c.restore();}

draw(t,g,hero,joy){if(Art.ready&&!this.artReady)this.makeGround();if(g)t=g.time;const c=this.ctx,w=this.w,h=this.h,p=g?.player,cx=p?.x||900,cy=p?.y||900;this.ground(cx,cy,t,g?this.zoom:1);if(g){c.fillStyle="#0914210c";c.fillRect(0,0,w,h);}
if(!g){const bounds=this.canvas.getBoundingClientRect(),label=document.querySelector(".home-title p")?.getBoundingClientRect(),content=document.querySelector(".home-content")?.getBoundingClientRect(),top=label?label.bottom-bounds.top:h*.22,bottom=content?content.top-bounds.top:h*.56,stageSize=Math.min(230,Math.max(85,bottom-top-28)),stageY=(top+bottom)/2+stageSize*.24;const grad=c.createLinearGradient(0,0,0,h);grad.addColorStop(0,"#061321d9");grad.addColorStop(.30,"#09182470");grad.addColorStop(.51,"#0a182dcc");grad.addColorStop(.64,"#0a182dfa");grad.addColorStop(1,"#0a182d");c.fillStyle=grad;c.fillRect(0,0,w,h);
this.glow(w/2,stageY-25,stageSize*1.7,hero.id==="knight"?"gold":hero.id==="ranger"?"mint":"blue",.22);
ellipse(c,w/2,stageY+stageSize*.23,stageSize*.56,stageSize*.13,"#020d1980");c.strokeStyle="#b69c6250";c.lineWidth=1;c.beginPath();c.ellipse(w/2,stageY+stageSize*.22,stageSize*.57,stageSize*.15,0,0,TAU);c.stroke();
drawHero(c,hero,w/2,stageY,stageSize/34,1,t);return;}
const f=this.feedback,shake=!this.reduced&&t<f.until?f.shake*Math.max(0,(f.until-t)/.22):0,sx=Math.sin(t*127)*shake,sy=Math.cos(t*111)*shake;
c.save();c.translate(w/2+sx,h/2+sy);c.scale(this.zoom,this.zoom);c.translate(-cx,-cy);
for(const field of g.skillFields||[])this.skillField(field,t);
for(const field of g.spellFields||[]){c.save();c.globalAlpha=Math.min(.6,field.ttl*.4);this.circle(field.x,field.y,field.r,"#7bbbe81a","#a8def078");c.strokeStyle="#a9e8ff80";c.lineWidth=1;for(let i=0;i<6;i++){const angle=i*TAU/6;c.beginPath();c.moveTo(field.x+Math.cos(angle)*28,field.y+Math.sin(angle)*28);c.lineTo(field.x+Math.cos(angle)*(field.r-16),field.y+Math.sin(angle)*(field.r-16));c.stroke();star(c,field.x+Math.cos(angle)*(field.r-16),field.y+Math.sin(angle)*(field.r-16),8,"#c4ecff99");}c.restore();}
if(g.rift){const r=g.rift;c.save();c.translate(r.x,r.y);this.glow(0,0,150,"violet",.25);this.circle(0,0,r.r,"#171c4580","#b7a3e080");c.strokeStyle="#f6d38d";c.lineWidth=4;c.beginPath();c.arc(0,0,r.r,-Math.PI/2,-Math.PI/2+TAU*r.progress/3);c.stroke();c.rotate(t*.22);for(let i=0;i<6;i++){const a=i*TAU/6;star(c,Math.cos(a)*43,Math.sin(a)*43,5,"#ccbbf4");}c.rotate(-t*.22);c.font="600 11px -apple-system,sans-serif";c.textAlign="center";c.fillStyle="#e6dffc";c.fillText(r.progress>0?"봉인 중":"3초 머물기",0,4);c.restore();}
for(const e of g.enemies)if(e.charge&&e.charge.age<.7){c.save();c.translate(e.x,e.y);c.rotate(e.charge.angle);c.fillStyle="#e2705f28";c.fillRect(0,-22,140,44);c.strokeStyle="#ffac82";c.lineWidth=1.5;c.strokeRect(0,-22,140,44);c.fillStyle="#ffc39e";c.beginPath();c.moveTo(140,0);c.lineTo(126,-7);c.lineTo(126,7);c.closePath();c.fill();c.restore();}
for(const gem of g.gems){if(Math.abs(gem.x-cx)>w/2+25||Math.abs(gem.y-cy)>h/2+25)continue;if(gem.value>=3)this.glow(gem.x,gem.y,25,gem.heal?"red":"mint",.55);c.save();c.translate(gem.x,gem.y);c.rotate(Math.PI/4);c.fillStyle=gem.heal?"#ed9d94":"#86ecc3";c.fillRect(-3,-3,6,6);c.fillStyle=gem.heal?"#ffded0":"#e4ffdb";c.fillRect(-2,-2,2,2);c.restore();}
for(const item of g.pickups||[]){if(Math.abs(item.x-cx)>w/2+40||Math.abs(item.y-cy)>h/2+40)continue;this.glow(item.x,item.y,52,item.kind==="chest"?"gold":"blue",.6);c.fillStyle="#0a2723";c.fillRect(item.x-14,item.y-10,28,24);c.fillStyle=item.kind==="chest"?"#bb9048":"#6ca9ca";c.fillRect(item.x-12,item.y-9,24,20);c.strokeStyle="#fff1b0";c.lineWidth=1.5;c.strokeRect(item.x-12,item.y-9,24,20);c.fillStyle="#355445";c.fillRect(item.x-9,item.y-5,18,4);star(c,item.x,item.y+1,6,"#fff1c2");}
for(const hazard of g.hazards){c.lineWidth=2;const pulsing=.4+Math.sin(t*16)*.13;this.circle(hazard.x,hazard.y,hazard.r,hazard.delay>0?"#702b5559":"#dc6d8477","#ffd0b2");c.globalAlpha=pulsing;this.circle(hazard.x,hazard.y,hazard.r-7,null,"#fa9b87");c.globalAlpha=1;if(hazard.delay>0){c.strokeStyle="#ffdfba";c.lineWidth=3;c.beginPath();c.arc(hazard.x,hazard.y,hazard.r*(1-Math.max(0,hazard.delay)/1.1),0,TAU);c.stroke();}else this.glow(hazard.x,hazard.y,hazard.r*2,"red",.6);}
if(g.bladeSwing&&g.bladeSwing.elapsed<BLADE_TIMING.windup){const u=g.bladeSwing.elapsed/BLADE_TIMING.windup;c.save();c.translate(p.x,p.y-18);c.rotate(g.bladeSwing.angle);c.globalAlpha=.18+u*.2;c.strokeStyle="#d6ba73";c.lineWidth=1.2;c.beginPath();c.arc(0,0,23+u*9,-1.6,-.5);c.stroke();this.glow(18,-22,23,"gold",u*.24);c.restore();}
const ranged=g.rangedAttacks[g.hero.weapon];if(ranged&&!ranged.released){const frost=ranged.key==="bolt",u=Math.min(1,ranged.elapsed/ranged.releaseAt),face=Math.cos(ranged.angle)>=0?1:-1,x=p.x+face*(frost?23:28),y=p.y-(frost?34:27);c.save();c.globalAlpha=.2+u*.5;this.glow(x,y,frost?42:28,frost?"blue":"mint",u*.7);c.strokeStyle=frost?"#a2ddffbb":"#c7ebae99";c.lineWidth=1.1;if(frost){const r=17-u*6;c.beginPath();for(let i=0;i<6;i++){const a=i*TAU/6+t*1.4;if(!i)c.moveTo(x+Math.cos(a)*r,y+Math.sin(a)*r);else c.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r);}c.closePath();c.stroke();if(!this.reduced)for(let i=0;i<3;i++){const angle=t*2+i*TAU/3,dist=27*(1-u)+4;star(c,x+Math.cos(angle)*dist,y+Math.sin(angle)*dist,2.3,"#d3f2ff");}this.glow(p.x-face*16,p.y-67,24,"blue",u*.3);}else{c.beginPath();c.arc(x,y,9+u*4,-1.2,1.2);c.stroke();c.fillStyle="#e7ffcd";c.beginPath();c.moveTo(x+face*9,y);c.lineTo(x-face*9,y-1.2);c.lineTo(x-face*9,y+1.2);c.closePath();c.fill();}c.restore();}
for(const fx of g.fx)if(fx.kind==="ghost")this.effect(fx,t,g);
this.visible.length=0;for(const e of g.enemies)if(Math.abs(e.x-cx)<w/2+90&&Math.abs(e.y-cy)<h/2+120)this.visible.push(e);for(const [x,y,height,face]of this.groves)if(Math.abs(x-cx)<w/2+height*.5&&Math.abs(y-cy)<h/2+height)this.visible.push({prop:true,x,y,height,face});this.visible.push({player:true,y:p.y});this.visible.sort((a,b)=>a.y-b.y);
for(const e of this.visible){if(e.prop){c.save();const overlaps=Math.abs(e.x-p.x)<e.height*.46&&p.y>e.y-e.height*.76&&p.y<e.y+e.height*.28;c.globalAlpha=overlaps?.15:.60;drawSprite(c,"grove",e.x,e.y,e.height,e.face);c.restore();continue;}if(e.player){const primary=g.hero.weapon==="blade"?(g.bladeSwing||g.skillPose):(g.rangedAttacks[g.hero.weapon]||g.skillPose),attacking=!!primary,face=attacking?Math.cos(primary.angle)>=0?1:-1:p.facing;c.save();if(p.inv>0)c.globalAlpha=.7+Math.sin(t*22)*.2;drawHero(c,g.hero,p.x,p.y,2.6,face,t,p.moving,attacking,p.inv>0&&t<f.flash?.6:0,primary,!this.reduced,p.walkDistance/72);c.restore();if(p.dash>0){this.glow(p.x,p.y,65,"mint",.32);}if(p.inv>0){c.lineWidth=1;this.circle(p.x,p.y,23,null,"#b4f3d76f");}}else{this.enemy(e,t,p);if(e.statuses?.bleed||e.statuses?.["poison-dot"]){c.save();c.globalAlpha=.55;this.circle(e.x,e.y+4,e.r+4,null,e.statuses.bleed?"#f4918e":"#bbe970");c.restore();}if(e.root>0){c.strokeStyle="#bde7f599";c.lineWidth=1.2;c.beginPath();c.moveTo(e.x-e.r,e.y+8);c.lineTo(e.x,e.y-e.r-3);c.lineTo(e.x+e.r,e.y+8);c.stroke();}}}
const lv=g.weapons.orbit;if(lv){const evo=!!g.evolved?.orbit,n=evo?6:2+Math.floor(lv/2),r=(64+lv*6+(evo?20:0))*(1+(g.passives.focus||0)*.08);c.lineWidth=.6;this.circle(p.x,p.y,r,null,"#d2b77c33");for(let i=0;i<n;i++){const a=g.time*2.6+i*TAU/n,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;this.glow(x,y,32,"gold",.55);c.save();c.translate(x,y);c.rotate(a+Math.PI/2);c.fillStyle="#b98f55";c.fillRect(-3,-12,6,24);c.fillStyle="#fceac1";c.beginPath();c.moveTo(0,-24);c.lineTo(4,-6);c.lineTo(0,0);c.lineTo(-4,-6);c.closePath();c.fill();c.strokeStyle="#fff6da";c.lineWidth=1;c.beginPath();c.moveTo(0,-22);c.lineTo(0,-3);c.stroke();c.restore();}}
for(const b of g.bullets)if(Math.abs(b.x-cx)<w/2+45&&Math.abs(b.y-cy)<h/2+45)this.projectile(b);
for(const b of g.shots)if(Math.abs(b.x-cx)<w/2+25&&Math.abs(b.y-cy)<h/2+25)this.projectile(b,true);
let decorative=0;for(const fx of g.fx){if(fx.kind==="ghost"||Math.abs(fx.x-cx)>w/2+(fx.r||80)||Math.abs(fx.y-cy)>h/2+(fx.r||80))continue;if(["impact","arrow-hit","bolt-hit","text","burst"].includes(fx.kind)&&++decorative>(this.quality<.8?24:56))continue;this.effect(fx,t,g);}
c.restore();
if(g.rift){const dx=(g.rift.x-cx)*this.zoom,dy=(g.rift.y-cy)*this.zoom,edgeX=w/2-38,edgeY=h/2-175,k=Math.min(1,edgeX/Math.max(1,Math.abs(dx)),edgeY/Math.max(1,Math.abs(dy)));
if(k<1){const x=w/2+dx*k,y=h/2+dy*k;c.save();c.translate(x,y);this.circle(0,0,17,"#101a35dc","#bca9e9");c.rotate(Math.atan2(dy,dx));c.fillStyle="#e0cff8";c.beginPath();c.moveTo(8,0);c.lineTo(-4,-5);c.lineTo(-4,5);c.closePath();c.fill();c.restore();}}
if(!this.reduced&&this.quality>.7){c.save();c.globalAlpha=.025;const light=c.createLinearGradient(0,0,w,h);light.addColorStop(0,"#ffeda9");light.addColorStop(1,"#ffeda900");c.fillStyle=light;c.beginPath();c.moveTo(w*.8,0);c.lineTo(w*.99,0);c.lineTo(w*.47,h*.68);c.lineTo(w*.04,h*.68);c.closePath();c.fill();c.restore();}c.fillStyle=this.vignette;c.fillRect(0,0,w,h);
if(!this.reduced&&t<f.flash){c.fillStyle=p.inv>0&&p.hp<p.maxHp*.45?"#df84741c":"#ffe8a916";c.fillRect(0,0,w,h);}
if(joy.active){c.lineWidth=1.5;this.circle(joy.ox,joy.oy,43,"#071f2055","#ecd9a66e");this.circle(joy.ox+joy.x*37,joy.oy+joy.y*37,18,"#c6d8bd50","#f6e5b2a0");}
}
}
