import {UPGRADES,BLADE_TIMING} from "./core.js";
import {Art,drawSprite} from "./art.js";
const TAU=Math.PI*2,hash=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n);};
function ellipse(c,x,y,rx,ry,color){c.fillStyle=color;c.beginPath();c.ellipse(x,y,rx,ry,0,0,TAU);c.fill();}
function star(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.moveTo(x,y-r);c.lineTo(x+r*.27,y-r*.27);c.lineTo(x+r,y);c.lineTo(x+r*.27,y+r*.27);c.lineTo(x,y+r);c.lineTo(x-r*.27,y+r*.27);c.lineTo(x-r,y);c.lineTo(x-r*.27,y-r*.27);c.closePath();c.fill();}
export function drawHero(c,h,x,y,scale=2,face=1,t=0,moving=false,attack=false,flash=0,swing=null,motion=true){
const height=scale*34,bob=moving?Math.sin(t*12)*1.3:Math.sin(t*2)*.65;
ellipse(c,x,y+height*.18,height*.24,height*.09,"#010e0baa");
if(h.id==="knight"&&Art.images.has("knight-strike-0")){let index=0,lean=0,lunge=0;if(swing){const age=swing.elapsed;index=age<.025?0:age<.06?1:age<.09?2:age<.14?3:age<.19?4:age<.255?5:age<.31?6:7;lean=age<.09?-.035:age<.20?.04:0;lunge=age<.09?-2:age<.20?4:1;}const sprite=Art.sprite("knight-strike-"+index),poseHeight=scale*58,poseWidth=poseHeight*sprite.width/sprite.height;
c.save();c.translate(x+lunge*face,y+bob);c.scale(face,1);c.rotate(lean);const top=poseHeight*(.18-256/296);if(swing&&motion&&swing.elapsed>=.10&&swing.elapsed<.18){c.save();c.globalAlpha*=.11;const trail=Art.sprite("knight-strike-3");c.drawImage(trail.image,-poseWidth/2-5,top,poseWidth,poseHeight);c.restore();}c.drawImage(sprite.image,-poseWidth/2,top,poseWidth,poseHeight);if(flash>0){c.globalAlpha*=Math.min(.3,flash);c.drawImage(sprite.flash,-poseWidth/2,top,poseWidth,poseHeight);}c.restore();return;}
const frame=h.id==="knight"?(attack?"knight-attack":moving?(Math.floor(t*10)%2?"knight-walk-a":"knight-walk-b"):"knight-idle"):h.id;
drawSprite(c,frame,x,y+bob,height,face,flash,moving?Math.sin(t*10)*.025:0);
}
export class Renderer{
constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext("2d",{alpha:false});this.reduced=false;this.quality=1;this.visible=[];this.artReady=false;this.zoom=1.12;this.groves=[[685,850,295,1],[1105,845,300,-1],[850,1235,290,1],[1050,570,300,-1],[405,410,285,1],[1370,1220,320,-1],[1510,430,280,1]];this.feedback={shake:0,until:0,flash:0,swingUntil:0,swingAngle:0};this.makeGround();this.makeEffects();this.resize();}
setQuality(scale){if(Math.abs(this.quality-scale)<.01)return;this.quality=scale;this.resize();}
makeGround(){const tile=document.createElement("canvas");tile.width=tile.height=768;const c=tile.getContext("2d"),image=Art.images.get("forest");if(image){c.drawImage(image,0,0,768,768);c.fillStyle="#04261e64";c.fillRect(0,0,768,768);this.artReady=true;}else{c.fillStyle="#16382e";c.fillRect(0,0,768,768);}this.tile=tile;this.pattern=this.ctx.createPattern(tile,"repeat");}
makeEffects(){
this.glows={};for(const [key,color]of Object.entries({gold:"#ffe7a0",mint:"#95f8c5",blue:"#b5eaff",violet:"#d89bff",red:"#ffaca0"})){const tile=document.createElement("canvas");tile.width=tile.height=96;const c=tile.getContext("2d"),g=c.createRadialGradient(48,48,0,48,48,48);g.addColorStop(0,color+"b0");g.addColorStop(.22,color+"65");g.addColorStop(.6,color+"22");g.addColorStop(1,color+"00");c.fillStyle=g;c.fillRect(0,0,96,96);this.glows[key]=tile;}
const tile=document.createElement("canvas");tile.width=tile.height=384;const c=tile.getContext("2d");c.translate(192,192);const g=c.createLinearGradient(10,-140,155,125);g.addColorStop(0,"#f6b54700");g.addColorStop(.24,"#e4a84490");g.addColorStop(.7,"#ffe59fff");g.addColorStop(1,"#fffbeeff");c.fillStyle=g;c.beginPath();c.arc(0,0,158,-1.6,1.1);c.arc(0,0,130,1.1,-1.6,true);c.closePath();c.shadowColor="#ffc66d";c.shadowBlur=18;c.fill();c.shadowBlur=0;c.strokeStyle="#fff6d4";c.lineWidth=4;c.beginPath();c.arc(0,0,158,-.85,1.08);c.stroke();c.strokeStyle="#ffcb6c88";c.lineWidth=2;c.beginPath();c.arc(0,0,118,-1.2,1);c.stroke();for(let i=0;i<6;i++){const a=-1.05+i*.36;star(c,Math.cos(a)*125,Math.sin(a)*125,4,"#fff0bfbb");}this.slashTile=tile;
}
resize(){const b=this.canvas.getBoundingClientRect();this.w=Math.max(1,b.width);this.h=Math.max(1,b.height);const d=Math.min(window.devicePixelRatio||1,2)*this.quality;this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.ctx.setTransform(d,0,0,d,0,0);this.ctx.imageSmoothingEnabled=true;this.pattern=this.ctx.createPattern(this.tile,"repeat");this.vignette=this.ctx.createRadialGradient(this.w/2,this.h*.48,Math.min(this.w,this.h)*.16,this.w/2,this.h*.48,Math.max(this.w,this.h)*.65);this.vignette.addColorStop(0,"#04191000");this.vignette.addColorStop(.65,"#031c1444");this.vignette.addColorStop(1,"#010e0ddd");}
circle(x,y,r,color,stroke){const c=this.ctx;c.beginPath();c.arc(x,y,r,0,TAU);if(color){c.fillStyle=color;c.fill();}if(stroke){c.strokeStyle=stroke;c.stroke();}}
glow(x,y,size,key="gold",alpha=1){const c=this.ctx;c.save();c.globalAlpha*=alpha;c.drawImage(this.glows[key],x-size/2,y-size/2,size,size);c.restore();}
react(e,g){if(!g)return;const f=this.feedback,t=g.time;if(e.type==="blade-windup"){f.swingUntil=t+BLADE_TIMING.duration;f.swingAngle=e.angle;}if(e.type==="blade-contact"){f.shake=Math.max(f.shake,e.strong?2.6:1.5);f.until=t+.075;f.contact=t;f.combo=e.id;}
if(e.type==="impact"&&e.strong){f.shake=Math.max(f.shake,2.5);f.until=t+.085;}if(e.type==="hurt"){f.shake=4;f.until=t+.13;f.flash=t+.1;}if(e.type==="ultimate"){f.shake=6;f.until=t+.22;f.flash=t+.085;}}
ground(cx,cy,t,zoom=1){const c=this.ctx,w=this.w,h=this.h;c.fillStyle="#16382e";c.fillRect(0,0,w,h);c.save();c.translate(w/2,h/2);c.scale(zoom,zoom);c.translate(-cx,-cy);c.fillStyle=this.pattern;c.fillRect(cx-w/(2*zoom),cy-h/(2*zoom),w/zoom,h/zoom);c.strokeStyle="#a0c98c33";c.lineWidth=2;for(const r of [115,135]){c.beginPath();c.arc(900,900,r,0,TAU);c.stroke();}for(let i=0;i<8;i++){const a=i*TAU/8;star(c,900+Math.cos(a)*125,900+Math.sin(a)*125,5,"#b8cd8855");}
for(const [x,y]of [[590,600],[1200,600],[600,1200],[1200,1190],[930,1420],[410,1030],[1480,880]]){if(Math.abs(x-cx)>w/2+60||Math.abs(y-cy)>h/2+100)continue;ellipse(c,x,y+20,25,10,"#01171088");drawSprite(c,"ruin",x,y,90);this.glow(x,y-30,48,"mint",.25);}
c.fillStyle="#031713";c.fillRect(-300,-300,2400,300);c.fillRect(-300,1800,2400,300);c.fillRect(-300,0,300,1800);c.fillRect(1800,0,300,1800);c.strokeStyle="#83925d55";c.lineWidth=6;c.strokeRect(10,10,1780,1780);c.restore();
if(!this.reduced&&this.quality>.7)for(let i=0;i<9;i++){const x=(hash(i,9)*w+t*(i%3+1)*2)%(w+20)-10,y=(hash(i,4)*h-t*1.4)%(h+20);this.circle(x,y,1.2,"#ddeea8"+(i%2?"45":"88"));}}
enemy(e,t,p){const c=this.ctx,flash=Math.max(0,e.flash/.12),away=Math.atan2(e.y-p.y,e.x-p.x),recoil=flash*5,x=e.x+Math.cos(away)*recoil,y=e.y+Math.sin(away)*recoil;
const height=e.boss?170:e.kind==="brute"?(e.elite?100:80):e.kind==="bat"?48:e.kind==="seer"?70:58;
ellipse(c,x,y+height*.18,height*.26,height*.10,e.boss?"#0a080eb0":"#020b0b88");
if(e.boss){this.glow(x,y-20,120,"violet",.32);c.lineWidth=1;this.circle(x,y,55,null,"#d099df55");}
const bob=e.kind==="bat"?Math.sin(t*12+e.id)*3:Math.sin(t*7+e.id)*.6;
drawSprite(c,e.boss?"boss":e.kind,x,y+bob,height,p.x>=e.x?1:-1,flash*(e.hitKind==="blade"?.18:.32),Math.sin(t*7+e.id)*.015+flash*.07);
if(e.slow>0){c.strokeStyle="#c5f3ff99";c.lineWidth=1;c.beginPath();c.arc(x,y,Math.max(15,e.r+3),0,TAU);c.stroke();}
if(e.elite&&!e.boss){c.lineWidth=2;this.circle(x,y,e.r+5,null,"#e8c37d88");c.fillStyle="#0a0f14cc";c.fillRect(x-20,y-height*.65,40,4);c.fillStyle="#f8cc79";c.fillRect(x-20,y-height*.65,40*Math.max(0,e.hp/e.maxHp),4);}}
projectile(b,enemy=false){const c=this.ctx,angle=Math.atan2(b.vy,b.vx);c.save();c.translate(b.x,b.y);c.rotate(angle);if(enemy){this.glow(0,0,25,"violet",.9);ellipse(c,0,0,b.r+1,b.r+1,"#ca72ee");ellipse(c,1,-1,2.4,2.4,"#fff0ff");}else if(b.key==="arrow"){c.strokeStyle="#6cdbab66";c.lineWidth=5;c.beginPath();c.moveTo(-32,0);c.lineTo(0,0);c.stroke();c.strokeStyle="#e4f8c1";c.lineWidth=2;c.beginPath();c.moveTo(-22,0);c.lineTo(5,0);c.stroke();c.fillStyle="#f4ffd8";c.beginPath();c.moveTo(9,0);c.lineTo(0,-4);c.lineTo(0,4);c.closePath();c.fill();}else{this.glow(0,0,b.r*6,"blue",.8);ellipse(c,-9,0,19,b.r*1.6,"#6fc4f280");ellipse(c,0,0,13,b.r*.75,"#d4f3ff");star(c,4,0,b.r+3,"#fff");}c.restore();}
effect(f,t,g){const c=this.ctx,a=Math.max(0,f.ttl/f.max),progress=1-a;c.save();c.globalAlpha=a;c.strokeStyle=f.color;c.fillStyle=f.color;c.lineWidth=2;
if(f.kind==="text"){if(!this.reduced){c.font=(f.n>=45?"800 16px":"700 12px")+" -apple-system, sans-serif";c.textAlign="center";c.lineWidth=3;c.strokeStyle="#071313";c.strokeText(f.n,f.x,f.y-progress*23);c.fillStyle=f.n>=45?"#ffdf82":"#fff5d9";c.fillText(f.n,f.x,f.y-progress*23);}}
else if(f.kind==="slash"){const age=f.max-f.ttl,u=Math.min(1,age/.105),front=-1.35+2.65*(1-(1-u)**3),tail=Math.max(-1.38,front-(u<1?1.15:2.65)),fade=age<.105?1:Math.max(0,1-(age-.105)/.165)**2;c.translate(f.x,f.y);c.rotate(f.angle);const radius=f.r*.90,texture=Art.images.get("gold-slash")||this.slashTile;c.globalAlpha=fade;c.save();c.beginPath();const outer=[],inner=[];for(let i=0;i<=24;i++){const q=i/24,angle=tail+(front-tail)*q,thickness=(f.evolved?24:17)*Math.sin(Math.PI*q)**.65;outer.push([Math.cos(angle)*(radius+thickness),Math.sin(angle)*(radius+thickness)]);inner.push([Math.cos(angle)*(radius-thickness*.65),Math.sin(angle)*(radius-thickness*.65)]);}c.moveTo(...outer[0]);for(const point of outer)c.lineTo(...point);for(const point of inner.reverse())c.lineTo(...point);c.closePath();c.clip();c.globalAlpha*=.88;c.drawImage(texture,-radius*1.13,-radius*1.13,radius*2.26,radius*2.26);c.restore();
c.lineCap="round";c.strokeStyle="#fff8d8";c.lineWidth=2.5;c.beginPath();c.arc(0,0,radius*.96,Math.max(tail,front-.42),front);c.stroke();
if(!this.reduced){for(let i=0;i<8;i++){const angle=tail+(front-tail)*i/8,dist=radius*(.82+hash(i,f.id)*.24)+age*20;star(c,Math.cos(angle)*dist,Math.sin(angle)*dist,(1.6+hash(i,7)*2.2)*fade,"#ffe5a0");}const x=Math.cos(front)*radius,y=Math.sin(front)*radius;this.glow(x,y,42,"gold",fade*.55);}
}
else if(f.kind==="cut-hit"){const age=f.max-f.ttl,k=Math.max(0,1-age/.32),impact=Math.max(0,1-age/.09);c.translate(f.x,f.y);c.rotate(f.angle-.7);c.globalCompositeOperation="lighter";c.globalAlpha=impact;this.glow(0,0,45+age*100,"gold",.85);c.fillStyle="#fff3c7";c.beginPath();c.moveTo(-27*impact,0);c.lineTo(0,-3.5);c.lineTo(27*impact,0);c.lineTo(0,3.5);c.closePath();c.fill();
c.globalAlpha=k*k;if(!this.reduced)for(let i=0;i<9;i++){const angle=(i-4)*.26,travel=(20+hash(i,f.x)*55)*age*5,side=i%2?1:-1,x=Math.cos(angle)*travel*side,y=Math.sin(angle)*travel+age*age*100;c.strokeStyle=i%3?"#e2af64":"#fff6cc";c.lineWidth=i%3?1.2:2;c.beginPath();c.moveTo(x,y);c.lineTo(x-Math.cos(angle)*side*(3+k*6),y-Math.sin(angle)*(3+k*6));c.stroke();}}
else if(f.kind==="impact"){this.glow(f.x,f.y,45*a+12,"gold",.85);star(c,f.x,f.y,(7+progress*14)*a,"#fff6d3");if(!this.reduced)for(let i=0;i<5;i++){const angle=f.angle+i*TAU/5,dist=6+progress*29;c.strokeStyle=i%2?"#fff4cf":"#ffc46f";c.lineWidth=1.5;c.beginPath();c.moveTo(f.x+Math.cos(angle)*dist,f.y+Math.sin(angle)*dist);c.lineTo(f.x+Math.cos(angle)*(dist+5*a),f.y+Math.sin(angle)*(dist+5*a));c.stroke();}}
else if(f.kind==="burst"){this.glow(f.x,f.y,45+progress*28,"violet",.42);if(!this.reduced)for(let i=0;i<7;i++){const ang=i*TAU/7+f.x*.1,dist=progress*32;star(c,f.x+Math.cos(ang)*dist,f.y+Math.sin(ang)*dist,3*a,f.color);}}
else if(f.kind==="ring"){const radius=f.r*(1-a*.83);c.lineWidth=f.r>400?5:3;this.circle(f.x,f.y,radius,null,f.color);c.globalAlpha=a*.5;c.lineWidth=1;this.circle(f.x,f.y,radius-8,null,"#effbff");if(!this.reduced){for(let i=0;i<(f.r>400?16:8);i++){const ang=i*TAU/(f.r>400?16:8)+t*.3;star(c,f.x+Math.cos(ang)*radius,f.y+Math.sin(ang)*radius,5*a,"#f0fbff");}this.glow(f.x,f.y,Math.min(300,radius*2),"blue",a*.15);}}
else if(f.kind==="line"){const length=Math.hypot(f.x2-f.x,f.y2-f.y),segments=Math.min(12,Math.max(3,Math.floor(length/26)));c.beginPath();c.moveTo(f.x,f.y);for(let i=1;i<segments;i++){const u=i/segments,offset=Math.sin(i*7+f.x)*10;c.lineTo(f.x+(f.x2-f.x)*u+offset,f.y+(f.y2-f.y)*u-offset);}c.lineTo(f.x2,f.y2);c.strokeStyle="#ffd57155";c.lineWidth=8;c.stroke();c.strokeStyle="#fff5bd";c.lineWidth=2;c.stroke();this.glow(f.x2,f.y2,45,"gold",.7);}
else if(f.kind==="ghost"&&!this.reduced){c.globalAlpha=a*.28;drawHero(c,g.hero,f.x,f.y,2.6,f.face,t,true);}
c.restore();}
draw(t,g,hero,joy){if(Art.ready&&!this.artReady)this.makeGround();if(g)t=g.time;const c=this.ctx,w=this.w,h=this.h,p=g?.player,cx=p?.x||900,cy=p?.y||900;this.ground(cx,cy,t,g?this.zoom:1);if(g){c.fillStyle="#04161038";c.fillRect(0,0,w,h);}
if(!g){for(const [x,y,height,face]of [[w*.13,h*.36,Math.min(410,h*.54),1],[w*.94,h*.45,Math.min(390,h*.48),-1]]){c.save();c.globalAlpha=.40;drawSprite(c,"grove",x,y,height,face);c.restore();}const height=Math.min(330,h*.43),x=w*.72,y=h*.30;this.glow(x,y-15,height*1.1,"gold",.40);this.glow(x-60,y+20,height*1.2,"mint",.17);c.save();c.translate(x,y);c.strokeStyle="#e6c47766";c.lineWidth=1;c.beginPath();c.arc(0,0,height*.40,0,TAU);c.stroke();for(let i=0;i<8;i++){const a=i*TAU/8+t*.04;star(c,Math.cos(a)*height*.4,Math.sin(a)*height*.4,4,"#e6d09b99");}c.restore();drawHero(c,hero,x,y,height/34,1,t);const grad=c.createLinearGradient(0,0,0,h);grad.addColorStop(0,"#03171470");grad.addColorStop(.22,"#03171408");grad.addColorStop(.43,"#061b1790");grad.addColorStop(.58,"#071d1bf8");grad.addColorStop(1,"#071d1b");c.fillStyle=grad;c.fillRect(0,0,w,h);return;}
const f=this.feedback,shake=!this.reduced&&t<f.until?f.shake*Math.max(0,(f.until-t)/.22):0,sx=Math.sin(t*127)*shake,sy=Math.cos(t*111)*shake;
c.save();c.translate(w/2+sx,h/2+sy);c.scale(this.zoom,this.zoom);c.translate(-cx,-cy);
for(const gem of g.gems){if(Math.abs(gem.x-cx)>w/2+25||Math.abs(gem.y-cy)>h/2+25)continue;if(gem.value>=3)this.glow(gem.x,gem.y,25,gem.heal?"red":"mint",.55);c.save();c.translate(gem.x,gem.y);c.rotate(Math.PI/4);c.fillStyle=gem.heal?"#ed9d94":"#86ecc3";c.fillRect(-3,-3,6,6);c.fillStyle=gem.heal?"#ffded0":"#e4ffdb";c.fillRect(-2,-2,2,2);c.restore();}
for(const item of g.pickups||[]){if(Math.abs(item.x-cx)>w/2+40||Math.abs(item.y-cy)>h/2+40)continue;this.glow(item.x,item.y,52,item.kind==="chest"?"gold":"blue",.6);c.fillStyle="#0a2723";c.fillRect(item.x-14,item.y-10,28,24);c.fillStyle=item.kind==="chest"?"#bb9048":"#6ca9ca";c.fillRect(item.x-12,item.y-9,24,20);c.strokeStyle="#fff1b0";c.lineWidth=1.5;c.strokeRect(item.x-12,item.y-9,24,20);c.fillStyle="#355445";c.fillRect(item.x-9,item.y-5,18,4);star(c,item.x,item.y+1,6,"#fff1c2");}
for(const hazard of g.hazards){c.lineWidth=2;const pulsing=.4+Math.sin(t*16)*.13;this.circle(hazard.x,hazard.y,hazard.r,hazard.delay>0?"#702b5559":"#dc6d8477","#ffd0b2");c.globalAlpha=pulsing;this.circle(hazard.x,hazard.y,hazard.r-7,null,"#fa9b87");c.globalAlpha=1;if(hazard.delay>0){c.strokeStyle="#ffdfba";c.lineWidth=3;c.beginPath();c.arc(hazard.x,hazard.y,hazard.r*(1-Math.max(0,hazard.delay)/1.1),0,TAU);c.stroke();}else this.glow(hazard.x,hazard.y,hazard.r*2,"red",.6);}
if(g.bladeSwing&&g.bladeSwing.elapsed<BLADE_TIMING.windup){const u=g.bladeSwing.elapsed/BLADE_TIMING.windup;c.save();c.translate(p.x,p.y-18);c.rotate(g.bladeSwing.angle);c.globalAlpha=.18+u*.2;c.strokeStyle="#d6ba73";c.lineWidth=1.2;c.beginPath();c.arc(0,0,23+u*9,-1.6,-.5);c.stroke();this.glow(18,-22,23,"gold",u*.24);c.restore();}
for(const fx of g.fx)if(fx.kind==="ghost")this.effect(fx,t,g);
this.visible.length=0;for(const e of g.enemies)if(Math.abs(e.x-cx)<w/2+90&&Math.abs(e.y-cy)<h/2+120)this.visible.push(e);for(const [x,y,height,face]of this.groves)if(Math.abs(x-cx)<w/2+height*.5&&Math.abs(y-cy)<h/2+height)this.visible.push({prop:true,x,y,height,face});this.visible.push({player:true,y:p.y});this.visible.sort((a,b)=>a.y-b.y);
for(const e of this.visible){if(e.prop){c.save();const overlaps=Math.abs(e.x-p.x)<e.height*.46&&p.y>e.y-e.height*.76&&p.y<e.y+e.height*.28;c.globalAlpha=overlaps?.15:.60;drawSprite(c,"grove",e.x,e.y,e.height,e.face);c.restore();continue;}if(e.player){const attacking=!!g.bladeSwing,face=attacking?Math.cos(g.bladeSwing.angle)>=0?1:-1:p.dirX>=0?1:-1;c.save();if(p.inv>0)c.globalAlpha=.7+Math.sin(t*22)*.2;drawHero(c,g.hero,p.x,p.y,2.6,face,t,p.dash>0||joy.active||joy.keyboard,attacking,p.inv>0&&t<f.flash?.6:0,g.bladeSwing,!this.reduced);c.restore();if(p.dash>0){this.glow(p.x,p.y,65,"mint",.32);}if(p.inv>0){c.lineWidth=1;this.circle(p.x,p.y,23,null,"#b4f3d76f");}}else this.enemy(e,t,p);}
const lv=g.weapons.orbit;if(lv){const evo=!!g.evolved?.orbit,n=evo?6:2+Math.floor(lv/2),r=64+lv*6+(evo?20:0);c.lineWidth=.6;this.circle(p.x,p.y,r,null,"#d6c0f533");for(let i=0;i<n;i++){const a=g.time*2.6+i*TAU/n,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;this.glow(x,y,32,evo?"gold":"violet",.7);star(c,x,y,9,evo?"#fff0bf":"#f0cfff");star(c,x,y,4,"#fffaff");}}
for(const b of g.bullets)if(Math.abs(b.x-cx)<w/2+45&&Math.abs(b.y-cy)<h/2+45)this.projectile(b);
for(const b of g.shots)if(Math.abs(b.x-cx)<w/2+25&&Math.abs(b.y-cy)<h/2+25)this.projectile(b,true);
let decorative=0;for(const fx of g.fx){if(fx.kind==="ghost"||Math.abs(fx.x-cx)>w/2+(fx.r||80)||Math.abs(fx.y-cy)>h/2+(fx.r||80))continue;if(["impact","text","burst"].includes(fx.kind)&&++decorative>(this.quality<.8?24:56))continue;this.effect(fx,t,g);}
c.restore();if(!this.reduced&&this.quality>.7){c.save();c.globalAlpha=.06;const light=c.createLinearGradient(0,0,w,h);light.addColorStop(0,"#ffeda9");light.addColorStop(1,"#ffeda900");c.fillStyle=light;c.beginPath();c.moveTo(w*.8,0);c.lineTo(w*.99,0);c.lineTo(w*.47,h*.68);c.lineTo(w*.04,h*.68);c.closePath();c.fill();c.restore();}c.fillStyle=this.vignette;c.fillRect(0,0,w,h);
if(!this.reduced&&t<f.flash){c.fillStyle=p.inv>0&&p.hp<p.maxHp*.45?"#df84741c":"#ffe8a916";c.fillRect(0,0,w,h);}
if(joy.active){c.lineWidth=1.5;this.circle(joy.ox,joy.oy,43,"#071f2055","#ecd9a66e");this.circle(joy.ox+joy.x*37,joy.oy+joy.y*37,18,"#c6d8bd50","#f6e5b2a0");}
}
}
