import test from "node:test";
import assert from "node:assert/strict";
import {Audio,AUDIO_DESIGN,SAMPLES} from "../src/audio.js";
function spy(){const a=new Audio(),calls=[];let now=1;a.context={get currentTime(){return now;}};a.play=(name,options)=>calls.push({name,...options});return {a,calls,time:n=>now=n};}
test("all thirty-six attacks have material routes and empty contacts are silent",()=>{assert.equal(Object.keys(AUDIO_DESIGN.materials).length,36);assert.equal(SAMPLES.length,35);for(const key of Object.keys(AUDIO_DESIGN.materials)){const {a,calls}=spy();a.event("skill-contact",key,{hits:0});a.event("skill-finish",key,{hits:0});a.event("projectile-contact",key,{hits:0});assert.equal(calls.length,0,key);a.event("skill-release",key);if(key!=="blade"&&key!=="arrow"&&key!=="bolt"&&key!=="orbit")assert.ok(calls.length>0,key);assert.ok(!calls.some(c=>["magic","arrow","ultimate"].includes(c.name)),key+" used old tonal effect");}});
test("visual compatibility and damage over time never trigger per-tick impact voices",()=>{const {a,calls,time}=spy();for(let i=0;i<100;i++){time(1+i*.02);for(const key of ["bleed","poison-dot","burn","thorns"]){a.event("impact",key,{hits:1});a.event("skill-contact",key,{hits:1});}}assert.equal(calls.length,0);a.event("skill-impact","crosscut",{hits:0});assert.equal(calls.length,0);a.event("skill-impact","meteor",{hits:0,ground:true});assert.deepEqual(calls.map(c=>c.name),["stone-impact","fire-impact"]);});
test("continuous contact density and tails are bounded independently of tick count",()=>{for(const key of ["beam","dragon","blackflame","frost"]){const {a,calls,time}=spy();for(let i=0;i<60;i++){time(1+i/60);a.event("skill-contact",key,{hits:4,phase:"sustain",strong:true});}assert.ok(calls.length>=2&&calls.length<=4,key);assert.ok(calls.every(c=>c.gain<.3&&c.duration<=.2),key);}});
test("stage-five launch and finish have different material mixes with duplicate finish suppression",()=>{const signatures=[];for(const key of ["thousand","ballista","dragon"]){const {a,calls,time}=spy();a.event("skill-release",key,{id:8,evolved:true});const release=calls.map(c=>c.name).join(",");calls.length=0;time(2);a.event("skill-finish",key,{hits:3,phase:"finish"});const finish=calls.map(c=>c.name).join(","),count=calls.length;assert.notEqual(release,finish);assert.ok(count>=2);a.event("skill-contact",key,{hits:1,phase:"finish"});assert.equal(calls.length,count);signatures.push(release);}assert.equal(new Set(signatures).size,3);});
function fakeContext(){const sources=[],makeGain=()=>({gain:{setValueAtTime(){},linearRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}},connect(){},disconnect(){}});return {sources,state:"running",currentTime:1,sampleRate:8000,suspend:()=>Promise.resolve(),createGain:makeGain,createBiquadFilter:()=>({frequency:{value:0},Q:{value:0},connect(){},disconnect(){}}),createBuffer:(channels,length,rate)=>{const data=new Float32Array(length);return {duration:length/rate,sampleRate:rate,getChannelData:()=>data};},createBufferSource(){const s={playbackRate:{value:1},connect(){},disconnect(){},starts:[],stops:[],start(...args){this.starts.push(args);},stop(...args){this.stops.push(args);}};sources.push(s);return s;}};}
test("voice stealing protects hurt feedback and pause stops active and retiring sources",()=>{const saved=globalThis.document;globalThis.document={hidden:false};try{const c=fakeContext(),a=new Audio();a.context=c;a.master=c.createGain();a.wantsPlayback=true;a.buffers.set("noise",{duration:2});for(let i=0;i<18;i++)a.play("noise",{group:"test"+Math.floor(i/4),priority:2});assert.equal(a.voices.size,18);const hurt=a.play("noise",{group:"impact",priority:10});assert.ok(hurt);assert.equal(a.voices.size,18);assert.equal(a.retiring.size,1);assert.ok(a.stats.stolen>=1);assert.ok(hurt.starts[0][0]>=c.currentTime+.009);for(let i=0;i<8;i++)a.play("noise",{group:"impact",priority:1});assert.ok(a.voices.has(hurt));a.stop();assert.equal(a.voices.size,0);assert.equal(a.retiring.size,0);assert.equal(a.wantsPlayback,false);assert.ok(c.sources.every(s=>s.stops.length>0));}finally{if(saved===undefined)delete globalThis.document;else globalThis.document=saved;}});
test("licensed material palettes are cached, finite and peak limited without adding asset requests",()=>{const c=fakeContext(),a=new Audio();for(const [i,name]of SAMPLES.entries()){const b=c.createBuffer(1,16000,8000),d=b.getChannelData(0);for(let j=0;j<d.length;j++)d[j]=Math.sin(j*(.023+i*.001));a.buffers.set(name,b);}const original=a.buffers.get("bolt-release");a.buildPalette(c);assert.equal(a.palette.size,8);assert.equal(a.buffers.size,35);assert.notEqual(a.buffers.get("bolt-release"),original);for(const b of a.palette.values()){const d=b.getChannelData(0);assert.ok(d.some(x=>Math.abs(x)>.001));assert.ok(d.every(x=>Number.isFinite(x)&&Math.abs(x)<=.901));}const first=a.palette.get("dragon-sustain");a.buildPalette(c);assert.equal(a.palette.get("dragon-sustain"),first);});

test("gravity finishing collapse is not doubled by its ground event and misses keep physical scenery sound",()=>{const {a,calls,time}=spy();a.event("skill-contact","gravity",{hits:1,phase:"finish"});a.event("skill-impact","gravity",{hits:1,phase:"finish",ground:true});a.event("skill-finish","gravity",{hits:1,phase:"finish"});assert.equal(calls.filter(c=>c.name==="gravity-collapse").length,1);calls.length=0;time(2);a.event("skill-impact","gravity",{hits:0,ground:true,phase:"finish"});assert.equal(calls.filter(c=>c.name==="gravity-collapse").length,1);});

test("signature ducking preserves important foreground cues and restores the bed on pause",()=>{const saved=globalThis.document;globalThis.document={hidden:false};try{const c=fakeContext(),a=new Audio(),automation=[],makeGain=c.createGain;c.createGain=()=>{const node=makeGain();node.connect=destination=>{node.destination=destination;};return node;};a.context=c;a.master=c.createGain();a.combatBed=c.createGain();a.foreground=c.createGain();a.combatBed.gain.cancelScheduledValues=t=>automation.push({method:"cancel",t});a.combatBed.gain.setTargetAtTime=(value,t)=>automation.push({method:"target",value,t});a.combatBed.gain.setValueAtTime=(value,t)=>automation.push({method:"value",value,t});a.wantsPlayback=true;a.buffers.set("test",{duration:2});c.currentTime=2;
a.focus("thousand",.30,.28);const normal=a.play("test",{group:"swing",priority:4}),finish=a.play("test",{group:"impact",priority:8});assert.equal(normal.volume.destination,a.combatBed);assert.equal(finish.volume.destination,a.foreground);assert.ok(automation.some(e=>e.method==="target"&&e.value<.5));assert.ok(automation.findLast(e=>e.method==="target"&&e.value===1).t>=2.30);
c.currentTime=2.15;a.focus("thousand",.50,.36);assert.ok(automation.some(e=>e.method==="cancel"&&e.t===2.15));assert.ok(automation.findLast(e=>e.method==="target"&&e.value===1).t>=2.65);
a.stop();assert.deepEqual(automation.at(-1),{method:"value",value:1,t:2.15});assert.equal(a.signatureUntil,0);assert.equal(a.signatureKey,null);assert.equal(a.wantsPlayback,false);
}finally{if(saved===undefined)delete globalThis.document;else globalThis.document=saved;}});
test("ambient recovery ignores stale epochs, hidden pages and stopped playback",()=>{const saved=globalThis.document;globalThis.document={hidden:false};try{const c=fakeContext(),a=new Audio();a.context=c;a.master=c.createGain();a.wantsPlayback=true;a.buffers.set("test",{duration:2});let recoveries=0;a.music=()=>recoveries++;
const stale=a.play("test",{group:"swing"});a.stop();stale.onended();assert.equal(recoveries,0);
a.wantsPlayback=true;c.state="running";stale.onended();assert.equal(recoveries,0);
const current=a.play("test",{group:"swing"});current.onended();assert.equal(recoveries,1);
const hidden=a.play("test",{group:"swing"});globalThis.document.hidden=true;hidden.onended();assert.equal(recoveries,1);
globalThis.document.hidden=false;const disabled=a.play("test",{group:"swing"});a.enabled=false;disabled.onended();assert.equal(recoveries,1);a.enabled=true;
const suspended=a.play("test",{group:"swing"});c.state="suspended";suspended.onended();assert.equal(recoveries,1);a.stop();
}finally{if(saved===undefined)delete globalThis.document;else globalThis.document=saved;}});
