import test from "node:test";
import assert from "node:assert/strict";
import {Audio,AUDIO_DESIGN,SAMPLES} from "../src/audio.js";
function spy(){const a=new Audio(),calls=[];let now=1;a.context={get currentTime(){return now;}};a.play=(name,options)=>calls.push({name,...options});return {a,calls,time:n=>now=n};}
test("all thirty-six attacks have material routes and empty contacts are silent",()=>{assert.equal(Object.keys(AUDIO_DESIGN.materials).length,36);assert.equal(SAMPLES.length,29);for(const key of Object.keys(AUDIO_DESIGN.materials)){const {a,calls}=spy();a.event("skill-contact",key,{hits:0});a.event("skill-finish",key,{hits:0});a.event("projectile-contact",key,{hits:0});assert.equal(calls.length,0,key);a.event("skill-release",key);if(key!=="blade"&&key!=="arrow"&&key!=="bolt"&&key!=="orbit")assert.ok(calls.length>0,key);assert.ok(!calls.some(c=>["magic","arrow","ultimate"].includes(c.name)),key+" used old tonal effect");}});
test("visual compatibility and damage over time never trigger per-tick impact voices",()=>{const {a,calls,time}=spy();for(let i=0;i<100;i++){time(1+i*.02);for(const key of ["bleed","poison-dot","burn","thorns"]){a.event("impact",key,{hits:1});a.event("skill-contact",key,{hits:1});}}assert.equal(calls.length,0);a.event("skill-impact","crosscut",{hits:0});assert.equal(calls.length,0);a.event("skill-impact","meteor",{hits:0,ground:true});assert.deepEqual(calls.map(c=>c.name),["stone-impact","fire-impact"]);});
test("continuous contact density and tails are bounded independently of tick count",()=>{for(const key of ["beam","dragon","blackflame","frost"]){const {a,calls,time}=spy();for(let i=0;i<60;i++){time(1+i/60);a.event("skill-contact",key,{hits:4,phase:"sustain",strong:true});}assert.ok(calls.length>=2&&calls.length<=4,key);assert.ok(calls.every(c=>c.gain<.3&&c.duration<=.2),key);}});
test("stage-five launch and finish have different material mixes with duplicate finish suppression",()=>{const signatures=[];for(const key of ["thousand","ballista","dragon"]){const {a,calls,time}=spy();a.event("skill-release",key,{id:8,evolved:true});const release=calls.map(c=>c.name).join(",");calls.length=0;time(2);a.event("skill-finish",key,{hits:3,phase:"finish"});const finish=calls.map(c=>c.name).join(","),count=calls.length;assert.notEqual(release,finish);assert.ok(count>=2);a.event("skill-contact",key,{hits:1,phase:"finish"});assert.equal(calls.length,count);signatures.push(release);}assert.equal(new Set(signatures).size,3);});
function fakeContext(){const sources=[],makeGain=()=>({gain:{setValueAtTime(){},linearRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}},connect(){},disconnect(){}});return {sources,state:"running",currentTime:1,sampleRate:8000,suspend:()=>Promise.resolve(),createGain:makeGain,createBiquadFilter:()=>({frequency:{value:0},Q:{value:0},connect(){},disconnect(){}}),createBuffer:(channels,length,rate)=>{const data=new Float32Array(length);return {duration:length/rate,sampleRate:rate,getChannelData:()=>data};},createBufferSource(){const s={playbackRate:{value:1},connect(){},disconnect(){},starts:[],stops:[],start(...args){this.starts.push(args);},stop(...args){this.stops.push(args);}};sources.push(s);return s;}};}
test("voice stealing protects hurt feedback and pause stops active and retiring sources",()=>{const saved=globalThis.document;globalThis.document={hidden:false};try{const c=fakeContext(),a=new Audio();a.context=c;a.master=c.createGain();a.wantsPlayback=true;a.buffers.set("noise",{duration:2});for(let i=0;i<18;i++)a.play("noise",{group:"test"+Math.floor(i/4),priority:2});assert.equal(a.voices.size,18);const hurt=a.play("noise",{group:"impact",priority:10});assert.ok(hurt);assert.equal(a.voices.size,18);assert.equal(a.retiring.size,1);assert.ok(a.stats.stolen>=1);assert.ok(hurt.starts[0][0]>=c.currentTime+.009);for(let i=0;i<8;i++)a.play("noise",{group:"impact",priority:1});assert.ok(a.voices.has(hurt));a.stop();assert.equal(a.voices.size,0);assert.equal(a.retiring.size,0);assert.equal(a.wantsPlayback,false);assert.ok(c.sources.every(s=>s.stops.length>0));}finally{if(saved===undefined)delete globalThis.document;else globalThis.document=saved;}});
test("recorded Foley palettes are cached, finite and peak limited without adding asset requests",()=>{const c=fakeContext(),a=new Audio();for(const [i,name]of SAMPLES.entries()){const b=c.createBuffer(1,16000,8000),d=b.getChannelData(0);for(let j=0;j<d.length;j++)d[j]=Math.sin(j*(.023+i*.001));a.buffers.set(name,b);}const original=a.buffers.get("bolt-release");a.buildPalette(c);assert.equal(a.palette.size,7);assert.equal(a.buffers.size,29);assert.notEqual(a.buffers.get("bolt-release"),original);for(const b of a.palette.values()){const d=b.getChannelData(0);assert.ok(d.some(x=>Math.abs(x)>.001));assert.ok(d.every(x=>Number.isFinite(x)&&Math.abs(x)<=.901));}const first=a.palette.get("dragon-breath");a.buildPalette(c);assert.equal(a.palette.get("dragon-breath"),first);});
