import test from "node:test";import assert from "node:assert/strict";
import {Game,HEROES,weaponSlots,LIMITS,cleanSave,reward} from "../src/core.js";
import {STAGES,STAGE_SKILLS,STAGE_SKILL_ROWS,CAMPAIGN_ENEMIES} from "../src/campaign.js";
function fixture(hero="knight",stage=1){const g=new Game(hero,{},17);g.stage=stage;g.weapons={};g.player.inv=999;g.spawnCd=g.nextElite=g.nextMagnet=9999;g.hitStopEnabled=false;return g;}
function target(g,x=1020,y=900){const e=g.spawn("brute");Object.assign(e,{x,y,hp:30000,maxHp:30000,speed:0,shoot:999});return e;}
function frames(g,n){for(let i=0;i<n;i++)g.step(1/60);}
test("five boss defeats progress in order and only the fifth settles a victory",()=>{const g=fixture();for(let stage=1;stage<=5;stage++){assert.equal(g.stage,stage);const boss=g.spawnBoss();assert.equal(boss.maxHp,STAGES[stage-1].bossHp);g.hit(boss,999999,g.player);assert.equal(g.clearedStages,stage);if(stage<5){assert.equal(g.phase,"stage-clear");assert.equal(g.result,null);const now=g.time,kills=g.kills;frames(g,120);assert.equal(g.time,now);assert.equal(g.kills,kills);assert.ok(g.advanceStage());assert.equal(g.advanceStage(),false);assert.equal(g.stageTime,0);}else{assert.equal(g.phase,"result");assert.equal(g.result.win,true);assert.equal(g.result.clearedStages,5);assert.equal(g.advanceStage(),false);}}assert.equal(g.events.filter(e=>e.type==="result").length,1);assert.equal(g.stageHistory.length,5);assert.equal(reward(cleanSave(),g.result).wins,1);});
test("region transition keeps the build and XP, heals once, clears danger and grants the matching skill",()=>{for(const hero of HEROES){const g=new Game(hero.id,{},17);g.level=15;g.xp=31;g.passives={power:2,heart:1};g.weapons[hero.weapon]=5;g.evolved[hero.weapon]=true;g.player.hp=20;g.player.ultCd=15;g.player.dashCd=3;const before={level:g.level,xp:g.xp,max:g.player.maxHp};g.time=350;g.clearStage();assert.equal(g.result,null);g.bullets=[{x:900}];g.skillFields=[{key:"meteor"}];g.skillTasks=[{key:"slam"}];g.hazards=[{x:900}];g.enemies=[{hp:1}];assert.ok(g.advanceStage());assert.equal(g.player.hp,20+before.max*.5);assert.equal(g.level,before.level);assert.equal(g.xp,before.xp);assert.equal(g.evolved[hero.weapon],true);assert.equal(g.passives.power,2);const key=STAGE_SKILL_ROWS.find(r=>r[6]===hero.id&&r[7]===2)[0];assert.equal(g.weapons[key],1);assert.equal(g.player.dashCd,0);assert.equal(g.player.ultCd,0);assert.equal(weaponSlots(g.level,g.stage),7);assert.equal(g.advanceStage(),false);assert.equal(g.player.hp,20+before.max*.5);}});
test("stage countdown is relative to arrival, not the accumulated survival clock",()=>{const g=fixture();g.time=487;g.clearStage();g.advanceStage();g.spawnCd=g.nextElite=99999;g.stageStarted=487;g.time=487+STAGES[1].duration-.02;g.step(.01);assert.equal(g.bossSpawned,false);g.step(.02);assert.equal(g.bossSpawned,true);const boss=g.enemies.find(e=>e.boss);assert.equal(boss.hp,STAGES[1].bossHp);});
test("each later region adds exactly three class-specific techniques and rejects early forged choices",()=>{assert.equal(Object.keys(STAGE_SKILLS).length,12);for(let stage=2;stage<=5;stage++){const rows=STAGE_SKILL_ROWS.filter(r=>r[7]===stage);assert.equal(rows.length,3);assert.equal(new Set(rows.map(r=>r[6])).size,3);}for(const hero of HEROES){const g=fixture(hero.id);for(const [key,u]of Object.entries(STAGE_SKILLS)){g.phase="upgrade";g.pending=1;g.choices=[key];assert.equal(g.choose(key),false);}g.phase="playing";for(let stage=2;stage<=5;stage++){g.clearStage();g.advanceStage();const newest=STAGE_SKILL_ROWS.find(r=>r[6]===hero.id&&r[7]===stage)[0];assert.equal(g.weapons[newest],1);assert.ok(g.offer().includes(newest));for(let i=0;i<40;i++)for(const k of g.offer()){if(STAGE_SKILLS[k]){assert.equal(STAGE_SKILLS[k].hero,hero.id);assert.ok(STAGE_SKILLS[k].stage<=stage);}}}}});
for(const [key,u]of Object.entries(STAGE_SKILLS))test(key+" deals real damage at Lv.1/3/5, pauses cleanly and respects entity limits",()=>{const dealt=[];for(const lv of [1,3,5]){const g=fixture(u.hero,u.stage),e=target(g);g.attack(key,lv);const delay=g.skillTasks[0]?.delay;g.pause();frames(g,40);assert.equal(e.hp,30000);assert.equal(g.skillTasks[0]?.delay,delay);g.resume();frames(g,210);assert.ok(Number.isFinite(e.hp)&&e.hp<30000);dealt.push(30000-e.hp);assert.ok(g.skillFields.length<=LIMITS.fields);assert.ok(g.bullets.length<=LIMITS.bullets);assert.ok(g.skillTasks.length<=LIMITS.tasks);}assert.ok(dealt[1]>dealt[0]&&dealt[2]>dealt[1]);});
test("storm arrows chain to actual nearby targets and do not hit an isolated target",()=>{const g=fixture("ranger",4),a=target(g,1010),b=target(g,1110,940),far=target(g,1550,1300);g.attack("stormbow",3);frames(g,60);assert.ok(a.hp<30000);assert.ok(b.hp<30000);assert.equal(far.hp,30000);assert.ok(g.events.some(e=>e.type==="skill-impact"&&e.key==="stormbow"));});
test("region HP, boss HP and contact damage increase without changing the first region",()=>{assert.equal(STAGES[0].bossHp,5600);for(let stage=2;stage<=5;stage++){assert.ok(STAGES[stage-1].hp>STAGES[stage-2].hp);assert.ok(STAGES[stage-1].bossHp>STAGES[stage-2].bossHp);}const a=fixture("mage",1),b=fixture("mage",5);a.time=b.time=100;assert.ok(b.spawn("brute").hp>a.spawn("brute").hp);assert.ok(STAGES.slice(1).every(s=>s.pool.some(k=>CAMPAIGN_ENEMIES[k])));});
test("shield blocks the front but leaves its back vulnerable",()=>{const g=fixture("knight",2),e=g.spawn("guard");e.faceAngle=0;e.hp=1000;g.hit(e,100,{x:e.x+100,y:e.y});assert.equal(e.hp,945);g.hit(e,100,{x:e.x-100,y:e.y});assert.equal(e.hp,845);});
test("enemy telegraphs delay sniper shots, explosions and ice zones; healing stays capped",()=>{const s=fixture("ranger",4),sniper=s.spawn("sniper");Object.assign(sniper,{x:1150,y:900,shoot:0,speed:0});frames(s,30);assert.ok(sniper.aim);assert.equal(s.shots.length,0);frames(s,40);assert.ok(s.shots.length>0);
const b=fixture("mage",2),bomber=b.spawn("bomber");Object.assign(bomber,{x:1020,y:900,speed:0});frames(b,30);assert.ok(bomber.fuse>0);assert.equal(b.hazards.length,0);frames(b,30);assert.ok(b.events.some(e=>e.type==="enemy-burst"));
const h=fixture("knight",3),healer=h.spawn("healer"),ally=h.spawn("shade");Object.assign(healer,{x:1150,y:900,shoot:0,speed:0});Object.assign(ally,{x:1160,y:900,hp:1,speed:0});frames(h,1);assert.ok(ally.hp>1&&ally.hp<=ally.maxHp);
const f=fixture("mage",4),ice=f.spawn("frostling");ice.shoot=0;frames(f,1);assert.ok(f.hazards.some(x=>x.ice&&x.delay>1));});
test("later bosses have distinct bounded telegraphed patterns and pause freezes them",()=>{for(let stage=2;stage<=5;stage++){const g=fixture("knight",stage),e=g.spawnBoss();e.shoot=e.storm=999;e.special=0;frames(g,1);assert.ok(g.hazards.length||g.shots.length);const snapshot=JSON.stringify([g.hazards,g.shots]);g.pause();frames(g,100);assert.equal(JSON.stringify([g.hazards,g.shots]),snapshot);assert.ok(g.shots.length<=LIMITS.shots);}});
test("retiring between regions settles a loss once and cannot resume the campaign",()=>{const g=fixture();g.kills=240;g.level=20;g.clearStage();g.finish(false);const r=g.result;assert.equal(r.win,false);assert.equal(r.clearedStages,1);assert.equal(g.advanceStage(),false);g.finish(true);assert.equal(g.result,r);});
