import test from "node:test";
import assert from "node:assert/strict";
import {Game,CLASS_SKILLS,SKILL_STAGES,upgradeDetail,UPGRADES,LIMITS} from "../src/core.js";
import {Audio,SAMPLES} from "../src/audio.js";
function fixture(hero="knight"){const g=new Game(hero,{},17);g.weapons={};g.spawnCd=g.nextElite=g.nextMagnet=999;g.player.inv=999;g.hitStopEnabled=false;return g;}
function enemy(g,x=1000,y=900){const e=g.spawn("brute");Object.assign(e,{x,y,hp:9999,maxHp:9999,speed:0,shoot:999});return e;}
function frames(g,n){for(let i=0;i<n;i++)g.step(1/60);}
test("thirty-six class attacks have two explicit transformation milestones and legal discovery",()=>{assert.equal(Object.keys(SKILL_STAGES).length,36);for(const [hero,keys]of Object.entries(CLASS_SKILLS)){assert.equal(keys.length,12);const g=fixture(hero);g.stage=5;for(const key of keys){for(const lv of [2,4]){g.weapons={[key]:lv};const d=upgradeDetail(g,key);assert.equal(d.awakening,SKILL_STAGES[key][lv===2?0:1]);g.phase="upgrade";g.pending=1;g.choices=[key];assert.ok(g.choose(key));assert.ok(g.events.some(e=>e.type==="awaken"&&e.key===key&&e.level===lv+1));g.events=[];}}}});
test("new attacks at level one, three and five deal finite real damage",()=>{for(const [hero,keys]of [["knight",["hammer","fissure"]],["ranger",["ricochet","glaive"]],["mage",["beam","pyre"]]])for(const key of keys)for(const lv of [1,3,5]){const g=fixture(hero),targets=Array.from({length:8},(_,i)=>enemy(g,980+i*15,900+(i-4)*8));g.attack(key,lv);frames(g,125);assert.ok(targets.some(e=>e.hp<9999),key+" Lv."+lv+" has no real damage");assert.ok(targets.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.x)));assert.ok(g.skillFields.length<=LIMITS.fields);assert.ok(g.bullets.length<=LIMITS.bullets);}});
test("returning crescents acquire a second blade then hit on outward and return travel",()=>{for(const [lv,count]of [[1,1],[3,2],[5,2]]){const g=fixture("ranger"),e=enemy(g,1020);g.attack("glaive",lv);g.advanceSkills(.14);assert.equal(g.bullets.length,count);assert.ok(g.bullets.every(b=>b.resetOnReturn===(lv>=5)));frames(g,38);assert.ok(e.hp<9999);assert.ok(g.bullets.some(b=>b.returning));}});
test("ricochet travels to each target and never damages the same target twice",()=>{const g=fixture("ranger"),targets=[enemy(g,1010),enemy(g,1130),enemy(g,1250),enemy(g,1330)];g.attack("ricochet",3);frames(g,90);const hit=targets.filter(e=>e.hp<9999);assert.equal(hit.length,4);for(const e of hit)assert.ok(Math.abs((9999-e.hp)-16*1.64)<1e-8);});
test("fissures and fire pillars keep their sequential anticipation and freeze on pause",()=>{for(const [hero,key]of [["knight","fissure"],["mage","pyre"]]){const g=fixture(hero);enemy(g);g.attack(key,3);g.advanceSkills(.25);assert.ok(g.skillFields.length>=4);assert.ok(g.skillFields[1].delay>g.skillFields[0].delay);const delays=g.skillFields.map(f=>f.delay);g.pause();frames(g,60);assert.deepEqual(g.skillFields.map(f=>f.delay),delays);g.resume();frames(g,80);assert.ok(g.events.filter(e=>e.type==="skill-impact"&&e.key===key).length>=4);}});
test("beam hits a line over time and leaves off-axis enemies untouched",()=>{const g=fixture("mage"),near=enemy(g,1000),far=enemy(g,1200),side=enemy(g,1000,1030);g.attack("beam",1);frames(g,20);assert.ok(near.hp<9999&&far.hp<9999);assert.equal(side.hp,9999);const hp=near.hp;frames(g,25);assert.ok(near.hp<hp);g.pause();const ttl=g.skillFields[0].ttl;frames(g,40);assert.equal(g.skillFields[0].ttl,ttl);});
test("sword awakens into delayed extra cuts and whirlwind pulls enemies",()=>{const g=fixture(),e=enemy(g,980);g.attack("blade",3);g.advanceBlade(.15);assert.equal(g.skillTasks.filter(t=>t.key==="blade-echo").length,1);const hp=e.hp;g.advanceSkills(.14);assert.ok(e.hp<hp);const w=fixture(),target=enemy(w,1005);w.attack("whirlwind",3);w.advanceSkills(.15);const x=target.x;w.advanceSkills(.2);assert.ok(target.x<x);});
test("fire, poison and traps gain persistent fields only after their level milestone",()=>{for(const [hero,key,field]of [["mage","fireball","burn"],["ranger","poison","poison"],["ranger","trap","thorns"]]){for(const lv of [1,3]){const g=fixture(hero);enemy(g,key==="trap"?925:1010);g.attack(key,lv);frames(g,45);assert.equal(g.skillFields.some(f=>f.key===field),lv>=3,key);}}});
test("bleeding deaths create a deferred burst without recursive immediate settlement",()=>{const g=fixture(),a=enemy(g,980),b=enemy(g,1040,935);g.attack("rend",3);frames(g,15);assert.ok(a.statuses.bleed.burst>0);const hp=b.hp;g.damageKey="bleed";g.hit(a,99999,g.player);assert.ok(g.skillTasks.some(t=>t.key==="death-burst"));frames(g,6);assert.ok(b.hp<hp);});
test("combat audio has recorded material routes and bounded beam pulse density",()=>{assert.equal(SAMPLES.length,29);const a=new Audio(),calls=[];let now=1;a.context={get currentTime(){return now;}};a.play=(name,options)=>calls.push({name,...options});a.event("skill-release","fireball");a.event("skill-impact","slam");a.event("projectile-contact","poison");a.event("skill-release","whirlwind");assert.deepEqual(calls.map(x=>x.name),["fire-cast","stone-impact","poison-impact","whirlwind","swish-a"]);calls.length=0;for(let i=0;i<15;i++){now=2+i*.05;a.event("skill-pulse","beam");}assert.ok(calls.length>=2&&calls.length<=3);assert.ok(calls.every(x=>x.name==="void-impact"));});

test("new projectile contacts keep arrow, metal and stone materials distinct",()=>{for(const [hero,key,kind]of [["knight","hammer","cut-hit"],["ranger","glaive","cut-hit"],["ranger","ricochet","arrow-hit"]]){const g=fixture(hero);enemy(g,980);g.attack(key,1);frames(g,25);assert.ok(g.fx.some(f=>f.kind===kind&&f.key===key),key+" contact uses wrong material");assert.ok(!g.fx.some(f=>f.kind==="bolt-hit"&&f.key===key));}});

test("transformed multi-projectile cards display the real damage of each projectile",()=>{for(const [hero,key,lv]of [["knight","cleave",2],["ranger","piercing",4],["mage","fireball",4]]){const g=fixture(hero);g.weapons[key]=lv;enemy(g);const detail=upgradeDetail(g,key);g.attack(key,lv+1);g.advanceSkills(.25);assert.ok(g.bullets.length>0);assert.ok(detail.stat.includes(String(Math.round(g.bullets[0].damage))),key+" displayed damage differs from combat");}});

test("whirlwind pulls distant enemies toward its edge without sucking close enemies into the hero",()=>{const g=fixture(),near=enemy(g,970),far=enemy(g,1020);g.attack("whirlwind",3);g.advanceSkills(.15);assert.ok(near.x>=970,"Close enemy was pulled into contact range");assert.ok(far.x<1020,"Distant enemy did not move toward the attack");});
