import test from "node:test";
import assert from "node:assert/strict";
import {Game,HEROES,UPGRADES,LIMITS,cleanSave,purchase,reward} from "../src/core.js";
test("invalid saves normalize without negative currency or invalid upgrades",()=>{
for(const raw of ["broken","null","[]","4",null])assert.equal(cleanSave(raw).coins,0);
const s=cleanSave({coins:-4,best:Infinity,meta:{power:90,heart:-3},settings:{sound:false}});
assert.equal(s.coins,0);assert.deepEqual(s.meta,{power:5,heart:0,fortune:0});assert.equal(s.settings.sound,false);});
test("permanent purchases charge once, enforce limits and leave input untouched",()=>{
const source=cleanSave({coins:100}),r=purchase(source,"power");assert.equal(r.ok,true);assert.equal(r.save.coins,60);assert.equal(r.save.meta.power,1);assert.equal(source.coins,100);assert.equal(purchase(r.save,"power").ok,false);assert.equal(purchase({coins:900,meta:{power:5}},"power").ok,false);assert.equal(purchase(source,"invalid").ok,false);});
test("three heroes have distinct weapons and receive persistent buffs",()=>{for(const h of HEROES){const g=new Game(h.id,{heart:2,power:3});assert.equal(g.player.maxHp,h.hp+20);assert.deepEqual(g.weapons,{[h.weapon]:1});assert.ok(Math.abs(g.damageScale()-1.18)<1e-9);}});
test("pause and upgrade freeze simulation; earned levels need separate choices",()=>{
const g=new Game();g.addXP(20);assert.equal(g.level,3);assert.equal(g.pending,2);assert.equal(g.phase,"upgrade");g.step(.05);assert.equal(g.time,0);assert.equal(g.choose("bogus"),false);g.choose(g.choices[0]);assert.equal(g.phase,"upgrade");g.choose(g.choices[0]);assert.equal(g.phase,"playing");g.pause();g.step(.05);assert.equal(g.time,0);g.resume();g.step(.05);assert.ok(g.time>0);});
test("offered choices respect weapon slots and level caps",()=>{const g=new Game();g.weapons={blade:5,arrow:2,bolt:2,orbit:2};for(let i=0;i<100;i++)for(const k of g.offer()){assert.notEqual(k,"blade");assert.ok(UPGRADES[k].kind!=="weapon"||k in g.weapons);}});
test("diagonal movement normalizes, large time steps clamp, and arena bounds hold",()=>{
const a=new Game(),b=new Game();a.step(.05,{x:1,y:0});b.step(.05,{x:1,y:1});assert.ok(Math.abs(Math.hypot(b.player.x-900,b.player.y-900)-(a.player.x-900))<1e-8);
b.player.x=1774;b.step(.05,{x:1,y:0});assert.equal(b.player.x,1775);const t=b.time;b.step(100,{x:1,y:0});assert.ok(b.time-t<=.05000001);});
test("dash preserves a zero axis, grants invulnerability and enforces cooldown",()=>{const g=new Game();assert.equal(g.dash(0,1),true);assert.equal(g.player.dirX,0);assert.equal(g.hurt(20),false);assert.equal(g.dash(1,0),false);g.step(.05);assert.equal(g.player.x,900);assert.ok(g.player.y>900);});
test("fast projectiles use swept collision and do not damage the same enemy twice",()=>{
const g=new Game("ranger"),e=g.spawn("shade");Object.assign(e,{x:920,y:900,speed:0,hp:100,maxHp:100});g.cool.arrow=99;g.bullets=[{x:890,y:900,vx:1600,vy:0,r:4,key:"arrow",ttl:1,damage:20,pierce:2,hit:[]}];g.step(.05);assert.equal(e.hp,80);g.step(.05);assert.equal(e.hp,80);});
test("invulnerability prevents stacked damage and death settles once",()=>{const g=new Game();assert.equal(g.hurt(9),true);assert.equal(g.hurt(9),false);g.player.inv=0;g.hurt(999);assert.equal(g.result.win,false);const r=g.result;g.finish(true);assert.equal(g.result,r);assert.equal(reward(cleanSave(),r).runs,1);});
test("the first boss appears at five minutes; its defeat opens the next region",()=>{const g=new Game();g.time=299.99;g.step(.05);const boss=g.enemies.find(e=>e.boss);assert.ok(boss);g.spawnBoss();assert.equal(g.enemies.filter(e=>e.boss).length,1);g.hit(boss,99999,g.player);assert.equal(g.result,null);assert.equal(g.phase,"stage-clear");assert.equal(g.clearedStages,1);assert.equal(g.events.filter(e=>e.type==="stage-clear").length,1);});
test("ultimate damages nearby enemies, clears bullets and has a cooldown",()=>{const g=new Game(),e=g.spawn("brute");Object.assign(e,{x:1000,y:900,hp:1000});g.shots=[{x:1}];assert.equal(g.ultimate(),true);assert.equal(e.hp,1000);g.advanceUltimate(.31);assert.ok(e.hp<1000);assert.equal(g.shots.length,0);assert.equal(g.ultimate(),false);});
test("a seeded full-length simulation remains finite with bounded entity counts",()=>{
const g=new Game("mage",{},1234);g.player.inv=999;g.weapons={blade:5,arrow:5,bolt:5,orbit:5,lightning:5,frost:5};
for(let i=0;i<20000&&!g.result;i++){if(g.phase==="upgrade")g.choose(g.choices[0]);g.step(1/60,{x:Math.cos(i/120),y:Math.sin(i/120)});assert.ok(Number.isFinite(g.player.hp));assert.ok(g.enemies.length<=LIMITS.enemies);assert.ok(g.gems.length<=LIMITS.gems);}
assert.equal(g.bossSpawned,true);assert.ok(g.level>1);});

function swordFixture(){const g=new Game("knight",{},7),e=g.spawn("brute");Object.assign(e,{x:980,y:900,speed:0,hp:500,maxHp:500});g.cool.blade=999;g.spawnCd=999;return {g,e};}
test("sword damage and contact feedback wait for the visible contact phase",()=>{const {g,e}=swordFixture();g.attack("blade",1);assert.equal(e.hp,500);for(let i=0;i<8;i++)g.step(1/60);assert.equal(e.hp,500);assert.equal(g.events.filter(x=>x.type==="blade-swing").length,1);assert.equal(g.events.filter(x=>x.type==="blade-contact").length,0);g.step(1/60);assert.equal(e.hp,477);assert.equal(g.events.filter(x=>x.type==="blade-contact").length,1);for(let i=0;i<30;i++)g.step(1/60);assert.equal(e.hp,477);assert.equal(g.bladeSwing,null);});
test("sword misses do not create a false contact and enemies behind the cut are spared",()=>{const {g,e}=swordFixture(),behind=g.spawn("shade");Object.assign(behind,{x:800,y:900,speed:0,hp:500});g.attack("blade",1);for(let i=0;i<9;i++)g.step(1/60);assert.equal(e.hp,477);assert.equal(behind.hp,500);const miss=swordFixture();miss.g.attack("blade",1);miss.e.x=1400;for(let i=0;i<9;i++)miss.g.step(1/60);assert.equal(miss.e.hp,500);assert.equal(miss.g.events.filter(x=>x.type==="blade-contact").length,0);});
test("pause freezes a pending swing and impact hold preserves timing and input safety",()=>{const {g,e}=swordFixture();g.attack("blade",1);g.step(.05);g.pause();g.step(.05);assert.equal(g.bladeSwing.elapsed,.05);assert.equal(e.hp,500);g.resume();for(let i=0;i<6;i++)g.step(1/60);assert.equal(e.hp,477);const time=g.time,x=g.player.x;g.step(1/60,{x:1,y:0});assert.equal(g.time,time);assert.equal(g.player.x,x);for(let i=0;i<3;i++)g.step(1/60,{x:1,y:0});assert.ok(g.player.x>x);});
test("sword practice ends without experience levels, gems or currency rewards",()=>{const g=new Game().enablePractice();for(let i=0;i<1100&&!g.result;i++)g.step(1/60);assert.ok(g.result);assert.equal(g.result.coins,0);assert.equal(g.level,1);assert.equal(g.gems.length,0);assert.ok(g.kills>0);});

function rangedFixture(hero){const g=new Game(hero,{},7),key=g.hero.weapon,e=g.spawn("brute");Object.assign(e,{x:1010,y:900,speed:0,hp:500,maxHp:500});g.cool[key]=999;g.spawnCd=999;g.events=[];return {g,e,key};}
test("ranged attacks release once after preparation and contact only after projectile travel",()=>{for(const hero of ["ranger","mage"]){const {g,e,key}=rangedFixture(hero);g.attack(key,1);for(let i=0;i<7;i++)g.step(1/60);assert.equal(g.bullets.length,0);assert.equal(e.hp,500);assert.equal(g.events.filter(x=>x.type==="projectile-release").length,0);for(let i=0;i<40;i++)g.step(1/60);assert.equal(e.hp,key==="arrow"?488:480);assert.equal(g.events.filter(x=>x.type==="projectile-release").length,1);assert.equal(g.events.filter(x=>x.type==="projectile-contact").length,1);assert.equal(g.rangedAttacks[key],undefined);}});
test("ranged misses create no contact feedback and paused preparation does not progress",()=>{for(const hero of ["ranger","mage"]){const {g,e,key}=rangedFixture(hero);g.attack(key,1);g.step(.05);g.pause();g.step(.05);assert.equal(g.rangedAttacks[key].elapsed,.05);assert.equal(g.bullets.length,0);e.hp=0;g.resume();for(let i=0;i<80;i++)g.step(1/60);assert.equal(g.events.filter(x=>x.type==="projectile-release").length,1);assert.equal(g.events.filter(x=>x.type==="projectile-contact").length,0);}});
test("haste speeds preparation and recovery without losing evolved projectile damage or count",()=>{for(const hero of ["ranger","mage"]){const {g,key}=rangedFixture(hero);g.weapons[key]=5;g.passives={haste:5,power:2,magnet:2};g.checkEvolution();g.cool[key]=999;g.attack(key,5);for(let i=0;i<5;i++)g.step(1/60);if(key==="arrow")assert.equal(g.events.filter(x=>x.type==="projectile-release").length,1);else assert.equal(g.events.filter(x=>x.type==="projectile-release").length,0);for(let i=0;i<3;i++)g.step(1/60);const release=g.events.find(x=>x.type==="projectile-release");assert.equal(release.count,key==="arrow"?5:3);assert.equal(release.evolved,true);for(let i=0;i<20;i++)g.step(1/60);assert.equal(g.rangedAttacks[key],undefined);}});
test("ranger and mage practice retain their own weapon and end with no permanent reward",()=>{for(const hero of ["ranger","mage"]){const g=new Game(hero).enablePractice();assert.deepEqual(g.weapons,{[g.hero.weapon]:2});for(let i=0;i<1000&&!g.result;i++)g.step(1/60);assert.ok(g.result);assert.equal(g.result.coins,0);assert.equal(g.level,1);assert.equal(g.gems.length,0);assert.ok(g.kills>0);}});
