import test from "node:test";
import assert from "node:assert/strict";
import {Game,LIMITS} from "../src/core.js";
import {STAGE_SKILLS} from "../src/campaign.js";
import {launchCampaignSkill,advanceCampaignField,campaignProjectileContact} from "../src/campaign-combat.js";
function scene(hero="knight"){const g=new Game(hero,{},17);g.stage=5;g.weapons={};g.spawnCd=g.nextElite=g.nextMagnet=g.nextRift=9999;g.player.inv=999;g.hitStopEnabled=false;return g;}
function target(g,x=1020,y=900){const e=g.spawn("brute");Object.assign(e,{x,y,hp:30000,maxHp:30000,speed:0,shoot:999});return e;}
function frames(g,n){for(let i=0;i<n;i++)g.step(1/60);}
test("missing targets never create authoritative sword contacts",()=>{for(const key of ["crosscut","phantom","thousand"]){const g=scene();target(g,1600,1600);g.attack(key,5);frames(g,145);assert.equal(g.events.filter(e=>["skill-contact","skill-finish","projectile-contact"].includes(e.type)).length,0,key);}});
test("dot damage has no displacement, hard impact or contact sound event",()=>{for(const key of ["bleed","burn","poison-dot","thorns"]){const g=scene("mage"),e=target(g);g.damageKey=key;const x=e.x;g.hit(e,10,g.player);assert.equal(e.x,x);assert.equal(e.hp,29990);assert.ok(!g.events.some(e=>e.type.includes("contact")));assert.ok(!g.fx.some(f=>["impact","cut-hit","bolt-hit"].includes(f.kind)));assert.equal(e.hitImpulse,undefined);}});
test("area damage counts real contacts including killing blows and skips dead enemies",()=>{const g=scene(),a=target(g,930),b=target(g,950),dead=target(g,940);a.hp=3;dead.hp=0;g.damageKey="slam";assert.equal(g.areaHit({x:900,y:900,r:90,key:"slam"},10),2);assert.equal(a.hp,-7);assert.equal(b.hp,29990);assert.equal(dead.hp,0);assert.equal(g.areaHit({x:1500,y:1500,r:20},10),0);});
test("black flame slows only enemies inside its visible lanes",()=>{const g=scene("mage"),inside=target(g,1040),outside=target(g,1040,1120);g.attack("blackflame",3);frames(g,35);assert.ok(inside.hp<30000&&inside.slow>0);assert.equal(outside.hp,30000);assert.equal(outside.slow,0);});
test("storm bow awakening schedules lightning before its delayed ground hit",()=>{const g=scene("ranger"),a=target(g,1040),b=target(g,1100,925);campaignProjectileContact(g,{key:"stormbow",chain:2,stormStrike:true,lv:5,damage:50,vx:620,vy:0,seed:7},a);const fields=g.skillFields.filter(f=>f.visualKey==="stormbow");assert.equal(fields.length,2);assert.ok(fields.every(f=>f.key==="judgment"&&f.marks[0].at===.32&&!f.marks[0].hit));const hp=a.hp;frames(g,10);assert.equal(a.hp,hp);frames(g,15);assert.ok(a.hp<hp);assert.ok(g.events.some(e=>e.type==="skill-impact"&&e.key==="stormbow"));});
test("thousand swords preserve anticipation and reserve the great cleave for level five",()=>{for(const lv of [1,3,5]){const g=scene(),e=target(g,990);g.attack("thousand",lv);frames(g,25);assert.equal(e.hp,30000);frames(g,130);assert.ok(e.hp<30000);assert.equal(g.events.some(e=>e.type==="skill-finish"&&e.key==="thousand"),lv===5);}});
test("ballista reports mechanical shot time and keeps its own contact material",()=>{const g=scene("ranger");target(g);g.attack("ballista",5);frames(g,38);const f=g.skillFields.find(f=>f.key==="ballista");assert.ok(f.shots>=1&&f.shotAt>=.45&&f.recoil>0);assert.equal(f.shotAt,f.lastShotAge);assert.ok(g.bullets.every(b=>b.key==="ballista"));frames(g,50);assert.ok(g.events.some(e=>e.type==="projectile-contact"&&e.key==="ballista"));assert.ok(!g.events.some(e=>e.type==="projectile-contact"&&e.key==="piercing"));});
test("dragon collision covers segments between mesh points and excludes off-body targets",()=>{const g=scene("mage"),inside=target(g,1130),outside=target(g,1130,1060);const f={key:"dragon",x:900,y:900,tx:1150,ty:900,angle:0,lv:1,evolved:false,area:1,length:290,r:24,age:1,ttl:1,tick:0,damage:20,paths:[],duration:1.7,finalAt:1.46,canFinish:false,seed:2};advanceCampaignField(g,f,1/60);assert.equal(f.paths[0].length,17);assert.ok(inside.hp<30000);assert.equal(outside.hp,30000);assert.ok(g.events.some(e=>e.type==="skill-contact"&&e.phase==="sustain"));});
test("contact pauses have a shared cadence and continuous damage never freezes simulation",()=>{const g=scene();g.hitStopEnabled=true;g.time=2;g.contactFeedback("skill-contact","thousand",{hits:1,phase:"contact"});assert.equal(g.hitPause,.014);g.hitPause=0;g.time+=.1;g.contactFeedback("skill-contact","ballista",{hits:1,phase:"contact"});assert.equal(g.hitPause,0);g.time+=.3;g.contactFeedback("skill-contact","dragon",{hits:1,phase:"sustain"});assert.equal(g.hitPause,0);g.contactFeedback("skill-contact","thousand",{hits:1,phase:"finish"});assert.equal(g.hitPause,.035);});
test("sustained hits coalesce damage text and cap recoil instead of pushing every tick",()=>{const g=scene("mage"),e=target(g);g.damageKey="beam";const x=e.x;for(let i=0;i<8;i++){g.time+=.03;g.hit(e,5,{x:900,y:900,contactPhase:"sustain"});}assert.equal(e.x-x,2);assert.equal(g.fx.filter(f=>f.kind==="text").length,1);assert.equal(g.fx.find(f=>f.kind==="text").n,40);assert.equal(e.hitForce,.22);});
test("all later evolved skills keep real contact metadata and bounded entities",()=>{for(const [key,u]of Object.entries(STAGE_SKILLS)){const g=scene(u.hero);g.evolved[key]=true;for(let i=0;i<8;i++)target(g,975+i%2*35,850+Math.floor(i/2)*35);g.attack(key,5);frames(g,165);assert.ok(g.events.some(e=>["skill-contact","projectile-contact"].includes(e.type)&&e.key===key),key);for(const e of g.events.filter(e=>["skill-contact","projectile-contact","skill-finish"].includes(e.type))){assert.ok(e.hits>0);assert.ok(Number.isFinite(e.angle));}assert.ok(g.bullets.length<=LIMITS.bullets&&g.skillFields.length<=LIMITS.fields);assert.ok(g.enemies.every(e=>Number.isFinite(e.hp)&&Number.isFinite(e.x)&&Number.isFinite(e.y)));}});

test("dragon thin tail does not damage enemies outside its visible taper",()=>{const g=scene("mage"),f={key:"dragon",x:900,y:900,tx:1200,ty:900,angle:0,lv:1,evolved:false,area:1,length:300,r:24,age:1,ttl:1,tick:0,damage:20,paths:[],duration:1.7,finalAt:1.46,canFinish:false,seed:2};advanceCampaignField(g,f,1/60);const point=f.paths[0][1],a=f.paths[0][0],b=f.paths[0][2],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),e=target(g,point.x-dy/len*11,point.y+dx/len*11);e.r=1;f.tick=0;advanceCampaignField(g,f,1/60);assert.equal(e.hp,30000,"Tail damaged beyond the visible body");const head=f.paths[0][14];e.x=head.x;e.y=head.y;f.tick=0;advanceCampaignField(g,f,1/60);assert.ok(e.hp<30000,"Solid body missed a real contact");});
