import {test,expect} from "@playwright/test";
test.beforeEach(async({page})=>{await page.goto("/");await expect(page.locator("#home")).toBeVisible();});
test("home has three heroes and gameplay draws real 2D art",async({page})=>{
await expect(page.locator(".hero")).toHaveCount(3);await page.getByRole("button",{name:"별빛 궁수",exact:true}).click();await expect(page.locator("#hero-description")).toContainText("화살");await page.screenshot({path:"test-results/home.png"});
await page.locator("#start").click();await expect(page.locator("#hud")).toBeVisible();expect(await page.evaluate(()=>window.__riftTest.game.hero.id)).toBe("ranger");
const colors=await page.evaluate(()=>{const c=document.querySelector("#world"),d=c.getContext("2d").getImageData(0,0,c.width,c.height).data,s=new Set();for(let i=0;i<d.length;i+=400)s.add(d[i]+","+d[i+1]+","+d[i+2]);return s.size;});expect(colors).toBeGreaterThan(10);await page.screenshot({path:"test-results/gameplay.png"});});
test("drag moves the hero and release stops movement",async({page})=>{
await page.locator("#start").click();const before=await page.evaluate(()=>window.__riftTest.game.player.x);await page.mouse.move(160,430);await page.mouse.down();await page.mouse.move(240,430,{steps:5});await page.waitForTimeout(300);await page.mouse.up();
const after=await page.evaluate(()=>window.__riftTest.game.player.x);expect(after).toBeGreaterThan(before+20);await page.waitForTimeout(150);expect(await page.evaluate(()=>window.__riftTest.game.player.x)).toBeCloseTo(after,0);});
test("level choices freeze combat and apply one upgrade",async({page})=>{
await page.locator("#start").click();await page.evaluate(()=>window.__riftTest.giveXP(8));await expect(page.locator(".upgrade")).toHaveCount(3);const t=await page.evaluate(()=>window.__riftTest.game.time);await page.waitForTimeout(150);expect(await page.evaluate(()=>window.__riftTest.game.time)).toBe(t);await page.screenshot({path:"test-results/skills.png"});
await page.locator(".upgrade").first().click();await expect(page.locator("#overlay")).toBeHidden();expect(await page.evaluate(()=>window.__riftTest.game.phase)).toBe("playing");expect(await page.evaluate(()=>window.__riftTest.game.pending)).toBe(0);});
test("pause and background stop gameplay until explicit resume",async({page})=>{
await page.locator("#start").click();await page.locator("#pause").click();await expect(page.locator("#resume")).toBeVisible();const t=await page.evaluate(()=>window.__riftTest.game.time);await page.waitForTimeout(150);expect(await page.evaluate(()=>window.__riftTest.game.time)).toBe(t);await page.locator("#resume").click();
await page.evaluate(()=>window.dispatchEvent(new Event("blur")));await expect(page.locator("#resume")).toBeVisible();await page.locator("#resume").click();expect(await page.evaluate(()=>window.__riftTest.game.phase)).toBe("playing");});
test("victory rewards once and records survive reload",async({page})=>{
await page.locator("#start").click();await page.evaluate(()=>{window.__riftTest.game.kills=24;window.__riftTest.finish(true);});await expect(page.locator("#dialog-title")).toContainText("균열을 닫았어요");await page.evaluate(()=>window.__riftTest.flush());expect(await page.evaluate(()=>window.__riftTest.save.coins)).toBe(74);await page.screenshot({path:"test-results/victory.png"});await page.reload();await expect(page.locator("#home")).toBeVisible();await expect(page.locator("#coins")).toHaveText("74");await expect(page.locator("#wins")).toHaveText("1");});
test("affordable upgrades and sound settings persist",async({page})=>{
await page.locator("#start").click();await page.evaluate(()=>window.__riftTest.finish(true));await expect(page.locator("#result-home")).toBeVisible();await page.locator("#result-home").click();await page.locator("#forge").click();await page.locator('[data-forge="power"]').click();expect(await page.evaluate(()=>window.__riftTest.save.meta.power)).toBe(1);await page.locator("#forge-close").click();await page.locator("#settings").click();await page.locator("#sound").click();await expect(page.locator("#sound")).toHaveText("꺼짐");await page.evaluate(()=>window.__riftTest.flush());await page.reload();await expect(page.locator("#home")).toBeVisible();expect(await page.evaluate(()=>window.__riftTest.save.meta.power)).toBe(1);expect(await page.evaluate(()=>window.__riftTest.save.settings.sound)).toBe(false);});
test("exit is confirmed, cancellation preserves run, exit saves rewards",async({page})=>{
await page.locator("#start").click();await page.evaluate(()=>window.__riftTest.requestExit());await expect(page.locator("#exit-confirm")).toBeVisible();await page.locator("#exit-cancel").click();await expect(page.locator("#resume")).toBeVisible();await page.locator("#resume").click();await page.evaluate(()=>window.__riftTest.requestExit());await page.locator("#exit-confirm").click();await expect(page.locator("#home")).toBeVisible();expect(await page.evaluate(()=>window.__riftTest.save.runs)).toBe(1);});
test("small phones retain a reachable start button",async({page})=>{
await page.setViewportSize({width:360,height:640});await expect(page.locator("#start")).toBeVisible();const b=await page.locator("#start").boundingBox();expect(b.y+b.height).toBeLessThan(640);await page.screenshot({path:"test-results/small-phone.png"});});
test("all dialogs and a short fight have no uncaught errors",async({page})=>{
const errors=[];page.on("pageerror",e=>errors.push(e.message));for(const [open,close]of [["help","help-close"],["privacy","privacy-close"],["forge","forge-close"],["settings","settings-close"]]){await page.locator("#"+open).click();await page.locator("#"+close).click();}
await page.locator("#start").click();await page.locator("#ultimate").click();await page.waitForTimeout(800);await page.locator("#dash").click();await page.locator("#pause").click();await page.locator("#retire").click();await expect(page.locator("#again")).toBeVisible();expect(errors).toEqual([]);});
test("three rerolls retain the earned level and disable when exhausted",async({page})=>{
await page.locator("#start").click();await page.evaluate(()=>window.__riftTest.giveXP(8));await expect(page.locator("#reroll")).toContainText("3회");for(let i=0;i<3;i++)await page.locator("#reroll").click();await expect(page.locator("#reroll")).toBeDisabled();expect(await page.evaluate(()=>window.__riftTest.game.pending)).toBe(1);await page.locator(".upgrade").first().click();await expect(page.locator("#overlay")).toBeHidden();
});
test("performance choices persist and battery mode lowers resolution and target frame rate",async({page})=>{
await page.locator("#settings").click();await expect(page.locator("#performance")).toHaveText("자동");await page.locator("#performance").click();await page.locator("#performance").click();await expect(page.locator("#performance")).toHaveText("배터리 절약");await page.evaluate(()=>window.__riftTest.flush());await page.reload();await expect(page.locator("#home")).toBeVisible();await page.locator("#start").click();expect(await page.evaluate(()=>window.__riftTest.budget.targetFPS)).toBe(30);expect(await page.evaluate(()=>window.__riftTest.renderer.quality)).toBeCloseTo(.65);
});
test("evolution changes the visible skill name and combat weapon",async({page})=>{
await page.locator("#start").click();await page.evaluate(()=>{const g=window.__riftTest.game;g.weapons.blade=5;g.passives.power=2;g.checkEvolution();});await expect(page.locator("#skills .skill")).toHaveAttribute("aria-label","태양의 대검 5레벨");await expect(page.locator("#banner")).toContainText("진화");
});
test("a restored page keeps its run paused and can resume with working controls",async({page})=>{
await page.locator("#start").click();await page.evaluate(()=>window.dispatchEvent(new Event("pagehide")));await expect(page.locator("#resume")).toBeVisible();const t=await page.evaluate(()=>window.__riftTest.game.time);await page.evaluate(()=>window.dispatchEvent(new Event("pageshow")));await page.waitForTimeout(100);expect(await page.evaluate(()=>window.__riftTest.game.time)).toBe(t);await page.locator("#resume").click();await page.keyboard.press("d");await page.waitForTimeout(100);expect(await page.evaluate(()=>window.__riftTest.game.time)).toBeGreaterThan(t);
});
test("portrait short screens can show all upgrade actions without losing the choice",async({page})=>{
await page.setViewportSize({width:360,height:640});await page.locator("#start").click();await page.evaluate(()=>window.__riftTest.giveXP(8));await expect(page.locator(".upgrade")).toHaveCount(3);await page.locator("#reroll").click();await page.locator(".upgrade").last().click();await expect(page.locator("#overlay")).toBeHidden();
});
test("backgrounding silences audio voices and cancels delayed sound effects",async({page})=>{
await page.locator("#start").click();await page.locator("#ultimate").click();await page.evaluate(()=>window.dispatchEvent(new Event("blur")));await expect(page.locator("#resume")).toBeVisible();await page.waitForTimeout(200);expect(await page.evaluate(()=>window.__riftTest.audio.timer)).toBeNull();expect(await page.evaluate(()=>window.__riftTest.audio.delayed.size)).toBe(0);expect(await page.evaluate(()=>window.__riftTest.audio.context?.state)).toBe("suspended");
});
test("stress scene remains responsive with capped entities and reports frame costs",async({page},testInfo)=>{
await page.locator("#start").click();await page.evaluate(()=>{const g=window.__riftTest.game;g.player.inv=999;g.spawnCd=999;g.nextElite=999;g.weapons={blade:5,arrow:5,bolt:5,orbit:5};g.passives={power:2,haste:3,heart:2,magnet:2};g.checkEvolution();for(let i=0;i<170;i++){const e=g.spawn(i%3?"shade":"brute");e.hp=e.maxHp=10000;const a=i*Math.PI*2/170,r=100+(i%7)*55;e.x=900+Math.cos(a)*r;e.y=900+Math.sin(a)*r;}});
const values=await page.evaluate(async()=>{const samples=[];for(let i=0;i<90;i++){await new Promise(requestAnimationFrame);const m=window.__riftTest.metrics;samples.push({updateMs:m.updateMs,renderMs:m.renderMs,frameMs:m.frameMs});}const g=window.__riftTest.game;return {engine:navigator.userAgent,samples,counts:{enemies:g.enemies.length,bullets:g.bullets.length,shots:g.shots.length,fx:g.fx.length},canvas:{width:window.__riftTest.renderer.canvas.width,height:window.__riftTest.renderer.canvas.height}};});
expect(values.counts.enemies).toBeLessThanOrEqual(180);expect(values.counts.bullets).toBeLessThanOrEqual(180);expect(values.counts.fx).toBeLessThanOrEqual(160);expect(values.samples.every(x=>Number.isFinite(x.updateMs)&&Number.isFinite(x.renderMs))).toBe(true);await testInfo.attach("stress-frame-samples",{body:JSON.stringify(values,null,2),contentType:"application/json"});await page.locator("#pause").click();await expect(page.locator("#resume")).toBeVisible();
});
